import type { FC } from "react";
import type { MDXComponents } from "mdx/types";

type MDXModule = { default: FC<{ components?: MDXComponents }> };

/** slug → sampler MDX body. GENERATED by scripts/gen-content.mjs. */
export const careerMdx: Record<string, () => Promise<MDXModule>> = {
  "accounting": () => import("./accounting.mdx"),
  "agriculture": () => import("./agriculture.mdx"),
  "allied-health": () => import("./allied-health.mdx"),
  "architecture": () => import("./architecture.mdx"),
  "business": () => import("./business.mdx"),
  "construction": () => import("./construction.mdx"),
  "cybersecurity": () => import("./cybersecurity.mdx"),
  "data-science": () => import("./data-science.mdx"),
  "dentistry": () => import("./dentistry.mdx"),
  "design": () => import("./design.mdx"),
  "engineering": () => import("./engineering.mdx"),
  "finance": () => import("./finance.mdx"),
  "hospitality": () => import("./hospitality.mdx"),
  "journalism": () => import("./journalism.mdx"),
  "law": () => import("./law.mdx"),
  "life-sciences": () => import("./life-sciences.mdx"),
  "marketing": () => import("./marketing.mdx"),
  "medicine": () => import("./medicine.mdx"),
  "nursing": () => import("./nursing.mdx"),
  "pharmacy": () => import("./pharmacy.mdx"),
  "psychology": () => import("./psychology.mdx"),
  "social-work": () => import("./social-work.mdx"),
  "teaching": () => import("./teaching.mdx"),
  "trades": () => import("./trades.mdx"),
  "translation": () => import("./translation.mdx"),
  "transport": () => import("./transport.mdx"),
  "veterinary": () => import("./veterinary.mdx"),
};

export const samplerSlugs = Object.keys(careerMdx);
export function hasSamplerPage(slug: string): boolean { return slug in careerMdx; }
