import type { FC } from "react";
import type { MDXComponents } from "mdx/types";

type MDXModule = { default: FC<{ components?: MDXComponents }> };

/** slug → sampler MDX body (the *career* voice). GENERATED by scripts/gen-content.mjs. */
export const careerMdx: Record<string, () => Promise<MDXModule>> = {
  "accounting": () => import("./accounting.mdx"),
  "agriculture": () => import("./agriculture.mdx"),
  "allied-health": () => import("./allied-health.mdx"),
  "architecture": () => import("./architecture.mdx"),
  "business": () => import("./business.mdx"),
  "construction": () => import("./construction.mdx"),
  "cybersecurity": () => import("./cybersecurity.mdx"),
  "data-science": () => import("./data-science.mdx"),
  "dentistry": () => import("./dentistry.mdx"),
  "design": () => import("./design.mdx"),
  "engineering": () => import("./engineering.mdx"),
  "finance": () => import("./finance.mdx"),
  "hospitality": () => import("./hospitality.mdx"),
  "journalism": () => import("./journalism.mdx"),
  "law": () => import("./law.mdx"),
  "life-sciences": () => import("./life-sciences.mdx"),
  "marketing": () => import("./marketing.mdx"),
  "medicine": () => import("./medicine.mdx"),
  "nursing": () => import("./nursing.mdx"),
  "pharmacy": () => import("./pharmacy.mdx"),
  "psychology": () => import("./psychology.mdx"),
  "social-work": () => import("./social-work.mdx"),
  "teaching": () => import("./teaching.mdx"),
  "trades": () => import("./trades.mdx"),
  "translation": () => import("./translation.mdx"),
  "transport": () => import("./transport.mdx"),
  "veterinary": () => import("./veterinary.mdx"),
};

/**
 * slug → the *studying* voice of the same Career Map (for someone still choosing
 * what to study), where one exists. Same scores, same components; the framing
 * prose differs. GENERATED from the <slug>-studying.mdx files present on disk.
 */
export const careerMdxStudying: Record<string, () => Promise<MDXModule>> = {
  "accounting": () => import("./accounting-studying.mdx"),
  "agriculture": () => import("./agriculture-studying.mdx"),
  "allied-health": () => import("./allied-health-studying.mdx"),
  "architecture": () => import("./architecture-studying.mdx"),
  "business": () => import("./business-studying.mdx"),
  "construction": () => import("./construction-studying.mdx"),
  "cybersecurity": () => import("./cybersecurity-studying.mdx"),
  "data-science": () => import("./data-science-studying.mdx"),
  "dentistry": () => import("./dentistry-studying.mdx"),
  "design": () => import("./design-studying.mdx"),
  "engineering": () => import("./engineering-studying.mdx"),
  "finance": () => import("./finance-studying.mdx"),
  "hospitality": () => import("./hospitality-studying.mdx"),
  "journalism": () => import("./journalism-studying.mdx"),
  "law": () => import("./law-studying.mdx"),
  "life-sciences": () => import("./life-sciences-studying.mdx"),
  "marketing": () => import("./marketing-studying.mdx"),
  "medicine": () => import("./medicine-studying.mdx"),
  "nursing": () => import("./nursing-studying.mdx"),
  "pharmacy": () => import("./pharmacy-studying.mdx"),
  "psychology": () => import("./psychology-studying.mdx"),
  "social-work": () => import("./social-work-studying.mdx"),
  "teaching": () => import("./teaching-studying.mdx"),
  "trades": () => import("./trades-studying.mdx"),
  "translation": () => import("./translation-studying.mdx"),
  "transport": () => import("./transport-studying.mdx"),
  "veterinary": () => import("./veterinary-studying.mdx"),
};

export const samplerSlugs = Object.keys(careerMdx);
export function hasSamplerPage(slug: string): boolean { return slug in careerMdx; }
export function hasStudyingVersion(slug: string): boolean { return slug in careerMdxStudying; }
