/* Healthcare & Nursing — a Judgment Gym lane. The AI drafts the documentation;
   you're the clinician who reviews it and signs off. The app doesn't give medical
   advice — it trains the judgment of checking AI-drafted notes against the orders,
   the chart, and standard practice before your name goes on them. Same shape as
   every other lane (see lib/gym.ts). All items tagged mode + failure pattern. */

import type { Scenario } from "@/lib/gym";

export const HEALTH_SCENARIOS: Record<string, Scenario> = {
  "health-discharge": {
    slug: "health-discharge", career: "Healthcare & Nursing", kind: "document",
    short: "Sign off an AI-drafted discharge summary against the chart and orders — meds, interactions, instructions.",
    client: "Medical ward — 68-year-old, post-pneumonia discharge",
    artifact: "Discharge_Summary.draft",
    thesis: "The AI drafted this discharge summary from the chart — diagnoses, the medication list, the patient instructions. It reads complete and confident. The patient goes home on what's written here, and you're the nurse signing it. Sign off only what matches the orders and the record.",
    role: "You're the nurse signing this discharge off — the patient goes home on exactly what's on this page.",
    aiDid: "The AI assembled the summary end-to-end from the notes and the medication chart. Some lines don't match the orders, the allergy record, or standard practice.",
    brief: [
      { l: "Patient", v: "68, admitted with community-acquired pneumonia, now stable for discharge" },
      { l: "On file", v: "Warfarin for atrial fibrillation (long-term); furosemide 40 mg once daily" },
      { l: "This admission", v: "A short antibiotic course started for the pneumonia" },
      { l: "Rule", v: "The summary must match the orders and the chart before you sign" },
    ],
    items: [
      { area: "Antibiotic course", verdict: "flag", severity: "critical", mode: "fact", pattern: "omission",
        output: "“Continue clarithromycin 500 mg twice daily for 5 days.” (Patient remains on warfarin.)",
        why: "A known interaction goes unflagged. Clarithromycin inhibits warfarin's metabolism and pushes the INR up — a well-documented interaction — yet the summary sends the patient home on both with no INR check or caution noted. The drugs are each fine; the missing safeguard is the error.",
        cost: "An unmonitored rise in INR after discharge is a bleeding risk that lands the patient back in the ED — and the summary you signed said nothing.",
        trains: "Checking an AI med list for the interaction it didn't surface, not just that each drug is reasonable." },
      { area: "Warfarin instruction", verdict: "flag", severity: "critical", mode: "fact", pattern: "overreach",
        output: "“You may stop taking your warfarin now that the infection has cleared.”",
        why: "No one ordered this. Warfarin is for the patient's atrial fibrillation, not the pneumonia — a long-term therapy the infection has nothing to do with. The draft invented a medication change that appears nowhere in the orders.",
        cost: "A patient who stops anticoagulation on a written instruction is a stroke risk — a change no clinician made, put in the patient's hands under your signature.",
        trains: "Reading a discharge instruction against what was actually ordered, not what sounds tidy." },
      { area: "Diuretic dose", verdict: "flag", severity: "major", mode: "fact", pattern: "miscalc",
        output: "“Furosemide 400 mg by mouth once daily.”",
        why: "A ten-fold error. The order and the home dose are furosemide 40 mg once daily — 400 mg is a decimal slip that reads plausibly on the page but is ten times the intended dose.",
        cost: "A ten-fold diuretic overdose sent home in writing — dehydration, electrolyte loss, and a fall risk, from a misplaced zero no one re-read.",
        trains: "Re-checking a dose and its units against the order, not trusting a clean-looking number." },
      { area: "Active problem list", verdict: "flag", severity: "minor", mode: "fact", pattern: "stale",
        output: "Active problems include “acute kidney injury — ongoing.”",
        why: "Copied forward from the prior admission. The creatinine returned to baseline this stay, so the AKI is resolved, not ongoing — the draft carried a stale problem across without checking it against this admission's results.",
        cost: "A resolved problem listed as active misdirects the primary care follow-up and clutters the record the next clinician trusts.",
        trains: "Testing a carried-forward problem against the current chart, not letting last admission's list stand." },
      { area: "Return precautions", verdict: "ship", mode: "judgment",
        output: "“Return to the emergency department if you develop chest pain, worsening breathlessness, or a fever above 100.4°F (38°C).”",
        why: "Sound safety-netting. Clear, specific red-flag symptoms and where to go — exactly what a discharge should tell a post-pneumonia patient.",
        cost: "Rewriting good, specific return advice only dulls it and delays the discharge.",
        trains: "Recognizing appropriate safety-netting and letting it stand." },
      { area: "Home medication", verdict: "ship", mode: "fact",
        output: "“Continue metformin 500 mg twice daily, unchanged.”",
        why: "Reconciles. The dose and frequency match the admission medication history, and nothing this stay changed it — a correctly continued home med.",
        cost: "Querying a home med that ties to the reconciliation just delays a ready discharge.",
        trains: "Confirming a continued medication matches the reconciliation and moving on." },
    ],
    lesson: "The unflagged clarithromycin interaction and the “stop your warfarin” line were the two that would have been yours to answer for. The AI drafts the summary in seconds — but the patient goes home on what you sign, and the check against the orders is the judgment that's yours.",
  },

  "health-care-plan": {
    slug: "health-care-plan", career: "Healthcare & Nursing", kind: "document",
    short: "Sign off an AI-built post-op nursing care plan against the orders and the chart — PRN meds, mobility, fluids, the vitals story.",
    client: "Surgical ward — day 1 after a hip replacement",
    artifact: "Care_Plan.draft",
    thesis: "The AI built the post-op nursing care plan — goals, PRN medications, mobility, fluids, monitoring. It's structured and complete. You own this plan and the shift runs on it. Sign off only what holds against the orders, the allergy record, and standard practice.",
    role: "You're the nurse who owns this care plan — the shift delivers what's on it.",
    aiDid: "The AI generated the plan from the operative note and the chart. Some of it contradicts the surgeon's orders, the allergy record, or the assessment in front of you.",
    brief: [
      { l: "Patient", v: "Day 1 after a total hip replacement, otherwise stable" },
      { l: "On file", v: "Documented allergy to morphine (rash); non-weight-bearing ordered by the surgeon for 6 weeks" },
      { l: "Watch", v: "The PRN analgesia, the mobility goal, the fluids, and the observations note" },
      { l: "Rule", v: "The plan must match the orders and reconcile to the chart" },
    ],
    items: [
      { area: "PRN analgesia", verdict: "flag", severity: "critical", mode: "fact", pattern: "omission",
        output: "“Breakthrough pain: morphine 5 mg IV PRN.”",
        why: "The allergy wasn't reconciled. The chart documents a morphine allergy, and the plan schedules morphine PRN anyway — the draft never checked the analgesia against the allergy record.",
        cost: "A drug the patient is allergic to, standing as a PRN order for any nurse to give at 3am — an avoidable reaction that traces straight to this plan.",
        trains: "Reconciling every drug on the plan against the allergy record before it's live." },
      { area: "Vitals note", verdict: "flag", severity: "critical", mode: "judgment", pattern: "unverified",
        output: "“Heart rate up and urine output down since return from theatre — consistent with post-op anxiety. Continue to monitor.”",
        why: "A tidy explanation accepted without the check. A rising heart rate with falling urine output on day 1 post-op is what you're taught to work up for hypovolemia or bleeding — the plan wrote a reassuring reason and closed the point instead of prompting the fluid balance, the trend, and escalation.",
        cost: "Early bleeding gets a “monitor” label and a head start; by the time it's obvious, the window to catch it cheaply has closed.",
        trains: "Refusing a reassuring explanation for a red-flag trend until the checks are done — the skepticism the draft skipped." },
      { area: "Mobility goal", verdict: "flag", severity: "major", mode: "fact", pattern: "stale",
        output: "“Mobility: weight-bear as tolerated, mobilize twice daily with the physiotherapist.”",
        why: "Contradicts this patient's order. The operative note specifies non-weight-bearing for six weeks; “weight-bear as tolerated” is a generic template goal the draft carried in without checking the surgeon's actual instruction.",
        cost: "Weight-bearing against a non-weight-bearing order can disrupt the repair and mean a return to theatre — a plan-level error acted on by the whole team.",
        trains: "Checking a standard goal against this patient's specific order, not letting the template win." },
      { area: "IV fluids", verdict: "flag", severity: "major", mode: "fact", pattern: "miscalc",
        output: "“Maintenance fluid: 1,000 mL over 8 hours — set the pump to 250 mL/hr.”",
        why: "The rate is wrong. 1,000 mL over 8 hours is 125 mL/hr; 250 mL/hr runs it in at double the ordered rate and empties the bag in four hours. A clean arithmetic slip on the pump setting.",
        cost: "Fluid delivered at twice the ordered rate — a real risk in an older post-op patient, from a rate no one re-derived.",
        trains: "Re-performing the pump rate against the volume and time, not trusting the printed number." },
      { area: "VTE prophylaxis", verdict: "ship", mode: "judgment",
        output: "“VTE prophylaxis: enoxaparin per the post-op protocol plus intermittent pneumatic compression, first dose timed to the surgeon's post-op bleeding window.”",
        why: "Correct and complete. Pharmacological plus mechanical prophylaxis, with the first dose timed to the bleeding window — exactly the standard for a hip replacement.",
        cost: "Second-guessing a well-formed prophylaxis plan just delays care the patient needs.",
        trains: "Recognizing a protocol-consistent prophylaxis plan and letting it stand." },
      { area: "Pain assessment", verdict: "ship", mode: "fact",
        output: "“Assess pain on a 0–10 scale every 4 hours and after each intervention, documenting the effect.”",
        why: "Sound. Regular scored assessment plus reassessment after each intervention, documented — the correct monitoring cadence for post-op pain.",
        cost: "Reworking a clear, standard assessment schedule adds nothing but delay.",
        trains: "Confirming an appropriate assessment cadence and moving on." },
    ],
    lesson: "The morphine PRN against a morphine allergy and the vitals waved off as “anxiety” were the two that would have been yours to answer for. The AI structures a plan in seconds — but the shift acts on what you sign, and the check against the orders and the patient in front of you is yours alone.",
  },

  "health-handoff": {
    slug: "health-handoff", career: "Healthcare & Nursing", kind: "memo",
    short: "Sign off an AI-drafted SBAR handoff against the chart — the assessment, the labs, the events, the recommendation.",
    client: "Night handoff — SBAR to the oncoming shift",
    artifact: "SBAR_Handoff.draft",
    thesis: "The AI drafted the SBAR handoff from the shift's charting — Situation, Background, Assessment, Recommendation. The oncoming nurse runs the next shift on what's written here. You're handing over, and you sign the note. Sign off only what matches the chart and holds up against standard practice.",
    role: "You're the nurse giving this handoff — the next shift acts on what it says.",
    aiDid: "The AI compiled the SBAR from the notes and the results. Some of it mis-states the chart, waves off a warning sign, or hands over the wrong thing.",
    brief: [
      { l: "Patient", v: "74, day 3 of an admission for a COPD exacerbation, on treatment-dose anticoagulation" },
      { l: "Overnight", v: "New confusion from ~2am; a critical potassium result flagged by the lab" },
      { l: "Watch", v: "The assessment, the labs, the overnight events, and the recommendation" },
      { l: "Rule", v: "Every line must tie to the chart; hand over the risks, don't smooth them" },
    ],
    items: [
      { area: "Assessment — confusion", verdict: "flag", severity: "critical", mode: "judgment", pattern: "unverified",
        output: "“A: Patient confused since ~2am — likely sundowning, no action needed.”",
        why: "A reassuring label with no work behind it. New overnight confusion in an older patient is what you check for hypoxia, infection, or a low glucose before you call it sundowning — the draft accepted the tidy explanation and closed the point.",
        cost: "A treatable cause of delirium gets handed over as “nothing to do,” and the oncoming nurse inherits a patient who was never worked up.",
        trains: "Refusing a comfortable explanation for a new sign until the basic checks are done." },
      { area: "Background — potassium", verdict: "flag", severity: "critical", mode: "fact", pattern: "fabrication",
        output: "“B: Bloods this morning unremarkable — potassium 4.1.”",
        why: "The chart says otherwise. The morning potassium was 6.1 — a critical high the lab flagged — not 4.1. The handoff states a normal value the record contradicts.",
        cost: "A critical result handed over as normal disappears from the next shift's radar — the one number that most needed watching, reported as fine.",
        trains: "Tying every value in a handoff back to the actual result, not the confident figure in the draft." },
      { area: "Overnight events", verdict: "flag", severity: "critical", mode: "fact", pattern: "omission",
        output: "“No overnight events to report.”",
        why: "A material omission. The notes record an unwitnessed fall with a head strike at ~3am while the patient is on treatment-dose anticoagulation — the single most important thing to hand over, and the SBAR says nothing happened.",
        cost: "A head injury on anticoagulation, with a real bleed risk, isn't watched because the next shift was told there was nothing to watch.",
        trains: "Catching the event the summary leaves out — the omission is invisible unless you read it against the notes." },
      { area: "Recommendation — family", verdict: "flag", severity: "major", mode: "judgment", pattern: "overreach",
        output: "“R: Reassured the family the patient will definitely go home tomorrow.”",
        why: "A commitment no one made. Discharge is a clinical decision that hasn't been taken, and a patient who was confused and had a fall overnight is further from it, not closer — the draft put a firm promise to the family into the handover.",
        cost: "A promise the team now has to walk back, made in writing on the handover — eroded trust and a discharge decision pre-empted.",
        trains: "Catching the commitment the draft made beyond what's been decided or ordered." },
      { area: "Situation", verdict: "ship", mode: "fact",
        output: "“S: 74-year-old, day 3 of an admission for a COPD exacerbation, on day 3 of IV antibiotics, on 2 L oxygen with saturations 94%.”",
        why: "Accurate and concise. A clean situation line that ties to the chart and orients the oncoming nurse in a sentence — exactly what the S should do.",
        cost: "Rewriting a clear, correct situation summary just slows the handover.",
        trains: "Recognizing an accurate, concise summary and letting it stand." },
      { area: "Recommendation — escalation", verdict: "ship", mode: "judgment",
        output: "“R: Continue 4-hourly observations and escalate to the on-call team if the early-warning score rises above 5, per protocol.”",
        why: "Sound. A concrete monitoring cadence with a clear, protocol-based escalation trigger — the actionable recommendation a good handover ends on.",
        cost: "Second-guessing a clear, protocol-consistent escalation plan wastes handover time.",
        trains: "Confirming an actionable, protocol-based recommendation and moving on." },
    ],
    lesson: "The confusion waved off as “sundowning,” the critical potassium reported as normal, and the overnight fall left off the page were the ones that would have been yours to answer for. The AI writes a tidy SBAR in seconds — but the next shift runs on what you hand over, and reading it against the chart is the judgment you sign for.",
  },
};
