/* Data & Analytics — Judgment Gym lane. The AI drafts the analysis; you sign off
   only what holds. Three reps across the analyst's real deliverables: a dashboard,
   a SQL pull, and an experiment readout — each seeded with buried, checkable errors
   and genuinely sound work to leave alone. Same shape as every other lane (see
   lib/gym.ts). All items tagged mode + failure pattern. */

import type { Scenario } from "@/lib/gym";

export const DATA_SCENARIOS: Record<string, Scenario> = {
  "data-dashboard": {
    slug: "data-dashboard", career: "Data & Analytics", kind: "spreadsheet",
    short: "Sign off an AI-built exec growth dashboard — the metrics, the denominators, and the data freshness.",
    client: "Lumina Retail — Q3 growth dashboard",
    artifact: "Lumina_Q3_Dashboard.xlsx",
    aiDid: "The AI built the dashboard from the warehouse tables — metrics tiled, charts drawn, a commentary line on each. It looks clean and the numbers read as plausible. Sign off only the tiles that hold.",
    role: "You present this — the exec team sets Q4 targets off the numbers you sign.",
    thesis: "The AI built the Q3 growth dashboard — active users, conversion, revenue, all charted with a confident line under each. A dashboard that looks clean can still count the wrong thing. Sign off only the tiles that hold.",
    brief: [
      { l: "Task", v: "Review the Q3 dashboard before it goes to the exec team" },
      { l: "Data", v: "Orders, sessions and users across web, iOS and Android" },
      { l: "Watch", v: "The headline metrics, the denominators, and the data freshness" },
      { l: "Rule", v: "Every metric ties to the warehouse and counts each user once" },
    ],
    items: [
      { area: "Active users (total)", verdict: "flag", severity: "critical", mode: "fact", pattern: "miscalc",
        output: "Sums active users across web, iOS and Android → 412,000.",
        why: "A user on more than one platform is counted once per platform, so anyone who used the web and the app is double- or triple-counted. The deduplicated distinct-user count is materially lower — you can't sum per-platform totals to a user headline.",
        cost: "The top-line growth number the whole story rests on is inflated by cross-platform overlap; the exec team sets Q4 targets against a user base that doesn't exist.",
        trains: "Counting distinct users across sources, not summing per-platform totals into a headline." },
      { area: "Checkout conversion rate", verdict: "flag", severity: "major", mode: "fact", pattern: "miscalc",
        output: "Orders ÷ total registered users = 3.1%.",
        why: "Wrong denominator. Checkout conversion is orders per session (or per visitor who reached checkout), not per registered user — most of the user base never visited in Q3, so dividing by all of them measures something the label doesn't claim.",
        cost: "A conversion figure that doesn't mean what it says; funnel decisions get made against a rate whose denominator is the wrong population.",
        trains: "Checking the denominator matches the metric's definition, not just that the division runs." },
      { area: "Revenue commentary", verdict: "flag", severity: "major", mode: "judgment", pattern: "unverified",
        output: "“Revenue rose 18% after the loyalty program launched — the program drove the quarter.”",
        why: "Correlation asserted as cause. Revenue rose in the same window as the launch, but a price change, seasonality and higher paid spend all moved too, and there's no holdout. The AI wrote the tidy story and closed the point.",
        cost: "The exec team pours Q4 budget into loyalty crediting it for a lift it may not have caused — while the real driver goes unmanaged.",
        trains: "Separating what happened alongside a change from what the change actually caused." },
      { area: "Data freshness", verdict: "flag", severity: "critical", mode: "fact", pattern: "stale",
        output: "Header reads “Live — as of today”; the underlying tables last refreshed 16 days ago after the nightly ETL job failed silently.",
        why: "The dashboard presents a stale snapshot as live. A failed refresh means the “current” tiles are over two weeks old — plausible, because the numbers were true once. The label is the trap.",
        cost: "The exec team makes Q4 calls on numbers they believe are current; a demand spike or drop-off in the last two weeks is simply invisible to them.",
        trains: "Verifying the last-refresh timestamp before trusting a “live” label on a dashboard." },
      { area: "Cohort retention chart", verdict: "ship", mode: "judgment",
        output: "Monthly cohorts tracked by signup month, showing the percent still active at M1, M3 and M6.",
        why: "Sound. Cohorting by signup month and following each cohort's survival is the honest way to read retention — no blended average hiding the decay. Nothing to fix.",
        cost: "Rebuilding a correct cohort view wastes time and strips out the one genuinely trustworthy trend on the page.",
        trains: "Recognizing a methodologically sound cohort analysis and letting it stand." },
      { area: "Revenue YoY", verdict: "ship", mode: "fact",
        output: "Q3 revenue $8.4m vs Q3 last year $7.1m = +18.3%, on a like-for-like basis excluding the divested product line.",
        why: "Correct and honest. The growth is computed like-for-like, stripping out the divested line so the comparison is apples-to-apples — the arithmetic and the basis both hold.",
        cost: "Querying a correctly normalized YoY just delays the pack and second-guesses the one clean comparison on it.",
        trains: "Confirming a like-for-like comparison is genuinely comparable, then moving on." },
    ],
    lesson: "The double-counted active users and the stale “live” data were the two that would have been yours to answer for. The exec team acts on the number you sign — and a metric that looks clean can still count the wrong thing, off the wrong base, from the wrong day.",
  },

  "data-query": {
    slug: "data-query", career: "Data & Analytics", kind: "code",
    aiDid: "An AI wrote this SQL pull request to power the finance team's monthly revenue-by-customer report. It runs, returns rows, and the totals look reasonable. Some of the query is subtly wrong. Approve only the logic that should merge.",
    short: "Review an AI-written SQL query against the spec — the joins, the counts, and the filters that decide what's counted.",
    client: "Cobalt Commerce — “revenue by customer” reporting query",
    artifact: "revenue_by_customer.sql",
    thesis: "The AI opened a PR with the query behind the monthly revenue report — it runs and the output reads right. A query that returns rows can still count the wrong thing. Approve only the logic that holds.",
    brief: [
      { l: "Ticket", v: "Monthly revenue and order count per customer" },
      { l: "Schema", v: "customers 1→* orders 1→* order_items; orders has a status column" },
      { l: "Rule", v: "Completed orders only; revenue net of refunds" },
      { l: "Bar", v: "Each customer counted once; totals tie to the finance ledger" },
    ],
    items: [
      { area: "Revenue sum", verdict: "flag", severity: "critical", mode: "fact", pattern: "miscalc",
        output: "`SUM(o.order_total)` computed after `JOIN order_items i ON i.order_id = o.id`.",
        why: "Join fan-out. Joining to order_items multiplies each order row by its number of line items, so `SUM(o.order_total)` adds the order total once per line — a three-item order is counted three times. The item join isn't even needed for an order-level sum.",
        cost: "Revenue overstated by a multiple that varies per customer with basket size — the report ties to nothing and the finance number is silently inflated.",
        trains: "Spotting the fan-out a one-to-many join creates before summing a parent-level column through it." },
      { area: "Order count", verdict: "flag", severity: "major", mode: "fact", pattern: "miscalc",
        output: "`COUNT(*) AS order_count`",
        why: "Counts rows, not orders. Over the item-joined set, `COUNT(*)` returns line-item rows; even without the fan-out it isn't distinct orders. It should be `COUNT(DISTINCT o.id)`.",
        cost: "Every customer's order count is inflated by their line-item volume — a per-customer metric the team segments on that's simply wrong.",
        trains: "Counting the distinct entity you actually mean, not the rows a join happens to produce." },
      { area: "Status filter", verdict: "flag", severity: "major", mode: "fact", pattern: "omission",
        output: "No `WHERE` clause on status — cancelled and refunded orders are summed into the totals.",
        why: "The ticket says completed orders only, net of refunds. With no `WHERE o.status = 'completed'`, cancelled and refunded orders count as revenue. The filter that defines the population is missing.",
        cost: "The top line includes money that was never collected or was already returned; the report overstates revenue and won't reconcile to the ledger.",
        trains: "Checking that the filter defining what counts is actually present, not assuming the default row set is right." },
      { area: "Reporting period", verdict: "flag", severity: "minor", mode: "fact", pattern: "stale",
        output: "`WHERE o.created_at >= '2024-01-01' AND o.created_at < '2024-02-01'` — a hard-coded January-2024 window.",
        why: "The month is hard-coded to a stale date rather than parameterized to the reporting month. It runs cleanly, but it quietly reports the same old month every time until someone notices.",
        cost: "A monthly report that silently serves a fixed, stale period — the finance team reconciles this month's business against last year's January.",
        trains: "Catching the hard-coded date sitting where a parameter belongs." },
      { area: "Customer scope", verdict: "ship", mode: "fact",
        output: "`customers c LEFT JOIN orders o` with `COALESCE(SUM(...), 0)` so zero-order customers still appear with revenue 0.",
        why: "Correct. A LEFT JOIN keeps customers who didn't order this month in the report, and COALESCE floors their revenue at 0 — exactly right when the ask is per-customer across all customers.",
        cost: "Switching to an INNER JOIN would silently drop every customer who didn't buy this month — the churned accounts the finance team most wants to see.",
        trains: "Recognizing the correct join and null handling for an all-customers report." },
      { area: "Refund netting", verdict: "ship", mode: "fact",
        output: "Refunds are pre-aggregated per order in a CTE, then subtracted: `gross_total - COALESCE(refunds.amount, 0)`.",
        why: "Right approach. Aggregating refunds in a CTE before joining means the refund rows don't themselves fan out the orders — net revenue done in a way that avoids the very bug that breaks the sum above.",
        cost: "Rewriting a correct, fan-out-safe netting wastes the author's time on the one part of the query that's carefully right.",
        trains: "Recognizing that pre-aggregating before a join is what keeps a second one-to-many relationship from inflating the total." },
    ],
    lesson: "The join fan-out on revenue and the missing status filter were the two that would have been yours to answer for. AI writes SQL that runs and returns plausible rows in seconds — but a query that returns numbers can still count the wrong thing, and the finance team ties the ledger to what you merge.",
  },

  "data-experiment": {
    slug: "data-experiment", career: "Data & Analytics", kind: "memo",
    aiDid: "The AI wrote the readout for a pricing A/B test — the analysis, the chart, and a confident recommendation to roll variant B out to everyone. It reads like a clean win. Some of the analysis doesn't support the claim. Sign off only what the data holds.",
    short: "Sign off an AI-written A/B test readout before rollout — the significance claim, the chart, and cause versus coincidence.",
    client: "Northwind SaaS — checkout pricing A/B test",
    artifact: "Pricing_Test_Readout.md",
    role: "You approve the rollout — the whole customer base gets the version you sign off.",
    thesis: "The AI wrote the readout for a pricing experiment — a result, a chart, a recommendation to ship variant B. A confident readout can still be a false positive. Sign off only what the data actually supports.",
    brief: [
      { l: "Test", v: "Variant B (new pricing page) vs control, two-week run" },
      { l: "Primary metric", v: "Pre-registered as checkout conversion" },
      { l: "Watch", v: "The significance claim, the chart, and the causal language" },
      { l: "Rule", v: "Call a win only on the primary metric, properly tested" },
    ],
    items: [
      { area: "Significance claim", verdict: "flag", severity: "critical", mode: "judgment", pattern: "overreach",
        output: "“B wins: of the 14 metrics we looked at, trial-to-paid is significant at p = 0.04.”",
        why: "P-hacking. Testing 14 metrics and reporting the one that cleared p < 0.05 ignores multiple comparisons — with that many looks, a false positive is expected by chance. And the pre-registered primary metric, checkout conversion, isn't the one that “won.”",
        cost: "A pricing change rolled to the whole base on a spurious result; the effect doesn't replicate and revenue can move the wrong way, with the readout on record as the basis.",
        trains: "Holding the result to the pre-registered primary metric and correcting for multiple comparisons, not celebrating whichever metric happened to clear." },
      { area: "Conversion chart", verdict: "flag", severity: "minor", mode: "judgment", pattern: "fabrication",
        output: "Bar chart of the headline lift with a y-axis running from 11.8% to 12.4%, so a 0.3-point difference fills the panel.",
        why: "Truncated axis. Starting the baseline at 11.8% instead of 0 turns a 0.3-point difference into a bar that looks like a landslide. The data is real; the picture overstates it.",
        cost: "A reader who trusts the chart over the effect size sees a dramatic win the numbers don't contain, and approves on the visual.",
        trains: "Reading the axis before the bars — a truncated baseline is the most common honest-looking distortion." },
      { area: "Feature-usage claim", verdict: "flag", severity: "major", mode: "judgment", pattern: "unverified",
        output: "“Users who viewed the new pricing FAQ converted 2x — the FAQ drives conversion, so we should promote it.”",
        why: "Correlation read as cause, with selection bias. Users who sought out the FAQ were already high-intent — the intent drove the conversion, not necessarily the FAQ. It's an observational cut inside the test, not a randomized comparison.",
        cost: "The team invests in pushing the FAQ expecting a 2x lift that won't materialize, because the causal arrow points the other way.",
        trains: "Distinguishing a self-selected segment from a randomized effect before claiming one thing caused another." },
      { area: "Run window", verdict: "flag", severity: "major", mode: "judgment", pattern: "omission",
        output: "The two-week test ran across a site-wide promotion; the readout never mentions it.",
        why: "An undisclosed confound. A promo period distorts buying behavior in both arms, so the result may not hold in a normal fortnight — and the reader can't weigh that because it isn't on the page.",
        cost: "A result generalized to normal conditions when it was measured under a sale; the rollout underperforms the readout and no one knows why.",
        trains: "Surfacing the conditions a test ran under, so the reader can judge whether the result generalizes." },
      { area: "Sample size & stopping rule", verdict: "ship", mode: "judgment",
        output: "Sample size was fixed up front from a power calculation, and the test stopped at the planned n rather than when the result looked good.",
        why: "Sound. Setting the sample size in advance and not peeking-and-stopping is exactly what keeps the false-positive rate honest — the disciplined part of the design.",
        cost: "Second-guessing a properly powered, pre-committed stop undermines the one rigorous thing the test did right.",
        trains: "Recognizing disciplined experiment design and letting it stand." },
      { area: "Guardrail metrics", verdict: "ship", mode: "fact",
        output: "Reports refund rate and support-ticket volume as unchanged, with confidence intervals, alongside the primary metric.",
        why: "Right. Checking guardrail metrics — that the change didn't quietly raise refunds or support load — and reporting them with intervals is honest, complete analysis.",
        cost: "Cutting the guardrail check to tighten the readout removes the evidence that the change did no harm elsewhere.",
        trains: "Valuing the guardrail metrics that confirm a win didn't cost something on another line." },
    ],
    lesson: "The p-hacked “significant” metric and the FAQ that “drives” conversion were the two that would have been yours to answer for. AI writes a confident readout in seconds — but a false positive shipped to the whole base is a real revenue call, and catching it before rollout is the judgment you're paid for.",
  },
};
