/* Education & Training — a Judgment Gym lane. The AI drafts the teaching
   artifact; you sign off only what holds against the standard, the level, and
   the rubric. Same shape as every other lane (see lib/gym.ts). All items tagged
   mode + failure pattern. US standards, grade levels and conventions throughout. */

import type { Scenario } from "@/lib/gym";

export const EDU_SCENARIOS: Record<string, Scenario> = {
  "edu-lesson-plan": {
    slug: "edu-lesson-plan", career: "Education & Training", kind: "document",
    short: "Sign off an AI-drafted lesson plan against the standard — objective, content accuracy, reading level.",
    client: "Grade 8 science — photosynthesis lesson",
    artifact: "Photosynthesis_Lesson_Plan.docx",
    thesis: "The AI drafted a full lesson plan from the standard — objective, activities, a reading, a check for understanding. It reads polished and ready to teach. Some of it doesn't hold against the standard, the science, or the reading level. Teach only what's right.",
    role: "You're the teacher signing this off before you teach it Monday.",
    aiDid: "AI built the whole plan from the standard code and the textbook chapter — objective, materials, reading, and the exit ticket. It cites the standard and looks classroom-ready.",
    brief: [
      { l: "Standard", v: "NGSS MS-LS1-6 — construct an explanation for the role of photosynthesis in the cycling of matter and flow of energy" },
      { l: "Class", v: "Grade 8, mixed readers, four multilingual learners" },
      { l: "Reading band", v: "Grade 6–8 stretch text is roughly 925L–1185L (Lexile)" },
      { l: "Rule", v: "The lesson must meet the standard's level, and the science must be correct" },
    ],
    items: [
      { area: "Learning objective", verdict: "flag", severity: "major", mode: "judgment", pattern: "omission",
        output: "“Students will be able to identify and label the parts of a plant cell.”",
        why: "It doesn't meet the standard's level. MS-LS1-6 asks students to construct an explanation of energy and matter flow — an analysis task. Labeling cell parts is recall, a rung below what the standard requires. The plan claims alignment it doesn't deliver.",
        cost: "You teach and assess to a lower bar than the standard, and it surfaces on the state test — where the students are asked to explain, not label, and can't.",
        trains: "Reading an objective against the cognitive level the standard actually demands, not just the topic it names." },
      { area: "Content — the gas exchange", verdict: "flag", severity: "critical", mode: "fact", pattern: "fabrication",
        output: "“During photosynthesis, plants take in oxygen and release carbon dioxide, which is how they make food.”",
        why: "Reversed, and it's the core science of the lesson. In photosynthesis plants take in carbon dioxide and release oxygen — the AI flipped the gases and stated it with total confidence as the key fact.",
        cost: "The central misconception gets taught as fact to a whole class, then has to be un-taught after it's already anchored — one of the hardest things to undo in science instruction.",
        trains: "Fact-checking the one sentence the whole lesson rests on, not trusting a fluent explanation." },
      { area: "Assigned reading", verdict: "flag", severity: "major", mode: "judgment", pattern: "omission",
        output: "A 1,310L journal-style article on the Calvin cycle, assigned to the whole class with no scaffold or alternate.",
        why: "Well above the grade band and inaccessible as set. At 1,310L it sits above even the grade 6–8 stretch ceiling, and there's no scaffold, glossary, or leveled alternate for the multilingual learners. The text is there; access to it isn't.",
        cost: "Most of the class — and every multilingual learner — can't actually read the source the lesson is built on, so the activity fails for the students who need it most.",
        trains: "Judging whether a resource is reachable at this level, and catching the missing accommodation." },
      { area: "Hands-on model activity", verdict: "ship", mode: "judgment",
        output: "Students build a labeled model tracing carbon and energy from sunlight through a plant, then write a short explanation of the flow.",
        why: "Sound and on-standard. Constructing a model and explaining the flow of matter and energy is exactly the analysis task MS-LS1-6 calls for — the activity meets the standard's level.",
        cost: "Reworking an activity that already hits the standard wastes prep time and cuts the best part of the lesson.",
        trains: "Recognizing an activity that matches the standard's level and letting it stand." },
      { area: "Multilingual scaffold", verdict: "ship", mode: "judgment",
        output: "Provides a labeled diagram, a sentence frame for the explanation, and a key-term glossary in the students' home languages.",
        why: "Good UDL practice. Sentence frames, a visual, and a home-language glossary give the multilingual learners access to the same task without lowering the bar — appropriate and well-judged.",
        cost: "Stripping a well-built scaffold pushes the very students it supports back out of the lesson.",
        trains: "Valuing genuine access supports and leaving them in." },
      { area: "Standard reference", verdict: "flag", severity: "minor", mode: "fact", pattern: "stale",
        output: "Header cites the district's 2011 science framework code “S8.B.2.1” as the alignment.",
        why: "A stale reference. The district moved to NGSS years ago and the 2011 framework codes are retired — the plan is tagged to a standard that no longer governs. Plausible, because that code was correct once.",
        cost: "The plan looks aligned in the planning system but maps to a dead standard, so coverage and pacing reports against the current curriculum are quietly wrong.",
        trains: "Checking that a cited standard code is the one currently adopted, not a superseded edition." },
    ],
    lesson: "The reversed gas exchange and the recall-level objective were the two that would have been yours to answer for. The AI plans a polished lesson in seconds — but you're the one standing in front of the class teaching it, and a confident wrong fact is the hardest thing to walk back.",
  },

  "edu-quiz-key": {
    slug: "edu-quiz-key", career: "Education & Training", kind: "document",
    short: "Sign off an AI-written quiz and answer key before it reaches students — the key, ambiguous items, the point total.",
    client: "Algebra I — Unit 4 quiz (linear equations)",
    artifact: "Algebra1_Unit4_Quiz_Key.docx",
    thesis: "The AI wrote the unit quiz and the answer key — items, distractors, and the solutions all laid out. A clean-looking key is where a wrong answer hides in plain sight. Sign off only the items and answers that hold.",
    role: "You're the teacher signing this off before it goes to students and gets graded against this key.",
    aiDid: "AI generated the eight quiz items, the multiple-choice distractors, and the full answer key from the unit objectives. It looks complete and correctly worked.",
    brief: [
      { l: "Unit", v: "Grade 9 Algebra I — solving and graphing linear equations" },
      { l: "Objective", v: "Solve one- and two-step equations; interpret slope" },
      { l: "Header", v: "Quiz is marked out of 25 points" },
      { l: "Rule", v: "Every keyed answer must be correct and every item must have one defensible answer" },
    ],
    items: [
      { area: "Answer key — Item 3", verdict: "flag", severity: "critical", mode: "fact", pattern: "miscalc",
        output: "“Solve 3x + 7 = 22.”  Key: x = 6.",
        why: "The key is wrong. 3x + 7 = 22 gives 3x = 15, so x = 5, not 6. The item is fine — the answer the whole class will be graded against is mis-worked.",
        cost: "Every student who solves it correctly is marked wrong, and the one who wrote 6 is marked right — a graded injustice that erodes trust the moment a parent re-works it.",
        trains: "Re-solving each keyed answer yourself, never trusting the machine's arithmetic on the key." },
      { area: "Item 5 — multiple choice", verdict: "flag", severity: "major", mode: "fact", pattern: "fabrication",
        output: "“Which value is a solution to x + 4 = 10?”  Options: (A) 6  (B) 14  (C) −6  (D) 6.0. Key: A.",
        why: "Two options are correct. Both (A) 6 and (D) 6.0 are the same value and both satisfy the equation, so the item has no single defensible answer — a mis-keyed, ambiguous question.",
        cost: "Students who pick (D) are marked wrong for a correct answer, and the appeal is unwinnable because the item itself is broken. It has to be thrown out after the fact.",
        trains: "Reading every distractor for the second right answer, not just confirming the keyed one works." },
      { area: "Item 6 — stated fact", verdict: "flag", severity: "major", mode: "fact", pattern: "fabrication",
        output: "Stem reads: “Recall that the slope of a horizontal line is undefined. What is the slope of y = 3?” Key: undefined.",
        why: "The stem states the concept backwards. A horizontal line has a slope of 0; a vertical line has an undefined slope. The item teaches the misconception in the question itself, and the key repeats it.",
        cost: "The quiz reinforces the exact confusion students already have between horizontal and vertical slope — assessed as if the wrong version were correct.",
        trains: "Catching the false premise embedded in a question stem before it's taught as fact." },
      { area: "Point total", verdict: "flag", severity: "minor", mode: "fact", pattern: "miscalc",
        output: "Header says 25 points; the eight items are worth 4, 3, 4, 3, 4, 3, 3, 3 — summing to 27.",
        why: "The items don't foot to the stated total. They sum to 27, not the 25 in the header, so every percentage grade off this quiz is computed against the wrong denominator.",
        cost: "Every score is off by the same skew, and it only surfaces when a student adds the points up — after grades are already in the book.",
        trains: "Adding the item points against the stated total before the quiz is scored." },
      { area: "Item 2 — two-step equation", verdict: "ship", mode: "fact",
        output: "“Solve 5x − 3 = 12.”  Key: x = 3.",
        why: "Correct and on-objective. 5x − 3 = 12 gives 5x = 15, x = 3 — a clean two-step equation, right at the unit's level, keyed correctly.",
        cost: "Re-working an item that's already right wastes review time on the part that holds.",
        trains: "Confirming a correctly-keyed, well-targeted item and moving on." },
      { area: "Item 7 — distractors", verdict: "ship", mode: "judgment",
        output: "A slope-from-two-points item whose wrong options each match a specific common error (inverted rise/run, dropped sign).",
        why: "Well built. Distractors that map to real, predictable student errors turn the item into diagnostic information, not just a right-or-wrong — good assessment design.",
        cost: "Replacing purposeful distractors with random ones throws away what the item can tell you about how students are thinking.",
        trains: "Recognizing distractors that diagnose the misconception and leaving them." },
    ],
    lesson: "The mis-worked key on Item 3 and the two-correct-answers item were the two that would have been yours to answer for. The AI writes a tidy quiz in seconds — but students are graded against the key you sign, and a wrong answer marked right is a fairness problem, not a typo.",
  },

  "edu-feedback": {
    slug: "edu-feedback", career: "Education & Training", kind: "memo",
    short: "Sign off AI-generated learner feedback against the rubric — the scores, the corrections, and whether it's specific.",
    client: "Sales Onboarding Cohort — customer-email exercise",
    artifact: "Cohort_Feedback_Batch.docx",
    thesis: "The AI graded the cohort's written exercise and drafted feedback for each trainee against the competency rubric. It's fast, warm, and ready to send. Some of it doesn't match the rubric, corrects the trainee with something wrong, or says nothing useful. Send only the feedback that holds.",
    role: "You're the trainer signing this off before it reaches the cohort.",
    aiDid: "AI scored each submission on the four-criterion rubric and wrote the individual feedback and next steps. It reads supportive and specific, and the scores are already totaled.",
    brief: [
      { l: "Exercise", v: "Draft a customer email resolving a delayed-order complaint" },
      { l: "Rubric", v: "Four criteria — Accuracy, Tone, Completeness, Clarity — each scored 1–4, level 4 = “Exceeds”" },
      { l: "Policy fact", v: "Standard resolution offer is a 15% credit; refunds require a manager" },
      { l: "Rule", v: "Scores must match the rubric descriptors, and every comment must be tied to a criterion" },
    ],
    items: [
      { area: "Overall comment", verdict: "flag", severity: "major", mode: "judgment", pattern: "unverified",
        output: "“Great work overall — really strong effort here, keep it up! You're clearly getting the hang of this.”",
        why: "Generic praise tied to nothing. It names no criterion, cites no line from the submission, and gives the trainee no idea what to do differently. Feedback that isn't anchored to the rubric doesn't move performance — it just fills the box.",
        cost: "The trainee reads it, feels fine, and changes nothing — the whole point of the exercise is lost, and it looks like coaching happened when it didn't.",
        trains: "Refusing to let warm, generic praise stand in for rubric-anchored, actionable feedback." },
      { area: "Accuracy score", verdict: "flag", severity: "critical", mode: "fact", pattern: "fabrication",
        output: "Accuracy: 4 — “Exceeds. Offered the customer a full refund to resolve the issue.”",
        why: "The score doesn't match the rubric, and it rewards a policy breach. A full refund requires a manager — the standard offer is a 15% credit — so the submission actually got the policy wrong. That can't be a “4 — Exceeds” on Accuracy; the AI scored the mistake as excellence.",
        cost: "The trainee is told an out-of-policy refund is exemplary and does it again on a real customer, and the inflated score misreports who's actually ready.",
        trains: "Checking the score against the rubric descriptors and the facts, not accepting a confident top mark." },
      { area: "Correction on escalation", verdict: "flag", severity: "major", mode: "fact", pattern: "fabrication",
        output: "“One fix: you shouldn't have escalated to a manager for the refund — reps can approve refunds directly, so handle it yourself next time.”",
        why: "The feedback corrects a correct instinct with a wrong rule. Reps can't approve refunds — that's exactly what needs a manager — so the AI is coaching the trainee toward the policy breach, confidently.",
        cost: "A trainee who did the right thing is told it was wrong and taught to bypass the control — the correction actively trains the mistake.",
        trains: "Verifying the correction itself is right before it's sent — a wrong fix is worse than no fix." },
      { area: "Score total", verdict: "flag", severity: "minor", mode: "fact", pattern: "miscalc",
        output: "Criterion scores of 3, 3, 2, 2 are reported as an overall 12 / 16 (75%).",
        why: "The total doesn't add up. 3 + 3 + 2 + 2 is 10 of 16, not 12 — the overall is two points high and the percentage with it. A small slip on the number that goes in the record.",
        cost: "The recorded competency score is inflated for this trainee, and the same total logic is applied across the whole cohort's records.",
        trains: "Re-adding the criterion scores against the reported total before it's logged." },
      { area: "Tone feedback", verdict: "ship", mode: "judgment",
        output: "Tone: 3 — “You opened with a genuine apology and named the delay directly, which builds trust. To reach a 4, add a specific reassurance about the new delivery date.”",
        why: "Exactly right. It names the criterion, quotes what the trainee did, and gives a concrete next step keyed to the level-4 descriptor — specific, honest, and actionable.",
        cost: "Rewriting feedback this good removes the model for what the rest of the batch should look like.",
        trains: "Recognizing rubric-anchored, actionable feedback and letting it stand." },
      { area: "Completeness score", verdict: "ship", mode: "fact",
        output: "Completeness: 2 — “The email resolves the complaint but never states the new delivery date, which the rubric requires for a 3.”",
        why: "Matches the rubric. The submission does omit the delivery date, the level-3 descriptor requires it, so a 2 is the correct, defensible score — tied directly to the descriptor.",
        cost: "Second-guessing a score that matches the rubric just delays sending the batch back.",
        trains: "Confirming a score that ties to the descriptor and moving on." },
    ],
    lesson: "The refund scored as “Exceeds” and the correction that taught the policy breach were the two that would have been yours to answer for. The AI grades a whole cohort in minutes — but the feedback goes out under your name, and a wrong correction trains the mistake faster than no feedback at all.",
  },
};
