/* Consulting & Strategy and Project & Program Management — Judgment Gym lanes.
   The AI drafts the deliverable; you sign off only what holds. Same shape as
   every other lane (see lib/gym.ts). All items tagged mode + failure pattern. */

import type { Scenario } from "@/lib/gym";

export const ADVISORY_SCENARIOS: Record<string, Scenario> = {
  "consult-market-sizing": {
    slug: "consult-market-sizing", career: "Consulting & Strategy", kind: "spreadsheet",
    short: "Sign off an AI-built market sizing for a client's new-market entry — assumptions, footing, sources.",
    client: "Helix Health — market-entry sizing",
    artifact: "Helix_TAM_Model.xlsx",
    thesis: "The AI built the market sizing for a new-market entry — TAM, SAM, SOM, a growth case. A sizing is only as good as its assumptions. Sign off only the numbers that hold.",
    brief: [
      { l: "Task", v: "Size the addressable market for a new product" },
      { l: "Approach", v: "Top-down: TAM → SAM → SOM" },
      { l: "Watch", v: "The assumptions, the sources, and the arithmetic" },
      { l: "Rule", v: "Every number foots and cites a current source" },
    ],
    items: [
      { area: "TAM basis", verdict: "flag", severity: "major", mode: "fact", pattern: "stale",
        output: "TAM = $12.0bn, per a 2019 industry report.",
        why: "The source is five years stale. A 2019 figure anchors the entire model to a market that has moved — a current basis could be materially different in either direction.",
        cost: "Every number below inherits an out-of-date anchor; the client builds an entry case on a market that no longer looks like this.",
        trains: "Checking the age and currency of the source under a headline number, not just that a number is cited." },
      { area: "SAM calculation", verdict: "flag", severity: "critical", mode: "fact", pattern: "miscalc",
        output: "SAM = 60% of TAM = $7.8bn.",
        why: "The arithmetic is wrong. 60% of $12.0bn is $7.2bn, not $7.8bn — a slip on the figure the whole opportunity narrows to.",
        cost: "The serviceable market is overstated by $600m, and the share and revenue cases stack on top of the error.",
        trains: "Re-performing the figure that anchors the opportunity, not trusting the printed calc." },
      { area: "Year-1 share (SOM)", verdict: "flag", severity: "major", mode: "judgment", pattern: "unverified",
        output: "SOM assumes a 15% market share in year one.",
        why: "Aggressive and unsupported. A new entrant taking 15% in year one is extraordinary — there's no comparable or basis given. It's the assumption that makes the model look good.",
        cost: "A revenue plan built on a share almost no new entrant achieves — the gap surfaces as a miss the moment the client acts on it.",
        trains: "Anchoring the key assumption to what new entrants actually achieve, not the number that makes the case." },
      { area: "Segmentation", verdict: "ship", mode: "judgment",
        output: "Market split by hospital size, aligned to the client's sales motion.",
        why: "Sound. A segmentation that maps to how the client actually sells makes the sizing usable — a defensible cut.",
        cost: "Re-cutting a segmentation that already fits the go-to-market just delays the work.",
        trains: "Recognising a segmentation that fits the decision and letting it stand." },
      { area: "Growth rate", verdict: "flag", severity: "major", mode: "fact", pattern: "fabrication",
        output: "Applies a 25% CAGR, “consistent with the sector.”",
        why: "Asserted, not evidenced. “Consistent with the sector” with no source, and 25% is high for this market — a confident number with nothing behind it.",
        cost: "The out-year case is inflated by a growth rate nobody can defend in the room — the first thing a sharp client challenges.",
        trains: "Demanding the source under a growth rate, not accepting a plausible-sounding figure." },
      { area: "Units & currency", verdict: "ship", mode: "fact",
        output: "All figures in USD millions, labelled and consistent throughout.",
        why: "Clean. Consistent units and currency across the model — no mixing, correctly labelled.",
        cost: "Querying consistent, well-labelled units wastes review time on the part that's right.",
        trains: "Confirming unit consistency and moving on." },
    ],
    lesson: "The stale TAM and the 15% year-one share were the two that would have been yours to answer for. A sizing sells the whole entry case — and the client builds a plan on the number you sign.",
  },

  "consult-reco": {
    slug: "consult-reco", career: "Consulting & Strategy", kind: "document",
    short: "Sign off an AI-drafted client recommendation memo — the number, the logic, the promise.",
    client: "Orion Retail — cost-reduction recommendation",
    artifact: "Orion_Reco_Memo.docx",
    thesis: "The AI drafted the recommendation memo to the client — findings, the number, the ask. The client will act on this. Sign off only what the analysis supports.",
    brief: [
      { l: "Engagement", v: "Cost-reduction review for a retail chain" },
      { l: "Diagnostic finding", v: "The waste was in process, not headcount" },
      { l: "Watch", v: "The headline number, the benchmark, and whether the reco follows the analysis" },
      { l: "Your seat", v: "You sign this to the client — the recommendation is yours" },
    ],
    items: [
      { area: "Headline saving", verdict: "flag", severity: "critical", mode: "judgment", pattern: "overreach",
        output: "“$4.2m in annual savings, guaranteed.”",
        why: "You never guarantee a saving. Delivery depends on the client executing — a guarantee is an over-promise, and the $4.2m isn't reconciled to the findings either.",
        cost: "A written guarantee is a liability the moment the client under-delivers on their side — and a number that doesn't tie is the first thing their CFO checks.",
        trains: "Catching the over-promise a helpful draft makes — commit to a range and a basis, never a guarantee." },
      { area: "Benchmark used", verdict: "flag", severity: "major", mode: "fact", pattern: "unverified",
        output: "Benchmarked against a “best-in-class peer,” with no peer or source named.",
        why: "An unsourced comparison. “Best-in-class” with no named peer or data behind it isn't a benchmark — it's a claim, and the client's team will ask exactly who.",
        cost: "The whole savings case leans on a comparison you can't produce when challenged — credibility gone in one question.",
        trains: "Requiring the named source behind a benchmark before it anchors a recommendation." },
      { area: "The recommendation", verdict: "flag", severity: "major", mode: "judgment", pattern: "fabrication",
        output: "Recommends a 12% headcount reduction.",
        why: "The reco doesn't follow the analysis. The diagnostic found the waste in process, not headcount — jumping to layoffs is a conclusion the evidence doesn't support.",
        cost: "The client cuts people to fix a process problem, the costs come back, and the engagement's credibility goes with it.",
        trains: "Checking that the recommendation actually follows from the diagnosis, not from a default playbook." },
      { area: "Risk section", verdict: "ship", mode: "judgment",
        output: "Names the delivery risks and the change-management load honestly.",
        why: "Sound and mature. A memo that names what could go wrong is more credible, not less — exactly what a serious client wants to see.",
        cost: "Softening an honest risk section to look more confident is how you lose the client's trust later.",
        trains: "Valuing a memo that's honest about its own risks." },
      { area: "Implementation timeline", verdict: "flag", severity: "minor", mode: "fact", pattern: "miscalc",
        output: "“Phases 1–3 delivered over 6 months.” The phases listed run 3 + 3 + 2.",
        why: "Doesn't add up. The three phases sum to eight months, not the six the memo headlines. A small slip, but it's the timeline the client plans around.",
        cost: "The client commits to a six-month plan that the phases can't hit — a credibility ding at the first review.",
        trains: "Re-adding the phase durations against the headline timeline." },
      { area: "Executive summary", verdict: "ship", mode: "judgment",
        output: "Leads with the recommendation and the number on one page.",
        why: "Right structure. The decision-maker gets the ask and the number first — a clear, well-ordered summary.",
        cost: "Reworking a clear summary just delays the memo.",
        trains: "Recognising a summary that leads with the decision and letting it stand." },
    ],
    lesson: "The guaranteed saving and the reco that didn't follow the analysis were the two that would have been yours to answer for. The client acts on the memo you sign — and a promise in writing is a liability.",
  },

  "consult-diligence": {
    slug: "consult-diligence", career: "Consulting & Strategy", kind: "document",
    short: "Sign off an AI-drafted commercial due-diligence memo on an acquisition target — the risks it names, and the ones it doesn't.",
    client: "Vantage Capital — target due diligence",
    artifact: "Vantage_CDD_Findings.docx",
    thesis: "The AI drafted the commercial due-diligence findings on an acquisition target. A fund will invest on this. Sign off only what the evidence supports — and catch what's missing.",
    brief: [
      { l: "Deal", v: "Commercial due diligence on an acquisition target" },
      { l: "Reader", v: "The investment committee decides off this" },
      { l: "Watch", v: "Revenue quality, concentration, and the synergy case" },
      { l: "Rule", v: "Claims need evidence; material risks must be surfaced" },
    ],
    items: [
      { area: "Revenue quality", verdict: "flag", severity: "critical", mode: "judgment", pattern: "unverified",
        output: "Accepts management's revenue forecast at face value.",
        why: "The core failure of weak diligence. A forecast from the seller is a starting point to test, not a finding — no pipeline corroboration, no cohort analysis, nothing behind it.",
        cost: "The fund pays a multiple on revenue that may not materialise — the single most expensive diligence miss there is.",
        trains: "Testing management's numbers against independent evidence, never accepting the seller's case as the finding." },
      { area: "Customer concentration", verdict: "flag", severity: "critical", mode: "fact", pattern: "omission",
        output: "Describes a “diversified customer base.”",
        why: "A material omission. One client is 40% of revenue — that isn't diversified, and it's the risk that most changes the valuation. The memo leaves it off the page.",
        cost: "The committee invests believing the revenue is spread; lose that one client post-deal and the thesis collapses.",
        trains: "Catching the concentration the summary language hides — the risk that isn't stated is the dangerous one." },
      { area: "Synergy case", verdict: "flag", severity: "major", mode: "judgment", pattern: "overreach",
        output: "Assumes full synergy capture in year one.",
        why: "Over-optimistic. Synergies lag — integration friction, attrition, systems — and full year-one capture is a number that flatters the return, not one that happens.",
        cost: "The return model overstates year-one value; the fund's committee approves on a case that slips a year or more in reality.",
        trains: "Discounting a synergy case for the friction that always comes, not banking the best case." },
      { area: "Market growth", verdict: "ship", mode: "fact",
        output: "Cites a current, named market report for the sector growth rate.",
        why: "Sourced and current. A named, recent source for the growth assumption — the standard the rest of the memo should meet.",
        cost: "Re-checking a properly sourced figure wastes diligence time.",
        trains: "Recognising a well-evidenced number and moving on." },
      { area: "Churn read", verdict: "flag", severity: "minor", mode: "fact", pattern: "miscalc",
        output: "Reports “low churn of 8% monthly” as a strength.",
        why: "Misread. 8% monthly churn is very high — roughly 63% a year — and it's flagged as a strength. The label is the opposite of what the number means.",
        cost: "A retention problem gets recorded as a selling point; the committee misreads the quality of the revenue.",
        trains: "Translating a monthly rate to its annual reality before you call it good or bad." },
      { area: "Management assessment", verdict: "ship", mode: "judgment",
        output: "A balanced read on the leadership team — strengths and the gaps.",
        why: "Sound. An even-handed assessment that names both the capability and the gaps is exactly what the committee needs.",
        cost: "Second-guessing a fair management read just slows the memo.",
        trains: "Letting an honest, balanced assessment stand." },
    ],
    lesson: "The unquestioned forecast and the buried 40% customer were the two that would have been yours to answer for. The fund invests on the diligence you sign — and the risk it doesn't name is the one that bites.",
  },

  "pm-status": {
    slug: "pm-status", career: "Project & Program Management", kind: "document",
    short: "Sign off an AI-assembled weekly client status report — the RAG, the variances, the risks.",
    client: "Northwind Program — weekly client status",
    artifact: "Northwind_Status_Wk12.pptx",
    thesis: "The AI assembled this week's client status report — RAG set, variances explained, risks summarised. The client acts on the status you sign. Sign off only what's true.",
    brief: [
      { l: "Cadence", v: "Weekly client status, four workstreams" },
      { l: "This week", v: "Two workstreams amber; a milestone slipped" },
      { l: "Watch", v: "The overall RAG, the schedule variance, and the risks" },
      { l: "Your seat", v: "You sign the status that goes to the client sponsor" },
    ],
    items: [
      { area: "Overall RAG", verdict: "flag", severity: "critical", mode: "judgment", pattern: "fabrication",
        output: "Overall status: GREEN.",
        why: "Can't be green. Two workstreams are amber and a milestone slipped — an overall green paints over the very things the sponsor needs to see. RAG smoothing is the classic status failure.",
        cost: "The sponsor relaxes on a program that's drifting; by the time reality shows, the recovery window has closed.",
        trains: "Refusing to let an overall RAG read better than the parts underneath it." },
      { area: "Schedule variance", verdict: "flag", severity: "major", mode: "fact", pattern: "miscalc",
        output: "“2 days behind plan.”",
        why: "Understated. The milestone due Monday completed the following Friday — that's four working days, not two. The number is softer than the truth.",
        cost: "The client plans around a slip half its real size; the downstream dates are wrong from here on.",
        trains: "Counting the actual slip against the plan, not the comfortable version of it." },
      { area: "Budget line", verdict: "ship", mode: "fact",
        output: "Spend $1.2m of $1.5m (80%), against 78% delivery.",
        why: "Foots and reconciles. Spend tracks delivery closely — a clean, honest budget line.",
        cost: "Querying a budget line that ties just delays the report.",
        trains: "Confirming spend tracks progress and moving on." },
      { area: "Top risk", verdict: "flag", severity: "major", mode: "judgment", pattern: "unverified",
        output: "The top risk is marked “mitigated.”",
        why: "Asserted, not evidenced. “Mitigated” with no mitigation described or proven is a risk being wished away — exactly what a status report shouldn't do.",
        cost: "A live risk drops off the client's radar under a reassuring label, and resurfaces with no plan in place.",
        trains: "Requiring the evidence before a risk is called mitigated." },
      { area: "Dependencies", verdict: "flag", severity: "minor", mode: "fact", pattern: "omission",
        output: "No mention of the vendor dependency now blocking workstream 3.",
        why: "A missing item. A live external blocker isn't on the report — the omission hides the thing most likely to slip the plan further.",
        cost: "The client can't help clear a blocker they were never told about; WS3 stalls in silence.",
        trains: "Surfacing the live dependency, not just reporting the workstreams in isolation." },
      { area: "Next steps", verdict: "ship", mode: "judgment",
        output: "Clear owners and dates against each next action.",
        why: "Sound. Actions with named owners and dates — the part that makes a status report actionable.",
        cost: "Reworking clear, owned actions wastes report time.",
        trains: "Recognising actionable next steps and letting them stand." },
    ],
    lesson: "The green-when-it's-amber and the risk marked mitigated were the two that would have been yours to answer for. The client runs on the status you sign — smoothing it over is how a program fails quietly.",
  },

  "pm-plan": {
    slug: "pm-plan", career: "Project & Program Management", kind: "document",
    short: "Sign off an AI-built project plan — critical path, estimates, dependencies, resourcing.",
    client: "Atlas Rollout — project plan",
    artifact: "Atlas_Plan_v3.mpp",
    thesis: "The AI built the project plan — work breakdown, schedule, critical path, resources. Commit to the wrong date and the whole program inherits it. Sign off only what holds.",
    brief: [
      { l: "Project", v: "System rollout with a hard go-live date" },
      { l: "Watch", v: "The critical path, the estimates, and the dependencies" },
      { l: "Your seat", v: "The business commits to the dates you sign" },
      { l: "Rule", v: "Sequence and resourcing must be feasible" },
    ],
    items: [
      { area: "Critical path", verdict: "flag", severity: "critical", mode: "judgment", pattern: "fabrication",
        output: "Marks the design phase as the critical path.",
        why: "Wrong path. Testing has zero float against a hard go-live — that's the real critical path. Calling design critical points the whole team's attention at the wrong risk.",
        cost: "Slack gets managed on the wrong phase; testing runs into the go-live with no room, and the date is missed.",
        trains: "Finding the path with no float to a hard date, not the phase the tool happened to flag." },
      { area: "Build estimate", verdict: "flag", severity: "major", mode: "fact", pattern: "unverified",
        output: "Build phase estimated at 4 weeks, “per the tool.”",
        why: "No basis. “Per the tool” isn't an estimate — there's no reference to similar work, no bottom-up build, nothing to defend when it slips.",
        cost: "The plan commits to a date built on a guess; when build takes six weeks, everything after it moves.",
        trains: "Grounding an estimate in a real basis, not accepting a number the tool produced." },
      { area: "Sequencing", verdict: "flag", severity: "major", mode: "fact", pattern: "omission",
        output: "UAT is scheduled to start before the data migration it depends on.",
        why: "A broken dependency. You can't test on data that hasn't been migrated — the sequence is impossible as drawn.",
        cost: "UAT stalls on day one waiting for data, burning a testing window that was already tight.",
        trains: "Reading the plan for the dependency that's out of order, not just that every task has a date." },
      { area: "Contingency", verdict: "ship", mode: "judgment",
        output: "10% buffer on the high-risk workstream, none on the routine ones.",
        why: "Sensible. Risk-based contingency — buffer where the risk is, not spread evenly for show.",
        cost: "Stripping a well-placed buffer trades a small saving for real schedule risk.",
        trains: "Recognising risk-based contingency and leaving it." },
      { area: "Resource loading", verdict: "flag", severity: "minor", mode: "fact", pattern: "miscalc",
        output: "One lead is allocated across two workstreams at 140% for the same weeks.",
        why: "Over-allocated. Nobody delivers at 140% — the plan quietly assumes one person does more than a full load, and the tool didn't flag it.",
        cost: "The lead becomes the bottleneck those weeks; whatever they can't get to slips, and the plan didn't see it coming.",
        trains: "Checking that no one is loaded past 100% before you commit the plan." },
      { area: "Milestones", verdict: "ship", mode: "fact",
        output: "Milestones map to the contract's payment gates.",
        why: "Correct. Aligning milestones to the payment gates is exactly right — it ties delivery to the commercials.",
        cost: "Re-mapping milestones that already align just delays the baseline.",
        trains: "Confirming milestones tie to the contract and moving on." },
    ],
    lesson: "The wrong critical path and the UAT-before-migration were the two that would have been yours to answer for. The business commits to the dates you sign — and a hidden dependency surfaces at go-live.",
  },

  "pm-raid": {
    slug: "pm-raid", career: "Project & Program Management", kind: "spreadsheet",
    short: "Sign off an AI-updated RAID log — scoring, closed risks, ownership, classification.",
    client: "Meridian Program — RAID review",
    artifact: "Meridian_RAID_Log.xlsx",
    thesis: "The AI updated the program RAID log — risks scored, issues logged, actions tracked. A tidy log isn't a true one. Sign off only what's real.",
    brief: [
      { l: "Task", v: "Review the weekly RAID log before the steering pack" },
      { l: "Watch", v: "The scoring, anything marked closed, and the owners" },
      { l: "Rule", v: "Score on likelihood AND impact; closed means evidenced" },
      { l: "Your seat", v: "The steering committee acts on this log" },
    ],
    items: [
      { area: "Risk scoring", verdict: "flag", severity: "major", mode: "judgment", pattern: "miscalc",
        output: "A regulatory-deadline risk scored “Low” — “because likelihood is low.”",
        why: "Scored on one axis. Likelihood may be low, but the impact of missing a regulatory deadline is severe — a low score ignores half the equation and buries a serious risk.",
        cost: "A catastrophic-impact risk sits at the bottom of the log and gets no attention until it's an issue nobody prepared for.",
        trains: "Scoring on likelihood and impact together, never likelihood alone." },
      { area: "Closed risk", verdict: "flag", severity: "critical", mode: "judgment", pattern: "unverified",
        output: "The key integration risk is marked “Closed.”",
        why: "Closed without evidence. The integration hasn't been tested — a risk isn't closed because time passed, it's closed because it was resolved and proven.",
        cost: "The one risk most likely to sink the program drops off the log, and nobody's watching it when integration fails.",
        trains: "Requiring proof of resolution before a risk is closed." },
      { area: "Issue vs risk", verdict: "ship", mode: "judgment",
        output: "A risk that has now materialised is moved to the issues log.",
        why: "Right call. Once a risk happens it's an issue to manage, not a risk to watch — the log handled the transition correctly.",
        cost: "Second-guessing a correct reclassification just adds noise.",
        trains: "Recognising a sound risk-to-issue move and letting it stand." },
      { area: "Ownership", verdict: "flag", severity: "minor", mode: "fact", pattern: "omission",
        output: "Three high-rated risks have no named owner.",
        why: "Unowned. A risk with no owner is a risk nobody is actioning — the log records it but nothing happens.",
        cost: "High risks drift week to week because there's no one accountable to move them.",
        trains: "Checking every live risk has a named owner before the log goes to steering." },
      { area: "Dependency classification", verdict: "flag", severity: "major", mode: "fact", pattern: "fabrication",
        output: "A dependency on a third-party vendor is logged as “Internal — low.”",
        why: "Misclassified. A dependency outside your control isn't internal or low — it's exactly the kind you can't manage directly, so it needs the most visibility, not the least.",
        cost: "An external blocker is treated as something the team can fix, so it isn't escalated until it's already holding up delivery.",
        trains: "Classifying a dependency by who actually controls it, not how the draft labelled it." },
      { area: "Action tracking", verdict: "ship", mode: "fact",
        output: "Overdue actions are flagged with dates and chased to owners.",
        why: "Good hygiene. Overdue items surfaced with dates and follow-up — the log is doing its job here.",
        cost: "Nit-picking sound action tracking trains the team around the review.",
        trains: "Recognising a well-tracked action list and leaving it." },
    ],
    lesson: "The “low” regulatory risk and the closed-but-untested integration were the two that would have been yours to answer for. A program is only as safe as the risks you're honest about.",
  },
};
