/* Design & Creative — a Judgment Gym lane. The AI drafts the deliverable — copy,
   layouts, a whole content set, a UX spec — polished and confident; you sign off
   only what's on-brief, substantiated, accessible, and yours to use. Same shape as
   every other lane (see lib/gym.ts). All items tagged mode + failure pattern. */

import type { Scenario } from "@/lib/gym";

export const DESIGN_SCENARIOS: Record<string, Scenario> = {
  "design-landing-copy": {
    slug: "design-landing-copy", career: "Design & Creative", kind: "document",
    short: "Sign off an AI-drafted product launch landing page against the brand brief — the claims, the copy, the assets, and accessibility.",
    client: "Nimbus — product launch landing page",
    artifact: "Nimbus_Landing_v3.html",
    thesis: "The AI drafted the full launch page from the brand brief and the product one-pager — headline, copy, images, the CTA. It reads polished and ready to publish. Some of it is off-brief, unsupported, or not yours to use. Publish only what holds.",
    role: "You publish this — every claim and every asset ships under the brand's name.",
    aiDid: "AI wrote the whole page end to end and picked the imagery. The copy is confident and the layout is clean; some of it the brand can't stand behind.",
    brief: [
      { l: "Product", v: "Nimbus — a project-management tool for small teams" },
      { l: "Brand voice", v: "Plain, specific, no hype — say what it does" },
      { l: "Rule", v: "Every claim substantiated; only licensed assets" },
      { l: "Bar", v: "WCAG 2.1 AA — the page must be usable by everyone" },
    ],
    items: [
      { area: "Hero headline", verdict: "flag", severity: "critical", mode: "judgment", pattern: "overreach",
        output: "“The last project tool you'll ever need — guaranteed to double your team's output.”",
        why: "An unbacked performance guarantee, and off the brief's plain voice. “Guaranteed to double your output” is a claim the brand can't substantiate and that regulators treat as deceptive — hype the brief explicitly rules out.",
        cost: "A false-advertising exposure on the most visible line of the page, and a promise the product can't keep the moment a customer measures it.",
        trains: "Catching the unbacked superlative a helpful draft reaches for — say what it does, never guarantee an outcome you can't." },
      { area: "Stat callout", verdict: "flag", severity: "major", mode: "fact", pattern: "fabrication",
        output: "“Teams using Nimbus save an average of 11 hours a week.”",
        why: "There's no study behind it. The figure is invented and presented as fact — a confident number with nothing to cite.",
        cost: "The first customer, journalist, or competitor who asks for the source finds nothing, and a made-up metric on a public page is a claim you have to defend or retract.",
        trains: "Demanding the source behind a number before it goes on a public page, not trusting a tidy statistic." },
      { area: "Hero image", verdict: "flag", severity: "major", mode: "fact", pattern: "unverified",
        output: "A hero photo pulled from a stock site — the watermarked comp, with no purchased license on file.",
        why: "It's a preview, not a licensed asset. Using the comp on a live commercial page is a rights violation — the AI picked a good-looking image without confirming usage rights.",
        cost: "A takedown and retroactive licensing fees at best, an infringement claim at worst — all avoidable by checking the license.",
        trains: "Confirming an asset's license covers commercial use before it ships, not assuming a good image is a cleared one." },
      { area: "Body & button contrast", verdict: "flag", severity: "major", mode: "fact", pattern: "omission",
        output: "Body copy set in light gray (#AAAAAA) on white; the CTA label is white on a pale mint fill.",
        why: "Both fail WCAG AA contrast (text needs 4.5:1). Low-vision users can't read the copy or the button — the accessibility bar the brief sets, quietly missed.",
        cost: "Readers who can't parse the page and an ADA exposure on a public commercial site — the kind of gap that draws a demand letter.",
        trains: "Reading a layout for the contrast failure the eye glides past, and treating the AA bar as a requirement, not a nicety." },
      { area: "Call to action", verdict: "ship", mode: "judgment",
        output: "“Start your first project — free for 14 days, no card required.”",
        why: "Clear, specific, on-voice. States the offer plainly and removes the friction — exactly the brief's register, nothing to fix.",
        cost: "Rewriting a clean, honest CTA just delays the launch and dulls a line that already works.",
        trains: "Letting plain, specific copy stand instead of dressing it up." },
      { area: "Value-prop section", verdict: "ship", mode: "judgment",
        output: "Three blocks — “See every project in one view,” “Know what's blocked,” “Ship on time” — each with a one-line explanation.",
        why: "Matches the brief's plain, specific voice: concrete benefits, no hype, no invented numbers. Good work.",
        cost: "Reworking on-brief copy that's already right signals you can't tell strong work from weak.",
        trains: "Recognizing copy that hits the brand voice and leaving it alone." },
    ],
    lesson: "The guaranteed-to-double claim and the unlicensed hero image were the two that would have been yours to answer for. AI drafts a polished page in seconds — but every claim and every asset ships under the brand's name, and a hype line or a borrowed image is a real liability.",
  },

  "design-social-set": {
    slug: "design-social-set", career: "Design & Creative", kind: "message",
    short: "Sign off an AI-produced social content set before it's scheduled — brand voice, claims, disclosure, and rights.",
    client: "Fern & Oak — spring launch social set",
    artifact: "Fern & Oak — spring launch · 6-post set",
    thesis: "The AI produced the whole set from the campaign brief — captions, hashtags, the carousel images, an influencer post. It's ready to schedule. Some of it is off-brand, unsubstantiated, undisclosed, or not licensed. Schedule only what's clean.",
    aiDid: "AI wrote every caption, chose the imagery, and drafted the paid creator's post. It looks on-trend and ready; some of it the brand answers for.",
    brief: [
      { l: "Brand", v: "Fern & Oak — a skincare brand, 10 years established" },
      { l: "Voice", v: "Warm, inclusive, plain — no hype, no medical claims" },
      { l: "Rule", v: "Paid partnerships disclosed (#ad); only licensed assets" },
      { l: "Rule", v: "No unsubstantiated efficacy claims" },
    ],
    items: [
      { area: "Efficacy claim", verdict: "flag", severity: "critical", mode: "judgment", pattern: "overreach",
        output: "“Clinically proven to erase wrinkles in 7 days.”",
        why: "A medical claim with no trial behind it. “Clinically proven” and “erase wrinkles” are exactly the unsubstantiated efficacy claims the brief forbids and the FTC enforces — a promise the brand can't stand up.",
        cost: "An FTC / advertising-standards exposure and a claim that has to be pulled the moment anyone asks for the study — reputational and regulatory in one line.",
        trains: "Refusing an efficacy claim without the evidence behind it, however confidently the draft states it." },
      { area: "Influencer post", verdict: "flag", severity: "major", mode: "fact", pattern: "omission",
        output: "The paid creator's post reads as an organic recommendation — no #ad or “paid partnership” label anywhere.",
        why: "A required disclosure is missing. The FTC requires paid endorsements to be clearly disclosed; the label is simply absent, and an undisclosed paid post is precisely what gets enforced.",
        cost: "A violation that lands on both the brand and the creator — the omission a regulator or a screenshot surfaces long after it posts.",
        trains: "Checking every paid post carries a clear, unmissable disclosure — the thing that isn't on the page is the risk." },
      { area: "Carousel assets", verdict: "flag", severity: "major", mode: "fact", pattern: "unverified",
        output: "Slide 3 uses a display font from a “free for personal use” download and a photo credited only “via Pinterest.”",
        why: "Neither is cleared for commercial use. A personal-use font and a Pinterest-sourced photo carry no commercial license — the AI grabbed assets that look free without confirming the rights.",
        cost: "Font-foundry and photographer infringement claims, both entirely avoidable by checking the license before the set ships.",
        trains: "Confirming commercial rights on every font and image, not treating “found online” as “free to use.”" },
      { area: "Launch caption", verdict: "flag", severity: "minor", mode: "judgment", pattern: "fabrication",
        output: "“We're just three friends who started mixing serums in a garage last year — help us go viral!”",
        why: "An invented backstory. Fern & Oak is a ten-year-old company, not a year-old garage startup — a fabricated origin in the brand's own voice, and off the warm, established tone the brief sets.",
        cost: "A public misrepresentation of the company that customers and press can disprove in a click — small, but it's the brand's credibility.",
        trains: "Checking a brand claim against what's actually true before it posts in the brand's voice." },
      { area: "Community caption", verdict: "ship", mode: "judgment",
        output: "“Skin comes in every shade and story. Here's what worked for three very different people this spring.”",
        why: "Warm, inclusive, plain — exactly the brand voice, with no hype and no efficacy claim. Good work.",
        cost: "Rewriting a caption that already nails the voice just delays the schedule.",
        trains: "Recognizing on-brand, inclusive copy and letting it stand." },
      { area: "Accessibility", verdict: "ship", mode: "fact",
        output: "Every image ships with descriptive alt text, and the video post includes burned-in captions.",
        why: "Alt text and captions make the set usable by screen-reader users and by Deaf and hard-of-hearing viewers — the standard done properly, not skipped.",
        cost: "Stripping accessibility work that's correct and expected would make the set reach fewer people for no gain.",
        trains: "Recognizing accessibility done right and keeping it in." },
    ],
    lesson: "The “clinically proven” claim and the undisclosed paid post were the two that would have been yours to answer for. AI fills a content calendar in seconds — but the brand answers for every claim it makes and every partnership it hides.",
  },

  "design-ux-spec": {
    slug: "design-ux-spec", career: "Design & Creative", kind: "document",
    short: "Sign off an AI-produced mobile checkout spec against the brief — the constraints it honors, the evidence it cites, accessibility, and the patterns it uses.",
    client: "Loop — mobile checkout redesign",
    artifact: "Loop_Checkout_Spec_v2.pdf",
    thesis: "The AI produced the redesign spec from the brief and the research notes — the flow, the screens, the microcopy, and a rationale citing user data. It reads convincingly. Some of it ignores the brief, invents its evidence, fails accessibility, or crosses a line. Approve only what holds.",
    role: "You approve this spec — the build follows exactly what you sign off.",
    aiDid: "AI drafted the whole flow and wrote the rationale, complete with cited numbers. It's coherent and confident; some of the decisions don't survive the brief.",
    brief: [
      { l: "Product", v: "Mobile checkout for a shopping app" },
      { l: "Constraint", v: "Must work one-handed and tolerate flaky connections" },
      { l: "Rule", v: "Research claims cite a real source; no deceptive patterns" },
      { l: "Bar", v: "WCAG 2.1 AA throughout" },
    ],
    items: [
      { area: "Marketing consent", verdict: "flag", severity: "critical", mode: "judgment", pattern: "security",
        output: "The “Subscribe me to marketing emails” checkbox is pre-checked and tucked under a collapsed “More options” drawer.",
        why: "A pre-checked, hidden consent box isn't valid consent — it's a deceptive pattern that breaches GDPR/CCPA consent rules and the brief's no-dark-patterns line. It looks fine in the demo and is a compliance breach in production.",
        cost: "Regulatory exposure on how consent is collected, plus the trust hit when users discover they were opted in without agreeing — a fix that becomes an incident.",
        trains: "Spotting the dark pattern the machine reached for to lift a metric, not just whether the screen looks clean." },
      { area: "Reachability & offline", verdict: "flag", severity: "major", mode: "judgment", pattern: "unverified",
        output: "Puts the primary “Pay” button at the top of the screen and assumes a live connection at every step.",
        why: "The brief requires one-handed use and connection tolerance. A top-of-screen primary action is out of thumb reach on a phone, and a flow that assumes connectivity breaks for the transit-and-tunnel users the brief names. The spec designed for ideal conditions, not the real constraint.",
        cost: "A checkout that fails the exact conditions it was scoped for — dropped payments and abandoned carts on mobile, the thing the redesign was meant to fix.",
        trains: "Testing the design against the real constraint, not the version where everything goes right." },
      { area: "Error states", verdict: "flag", severity: "major", mode: "fact", pattern: "omission",
        output: "Form validation signals errors by turning the field border red only — no text, no icon.",
        why: "Color-only signaling fails WCAG AA (1.4.1) and is invisible to colorblind users and to screen readers. An error a user can't perceive isn't an error state — the required cue is missing.",
        cost: "Users who can't see the error can't complete checkout — lost sales and an ADA exposure baked straight into the flow.",
        trains: "Catching color-only signaling and the accessibility requirement it silently drops." },
      { area: "Rationale stat", verdict: "flag", severity: "minor", mode: "fact", pattern: "fabrication",
        output: "“73% of users abandon at the address step (per our research).”",
        why: "The research notes contain no such figure. The number is invented to justify a decision — a fabricated insight dressed as evidence and attributed to research that doesn't say it.",
        cost: "The team reprioritizes the roadmap around a statistic that doesn't exist, and the real abandonment problem goes unaddressed.",
        trains: "Tracing a cited figure back to the actual research before it drives a decision." },
      { area: "Guest checkout & recovery", verdict: "ship", mode: "judgment",
        output: "Lets users check out as a guest and resume an interrupted payment without re-entering card details.",
        why: "Reduces friction and handles the dropped-connection case the brief cares about — a genuinely good, on-brief decision.",
        cost: "Stripping a sound flow that serves the exact constraint would make the checkout worse for no reason.",
        trains: "Recognizing a design decision that serves the real constraint and letting it through." },
      { area: "Input components", verdict: "ship", mode: "fact",
        output: "Every input has a visible, persistent label and a clear focus state; tap targets are 44px minimum.",
        why: "Persistent labels, visible focus, and adequate tap targets are AA done properly — the accessibility the error states got wrong, done right here.",
        cost: "Reworking components that already meet the bar wastes the build's time.",
        trains: "Recognizing accessibility done right and keeping it." },
    ],
    lesson: "The pre-checked consent box and the color-only error states were the two that would have been yours to answer for. AI produces a convincing spec in seconds — but the build ships exactly what you approve, and a dark pattern or an inaccessible flow is a liability, not a detail.",
  },
};
