/* Audit & Accounting — the first career built 12 reps deep.
   A full month of judgment work: the AI drafts the file, you own the sign-off.
   Each rep is a real deliverable an accountant actually produces, seeded with
   buried, checkable errors and genuinely good work to leave alone. US GAAP (ASC)
   and US tax throughout. Same shape as every other lane — see lib/gym.ts. */

import type { Scenario } from "@/lib/gym";

export const ACCOUNTING_SCENARIOS: Record<string, Scenario> = {
  "audit-accounting": {
    slug: "audit-accounting", career: "Audit & Accounting",
    short: "Sign off an AI-drafted set of audit workpapers against the file — recognition, materiality, disclosure.",
    client: "Northwind Inc. — FY25 financial statement audit",
    artifact: "Northwind_FY25_Workpapers.draft",
    thesis: "The AI has drafted the workpapers and conclusions for this audit — clean, referenced, confident. Some of it doesn't hold against the standards or the numbers. Sign off only what's right.",
    brief: [
      { l: "Engagement", v: "FY25 financial statement audit, revenue $42.0m (PY $38.4m)" },
      { l: "Materiality", v: "Set at 1.5% of revenue for planning" },
      { l: "Key risk", v: "Revenue recognition on multi-year support contracts (ASC 606)" },
      { l: "New this year", v: "A related-party lease with a director's company" },
      { l: "Framework", v: "US GAAP (ASC); document the basis" },
    ],
    items: [
      { area: "Materiality calculation", verdict: "flag", severity: "minor",
        output: "Planning materiality = 1.5% × $42.0m = $680,000.",
        why: "The arithmetic is off. 1.5% of $42.0m is $630,000, not $680,000. A number that sets the threshold for everything downstream, quietly wrong.",
        cost: "An inflated threshold lets ~$50k of misstatements pass untested. If it later matters, the file shows you approved the wrong basis.",
        trains: "Re-performing the figure that anchors the whole file, not trusting the machine's arithmetic." },
      { area: "Revenue recognition memo", verdict: "flag", severity: "critical",
        output: "“The full $1.2m on the 3-year support contract signed in June is recognized in FY25, as the contract is executed and non-cancellable.”",
        why: "Wrong under ASC 606. Support delivered over time is a performance obligation satisfied over the three years — roughly $1.2m ÷ 3 in FY25, not the whole amount up front. Non-cancellable doesn't mean earned.",
        cost: "Revenue overstated by ~$800k — well over materiality. A misstated set of financials with your name on the opinion, and a restatement risk.",
        trains: "Testing the AI's technical conclusion against the actual standard, not its confident phrasing." },
      { area: "Sample selection — receivables", verdict: "ship",
        output: "Selected 25 items: all balances > materiality, plus a random monetary-unit sample of the remainder.",
        why: "Sound. Covers everything individually material and gives representative coverage of the rest — a defensible sampling approach.",
        cost: "Re-designing a valid sample wastes hours and signals you can't tell good work from bad.",
        trains: "Recognizing a methodologically sound approach and letting it stand." },
      { area: "Analytical review commentary", verdict: "flag", severity: "major",
        output: "“Gross margin rose 4 points; management attribute this to improved supplier terms. No further work required.”",
        why: "It accepts management's explanation without corroboration. A 4-point margin swing on a key risk is exactly what you're meant to substantiate — the AI wrote a plausible reason and closed the point.",
        cost: "An unexplained margin movement — potentially a recognition or cut-off error — goes untested. This is how real misstatements slip through.",
        trains: "Professional skepticism — refusing to let a tidy narrative substitute for evidence." },
      { area: "Going concern conclusion", verdict: "ship",
        output: "“Net current assets positive, revolver renewed to 2027, 12-month cash forecast stress-tested. Going concern basis appropriate.”",
        why: "Appropriate and evidenced — headroom, a renewed facility, and a stress-tested forecast. The conclusion follows the work.",
        cost: "Second-guessing a well-supported conclusion delays sign-off for no gain.",
        trains: "Confirming a conclusion is actually backed by the evidence cited." },
      { area: "Related-party disclosure", verdict: "flag", severity: "critical",
        output: "The director's-company lease is recorded in operating costs; the related-party note lists “None requiring disclosure.”",
        why: "A required disclosure is missing. A lease with a director's company is a related-party transaction that must be disclosed under ASC 850 — the AI booked the cost but never surfaced the relationship.",
        cost: "A non-compliant set of financials and a governance red flag omitted from the file. This is the omission a regulator or the next auditor finds.",
        trains: "Catching what the machine leaves out — the missing disclosure is invisible unless you know to look." },
    ],
    lesson: "The recognition memo and the missing related-party note were the two that would have been yours to answer for. AI can draft the file at speed — but the opinion, and the accountability, are still human.",
  },

  "audit-tax": {
    slug: "audit-tax", career: "Audit & Accounting",
    short: "Sign off an AI-drafted inventory and tax provision — valuation, deferred tax, cut-off.",
    client: "Meridian Manufacturing — FY25 year-end",
    artifact: "Meridian_FY25_InventoryTax.draft",
    thesis: "The AI has drafted the inventory valuation and tax provision — referenced and confident. Some of it doesn't hold against the standards or the numbers. Sign off only what's right.",
    brief: [
      { l: "Inventory", v: "$6.4m at cost; includes a slow-moving product line" },
      { l: "NRV", v: "The slow-moving line now sells below cost" },
      { l: "Tax", v: "Enacted combined tax rate rises to 25% for FY25 (was 19%)" },
      { l: "Year-end", v: "Goods in transit at Dec 31, FOB shipping point" },
    ],
    items: [
      { area: "NRV write-down", verdict: "flag", severity: "major",
        output: "“Inventory held at cost of $6.4m. No write-down required.”",
        why: "Wrong. Under ASC 330 inventory is carried at the lower of cost and net realizable value. The slow-moving line sells below cost, so it must be written down to NRV — the AI left it at cost.",
        cost: "Inventory and profit overstated by the write-down you skipped. A known impairment ignored — exactly what the standard exists to catch.",
        trains: "Applying lower-of-cost-and-NRV, not accepting “held at cost” at face value." },
      { area: "Standard cost variance", verdict: "ship",
        output: "Favorable variance of $40k released to cost of sales, immaterial and consistent with prior year.",
        why: "Reasonable. Immaterial and treated consistently — a defensible call.",
        cost: "Re-opening an immaterial, consistent treatment wastes time.",
        trains: "Letting a sound, immaterial judgment stand." },
      { area: "Deferred tax rate", verdict: "flag", severity: "critical",
        output: "Deferred tax on timing differences calculated at 19%.",
        why: "Wrong rate. Under ASC 740 deferred tax is measured at the enacted rate expected when the difference reverses — 25% for FY25, not the old 19%. A single wrong percentage flows through the whole provision.",
        cost: "The deferred tax liability is understated by nearly a third. A material misstatement in the tax line, with your sign-off on it.",
        trains: "Checking the rate the machine used against the enacted rate, not last year's." },
      { area: "Inventory count coverage", verdict: "ship",
        output: "Observed count covered 92% of value; roll-forward reconciled to year-end with no exceptions.",
        why: "Sound. High value coverage and a clean roll-forward — a defensible basis.",
        cost: "Demanding more on a well-covered count just delays sign-off.",
        trains: "Confirming coverage is adequate and moving on." },
      { area: "Cut-off — goods in transit", verdict: "flag", severity: "minor",
        output: "Goods shipped Dec 30 (FOB shipping point) excluded from year-end inventory.",
        why: "A cut-off error. FOB shipping point means title passed on shipment — those goods are the buyer's at year-end and should be in inventory. Small, but it's the boundary you're meant to test.",
        cost: "Inventory understated and a cut-off error in the file — the kind of detail the next auditor re-performs and finds.",
        trains: "Getting the cut-off right on the shipping terms, not the invoice date." },
      { area: "Accounting policy note", verdict: "ship",
        output: "Policy note states inventory valued at lower of cost and NRV; cost on a FIFO basis.",
        why: "The disclosed policy is correct and standard — even though the AI failed to apply it above. The note itself is fine.",
        cost: "Flagging a correct policy note is a false positive.",
        trains: "Judging the note on its own merits — the policy is right even where the application wasn't." },
    ],
    lesson: "The deferred-tax rate and the missing NRV write-down were the two that would have been yours to answer for. The machine drafts the numbers — you're the one who stands behind them.",
  },

  "acc-month-end": {
    slug: "acc-month-end", career: "Audit & Accounting",
    short: "Close the month off an AI-prepared bank reconciliation and accrual schedule — reconciling items, accruals, cut-off.",
    client: "Harbor Logistics — March close",
    artifact: "Harbor_Mar_Close.draft",
    thesis: "The AI has prepped the month-end close — bank recs tied out, accruals scheduled, a tidy package ready to post. A “balanced” reconciliation isn't a correct one. Post only what actually holds.",
    brief: [
      { l: "Task", v: "Reconcile the operating account and finalize March accruals" },
      { l: "Book balance", v: "$1,284,500 per the GL" },
      { l: "Bank balance", v: "$1,301,200 per the statement" },
      { l: "Watch", v: "A large March utility and legal invoice arrived April 4" },
    ],
    items: [
      { area: "Bank reconciliation", verdict: "flag", severity: "major",
        output: "Reconciliation shows book $1,284,500 + outstanding checks $16,700 = bank $1,301,200. “Reconciled — no difference.”",
        why: "The sign is backwards. Outstanding checks reduce the bank balance to reach book, they aren't added to book to reach bank. The rec only “balances” because a plug was pointed the wrong way — the real reconciling items were never identified.",
        cost: "A rec that ties to zero but hides a genuine difference. Errors and even missing cash sit undetected behind a green checkmark until they compound.",
        trains: "Reading a reconciliation for direction and logic, not just whether it foots to zero." },
      { area: "Accrued expenses", verdict: "flag", severity: "critical",
        output: "The March utility ($22k) and legal ($40k) invoices received April 4 are recorded in April, “as that's when the invoices arrived.”",
        why: "A cut-off error. The service was consumed in March, so the expense and liability belong in March regardless of the invoice date. The AI booked by invoice receipt, not by period of benefit.",
        cost: "March expenses understated by $62k and profit overstated — a period that looks better than it was. On a covenant or a bonus threshold, that gap is the difference that matters.",
        trains: "Accruing to the period the cost was incurred, not the month the paper landed." },
      { area: "Prepaid amortization", verdict: "ship",
        output: "Annual insurance premium of $24k amortized at $2k per month; March entry $2k.",
        why: "Correct. Straight-line over the coverage period, $2k a month — a clean, standard prepaid release.",
        cost: "Re-checking a correct, routine amortization just slows the close.",
        trains: "Letting a correct, mechanical entry through." },
      { area: "Payroll accrual", verdict: "ship",
        output: "Accrues 4 of 5 working days of the biweekly payroll straddling month-end, $38k, reversed in April.",
        why: "Right. Accrues the earned-but-unpaid portion and reverses next period — textbook payroll cut-off.",
        cost: "Demanding changes to a correct straddle accrual burns close-week hours you don't have.",
        trains: "Confirming a sound cut-off accrual and moving on." },
      { area: "Suspense account", verdict: "flag", severity: "minor",
        output: "A $3,100 unidentified deposit is parked in a suspense account and carried forward to April.",
        why: "Small, but it shouldn't roll unexamined. Suspense is a holding pen, not a home — an unidentified receipt at close is exactly the item to chase before it's forgotten.",
        cost: "Unreconciled items that carry month to month are how a real problem — a misposted customer payment, a duplicate — hides in plain sight for a quarter.",
        trains: "Refusing to let “suspense, carried forward” become a permanent parking spot." },
      { area: "Journal entry support", verdict: "ship",
        output: "Each manual journal has a description, a preparer, and a supporting schedule referenced.",
        why: "Good hygiene. Described, supported, and attributable — an auditable trail for the manual entries.",
        cost: "Nit-picking well-documented entries trains the team to route around the close review.",
        trains: "Recognizing sound documentation and letting it stand." },
    ],
    lesson: "The backwards reconciliation and the March invoices booked in April were the two that would have been yours to answer for. A close that balances can still be wrong — the judgment is in whether it's right.",
  },

  "acc-mgmt-accounts": {
    slug: "acc-mgmt-accounts", career: "Audit & Accounting",
    short: "Sign off an AI-built monthly board pack — variance commentary, KPI math, and the story behind the numbers.",
    client: "Vantage Retail — board reporting pack",
    artifact: "Vantage_Board_Pack_Q2.draft",
    thesis: "The AI has assembled the monthly board pack — variances explained, KPIs charted, a confident narrative. The board will act on this. Ship only the numbers and stories that hold.",
    brief: [
      { l: "Audience", v: "Monthly board meeting — decisions get made off this" },
      { l: "Revenue", v: "Actual $3.10m vs budget $3.40m" },
      { l: "Watch", v: "Gross margin and the cash runway KPI" },
      { l: "Tone", v: "Straight — flag the bad news, don't bury it" },
    ],
    items: [
      { area: "Revenue variance %", verdict: "flag", severity: "major",
        output: "“Revenue $3.10m vs budget $3.40m — a favorable variance of 8.8%.”",
        why: "Wrong sign and wrong number. Coming in $0.30m under a $3.40m budget is an 8.8% shortfall — unfavorable, not favorable. The AI computed the magnitude and mislabeled the direction.",
        cost: "A board told it beat budget when it missed by $300k. Decisions made on a reversed headline — the most damaging kind of reporting error.",
        trains: "Checking the direction of a variance, not just the percentage." },
      { area: "Gross margin commentary", verdict: "flag", severity: "major",
        output: "“Margin fell to 41% (from 46%); this is seasonal and expected to recover next quarter. No action needed.”",
        why: "An assertion with nothing behind it. A 5-point margin drop is material, and “seasonal, will recover” is asserted, not evidenced — no prior-year seasonality, no driver breakdown. It papers over the exact number the board is watching.",
        cost: "A real margin problem — pricing, input costs, mix — gets a “no action” label and a quarter's head start before anyone reacts.",
        trains: "Demanding the evidence under a reassuring narrative before it reaches the board." },
      { area: "Revenue bridge", verdict: "ship",
        output: "Waterfall from prior quarter: +volume $120k, −price $90k, −mix $60k, netting to the reported movement.",
        why: "Solid. The components reconcile to the total movement and isolate the drivers cleanly — a genuinely useful bridge.",
        cost: "Rebuilding a bridge that already ties out wastes prep time and adds nothing.",
        trains: "Recognizing analysis that actually reconciles and letting it stand." },
      { area: "Cash runway KPI", verdict: "flag", severity: "critical",
        output: "“Runway: cash $1.8m ÷ monthly burn $150k = 18 months.”",
        why: "The math is wrong. $1.8m ÷ $150k is 12 months, not 18. A single miscalculated ratio on the one KPI that governs survival.",
        cost: "A board that believes it has 18 months of runway when it has 12 delays a raise or a cost cut by half a year — potentially past the point of rescue.",
        trains: "Re-performing the KPI the whole strategy hangs on, not trusting the printed figure." },
      { area: "Headcount table", verdict: "ship",
        output: "Opening 84, +6 hires, −3 leavers, closing 87; cost per head consistent with the payroll total.",
        why: "Reconciles and ties to payroll. Clean, checkable, no issue.",
        cost: "Second-guessing a table that reconciles just delays the pack.",
        trains: "Confirming a table foots and moving on." },
      { area: "Forecast assumption", verdict: "flag", severity: "minor",
        output: "Full-year forecast assumes the missed quarter is fully recovered by year-end, with no change to the growth rate.",
        why: "Optimistic and unstated. Baking in a full catch-up after a real miss, without flagging it as an assumption, quietly holds the annual number up. Not fraud — but the board should see the assumption, not inherit it.",
        cost: "A full-year forecast that looks intact because the miss was assumed away — until Q3 arrives and the gap is now twice as hard to close.",
        trains: "Surfacing the assumption that's holding a forecast together, so the reader judges it too." },
    ],
    lesson: "The reversed revenue variance and the 18-month runway were the two that would have been yours to answer for. The board acts on the number you sign — fast and right is the whole job.",
  },

  "acc-corp-tax": {
    slug: "acc-corp-tax", career: "Audit & Accounting",
    short: "Review an AI-drafted federal corporate tax computation — deductibility, depreciation, R&D, loss limits.",
    client: "Cedar Systems Inc. — Form 1120 computation",
    artifact: "Cedar_1120_Computation.draft",
    thesis: "The AI has drafted the corporate income tax computation — schedules referenced, add-backs listed, a number at the bottom. Some positions won't survive an IRS look. File only what's defensible.",
    brief: [
      { l: "Entity", v: "C corporation, FY25 (calendar year)" },
      { l: "Book income", v: "$2.4m before tax" },
      { l: "In the mix", v: "Client meals, a late-filing penalty, new equipment, an R&D project" },
      { l: "Carryforward", v: "$1.9m federal NOL from 2022" },
    ],
    items: [
      { area: "Meals deduction", verdict: "flag", severity: "minor",
        output: "Business meals with clients of $60k deducted at 100%.",
        why: "Over-deducted. Business meals are 50% deductible for FY25 — the temporary 100% provision expired at the end of 2022. The AI applied a rule that no longer exists.",
        cost: "$30k of deductions disallowed on exam, plus interest — a small, certain adjustment the IRS finds mechanically.",
        trains: "Checking the deduction percentage against the current year's rule, not a lapsed one." },
      { area: "Penalty add-back", verdict: "ship",
        output: "A $12k late-filing penalty is added back as non-deductible in the book-to-tax reconciliation.",
        why: "Correct. Fines and penalties paid to a government are non-deductible under §162(f) — the add-back is right.",
        cost: "Removing a correct add-back would understate taxable income and create the very exposure you're trying to avoid.",
        trains: "Recognizing a correct permanent difference and leaving it." },
      { area: "R&D costs (§174)", verdict: "flag", severity: "critical",
        output: "The full $500k of qualifying research expenditure is deducted in FY25.",
        why: "Wrong since the §174 change. Specified R&D expenditures must be capitalized and amortized (five years for domestic research), not expensed immediately. The AI took the old full-expensing position.",
        cost: "Taxable income understated by roughly $450k in year one — a material underpayment, penalties, and an amended return once it's caught.",
        trains: "Applying the current capitalize-and-amortize rule the machine wrote around." },
      { area: "Bonus depreciation", verdict: "flag", severity: "major",
        output: "New equipment of $300k claimed at 100% bonus depreciation in FY25.",
        why: "Wrong rate. Bonus depreciation is phasing down — 40% for property placed in service in 2025, not 100%. The AI used the fully-phased-in rate from earlier years.",
        cost: "An over-claimed first-year deduction of ~$180k — reversed on exam with interest, and a restated computation.",
        trains: "Pulling the current-year bonus rate, not the one from when the rule was new." },
      { area: "NOL utilization", verdict: "flag", severity: "major",
        output: "The $1.9m NOL carryforward is used to offset 100% of taxable income.",
        why: "Over-used. Post-2017 NOLs can offset only 80% of taxable income in a year — the AI wiped out the whole liability. The remaining 20% is taxable now.",
        cost: "Tax underpaid on 20% of income, with the shortfall plus penalties surfacing on notice. A confident zero that should never have been zero.",
        trains: "Applying the 80% limitation, not letting a carryforward zero out the bill." },
      { area: "State tax deduction", verdict: "ship",
        output: "State income taxes paid are deducted in arriving at federal taxable income.",
        why: "Correct at the entity level — state income taxes are deductible for a C corporation's federal computation. Right treatment.",
        cost: "Disallowing a valid deduction overstates the federal liability and the client overpays.",
        trains: "Confirming a correct deduction and moving on." },
    ],
    lesson: "The immediately-expensed R&D and the 100% NOL offset were the two that would have been yours to answer for. The AI writes a confident return — you're the one who signs it under penalties of perjury.",
  },

  "acc-sales-tax": {
    slug: "acc-sales-tax", career: "Audit & Accounting",
    short: "Sign off an AI-prepared multi-state sales tax position — nexus, taxability, exemptions.",
    client: "Brightloom SaaS — multi-state sales tax review",
    artifact: "Brightloom_SalesTax_Review.draft",
    thesis: "The AI has reviewed the company's sales tax obligations across states — thresholds checked, a filing map drawn. Get this wrong and the liability compounds silently. Sign off only what's correct.",
    brief: [
      { l: "Business", v: "SaaS subscriptions sold nationwide, remote team" },
      { l: "Texas", v: "$140k of sales, no office or staff" },
      { l: "California", v: "$180k of sales, no physical presence" },
      { l: "Watch", v: "One large sale ran on a claimed resale exemption" },
    ],
    items: [
      { area: "Texas nexus", verdict: "flag", severity: "critical",
        output: "“No office or employees in Texas, so no filing obligation. No registration required.”",
        why: "Physical-presence thinking, post-Wayfair. Economic nexus is triggered by sales volume alone — $140k of Texas sales is over the $100k economic-nexus threshold, so registration and collection are required regardless of physical presence.",
        cost: "Uncollected tax on $140k of sales accruing as a liability the company now owes out of pocket, plus penalties and interest, back to the date nexus was crossed.",
        trains: "Testing nexus on economic thresholds, not just physical presence." },
      { area: "SaaS taxability — Texas", verdict: "flag", severity: "major",
        output: "SaaS treated as a non-taxable service in Texas.",
        why: "Wrong for the state. Texas taxes SaaS as a data-processing service (with a partial exemption). Treating it as fully non-taxable under-collects on every Texas invoice — taxability is state-by-state, not a single rule.",
        cost: "A systematic under-collection on the taxable portion of every Texas sale — a growing exposure that scales with revenue.",
        trains: "Checking product taxability against the specific state, not assuming a nationwide answer." },
      { area: "California registration", verdict: "ship",
        output: "With $180k of sales over California's $500k threshold not met, no California registration proposed.",
        why: "Correct. California's economic-nexus threshold is $500,000; at $180k the company is below it, so no obligation yet. The right call — and a reminder thresholds differ by state.",
        cost: "Registering early where there's no obligation creates filing burden and returns for nothing.",
        trains: "Confirming a below-threshold state is genuinely below — and leaving it." },
      { area: "Resale exemption", verdict: "flag", severity: "major",
        output: "A large sale was treated as exempt for resale; no exemption certificate is on file.",
        why: "Unsupported exemption. An exemption is only as good as the certificate behind it — without a valid resale certificate on file, the sale is presumed taxable and the exemption fails on audit.",
        cost: "On audit the exemption is denied and the tax assessed against the company, not the customer — plus penalties for the undocumented position.",
        trains: "Requiring the certificate before accepting an exemption, not the claim alone." },
      { area: "Marketplace sales", verdict: "ship",
        output: "Sales made through a large marketplace are excluded, as the marketplace collects and remits under marketplace-facilitator rules.",
        why: "Correct. Marketplace-facilitator laws put the collection obligation on the marketplace — excluding those sales from the company's own liability is right.",
        cost: "Double-collecting on marketplace sales would overcharge customers and misstate the liability.",
        trains: "Recognizing where the obligation legitimately sits elsewhere." },
      { area: "Filing frequency", verdict: "ship",
        output: "Proposes quarterly filing in a newly-registered state based on projected volume, matching the state's assigned frequency.",
        why: "Reasonable. Filing frequency follows the state's assignment by volume — quarterly fits the projection here. A sensible operational call.",
        cost: "Overriding a correct frequency creates missed-deadline risk for no reason.",
        trains: "Letting a sound compliance-cadence decision stand." },
    ],
    lesson: "The Texas economic nexus and the missing resale certificate were the two that would have been yours to answer for. Sales tax errors don't bounce — they accrue silently until someone adds them up.",
  },

  "acc-payroll": {
    slug: "acc-payroll", career: "Audit & Accounting",
    short: "Sign off an AI-processed payroll run — worker classification, overtime, withholding, benefits.",
    client: "Summit Trades Co. — biweekly payroll",
    artifact: "Summit_Payroll_Run.draft",
    thesis: "The AI has processed the payroll run — hours totaled, taxes withheld, a batch ready to release. Payroll errors reach real people and real regulators fast. Release only what's right.",
    brief: [
      { l: "Task", v: "Process the biweekly run and release for payment" },
      { l: "Workers", v: "Hourly crew plus one long-term “contractor” full-time on site" },
      { l: "Watch", v: "A crew member worked 48 hours one week" },
      { l: "Rule", v: "Non-exempt hourly, FLSA overtime applies" },
    ],
    items: [
      { area: "Worker classification", verdict: "flag", severity: "critical",
        output: "A worker who is full-time, on the company's schedule, using company tools and supervised daily is paid as a 1099 contractor with no withholding.",
        why: "Misclassification. Under the common-law and economic-reality tests, control and integration like this make the worker an employee — the 1099 label doesn't match the facts. This is the classic payroll landmine.",
        cost: "Back employment taxes, unpaid overtime, penalties, and interest — plus potential state action. Misclassification is one of the most expensive payroll findings there is.",
        trains: "Classifying on the substance of the relationship, not the label on the paperwork." },
      { area: "Overtime calculation", verdict: "flag", severity: "major",
        output: "The crew member who worked 48 hours is paid 48 hours at the straight-time rate.",
        why: "FLSA overtime skipped. Hours over 40 in a week for a non-exempt worker must be paid at 1.5× — 8 of those 48 hours are owed at time-and-a-half, not straight time.",
        cost: "Underpaid wages that become a wage-and-hour claim, with liquidated (double) damages available. A cheap fix now, an expensive one later.",
        trains: "Applying the overtime premium over 40 hours, not just totaling the hours." },
      { area: "FICA withholding", verdict: "ship",
        output: "Employer FICA computed at 7.65% (6.2% Social Security to the wage base + 1.45% Medicare) matching employee withholding.",
        why: "Correct. The combined 7.65% employer match, split as stated, is right — and correctly matched to the employee side.",
        cost: "“Fixing” a correct FICA calc introduces the error you were trying to avoid.",
        trains: "Recognizing a correct statutory calculation and leaving it." },
      { area: "Health benefit treatment", verdict: "ship",
        output: "Employer contributions to the qualified health plan are excluded from taxable wages.",
        why: "Correct. Employer contributions to a qualified health plan are pre-tax and properly excluded from taxable wages.",
        cost: "Taxing an excludable benefit overstates withholding and shorts the employee's pay.",
        trains: "Confirming a correct pre-tax treatment and moving on." },
      { area: "Bonus withholding", verdict: "flag", severity: "minor",
        output: "A one-time cash bonus is added to the regular check with no separate supplemental-wage treatment noted.",
        why: "A small handling gap. Supplemental wages like a bonus have a defined withholding method — rolled into the regular check without flagging it, the withholding can come out wrong on the edge.",
        cost: "Under- or over-withholding on the bonus that surfaces as a surprise on the worker's return — minor, but avoidable friction.",
        trains: "Spotting supplemental wages that need their own withholding treatment." },
      { area: "PTO accrual", verdict: "ship",
        output: "Paid-time-off accrues at the stated policy rate per hours worked and is tracked as a liability.",
        why: "Right. Accrued at policy and carried as a liability — the correct treatment for earned PTO.",
        cost: "Re-working a correct accrual just delays the run.",
        trains: "Letting a correct, policy-based accrual stand." },
    ],
    lesson: "The misclassified contractor and the skipped overtime premium were the two that would have been yours to answer for. Payroll is where an accounting error becomes a person's paycheck and a regulator's file.",
  },

  "acc-ap-controls": {
    slug: "acc-ap-controls", career: "Audit & Accounting",
    short: "Approve an AI-prepared vendor payment batch — duplicate invoices, fraud red flags, approval limits.",
    client: "Irongate Facilities — weekly AP run",
    artifact: "Irongate_AP_Batch.draft",
    thesis: "The AI has assembled this week's vendor payment batch — invoices matched, totals ready to release. A clean-looking batch is where duplicate payments and fraud hide. Release only what's legitimate.",
    brief: [
      { l: "Task", v: "Review and release the weekly AP batch" },
      { l: "Controls", v: "3-way match; payments over $25k need a second approver" },
      { l: "Watch", v: "A vendor emailed new bank details this week" },
      { l: "Volume", v: "60 invoices, one large and several routine" },
    ],
    items: [
      { area: "Changed bank details", verdict: "flag", severity: "critical",
        output: "A $48k payment to a known vendor is routed to new bank details supplied by email this week; “updated per vendor request.”",
        why: "A textbook business-email-compromise red flag. A mid-cycle bank-detail change by email, unverified through a known contact, is exactly how payment-redirection fraud works. The AI took the email at face value.",
        cost: "$48k wired to a fraudster's account, rarely recoverable — one of the most common and costly frauds hitting finance teams today.",
        trains: "Verifying a bank-detail change out-of-band before releasing, never trusting the email that requests it." },
      { area: "Duplicate invoice", verdict: "flag", severity: "major",
        output: "Invoice #4471 for $9,200 appears in the batch; the same invoice number and amount was paid last week.",
        why: "A duplicate. Same vendor, same invoice number, same amount, one week apart — a classic double-payment the three-way match should have caught but the AI passed through.",
        cost: "$9,200 paid twice. Recoverable in theory, but only if someone notices — and duplicates are designed not to be noticed.",
        trains: "Catching the duplicate the batch presents as just another line." },
      { area: "Approval threshold", verdict: "flag", severity: "major",
        output: "A $31k invoice is marked approved with a single approver.",
        why: "Breaks the control. Payments over $25k require a second approver — at $31k this one is over the line with only one sign-off. The AI applied the payment but not the approval rule.",
        cost: "A control override on a material payment. If it's wrong — or fraudulent — there was no second set of eyes, and the breach is on the file.",
        trains: "Enforcing the approval threshold the workflow is supposed to guarantee." },
      { area: "Three-way match", verdict: "ship",
        output: "A $14k invoice is released with a matching purchase order and goods-receipt note attached.",
        why: "Clean. PO, receipt, and invoice agree on quantity and price — the three-way match is satisfied. A legitimate payment.",
        cost: "Holding a correctly-matched invoice delays a real vendor payment and strains the relationship.",
        trains: "Recognizing a satisfied three-way match and releasing it." },
      { area: "Early-payment discount", verdict: "ship",
        output: "A vendor offering 2/10 net 30 is scheduled for payment within the discount window to capture the 2%.",
        why: "Good treasury sense. Taking a 2% discount for paying 20 days early is a strong effective return — a sound, deliberate call.",
        cost: "Skipping a worthwhile discount leaves money on the table on every such invoice.",
        trains: "Letting a sound working-capital decision stand." },
      { area: "New vendor setup", verdict: "flag", severity: "minor",
        output: "A first-time vendor is paid in the same run it was created, with a W-9 “to follow.”",
        why: "Order of operations. A new vendor should be validated — W-9 collected, details confirmed — before the first payment, not after. Minor here, but it's the gap larger vendor frauds walk through.",
        cost: "A payment out the door before the payee is verified, and a missing W-9 that becomes a 1099 problem at year-end.",
        trains: "Completing vendor validation before the first payment, not after." },
    ],
    lesson: "The redirected bank details and the duplicate invoice were the two that would have been yours to answer for. AP is a control function — the machine can match, but it can't smell a fraud.",
  },

  "acc-cash-forecast": {
    slug: "acc-cash-forecast", career: "Audit & Accounting",
    short: "Sign off an AI-built 13-week cash flow forecast — covenant headroom, collection assumptions, formula integrity.",
    client: "Northpoint Foods — 13-week cash model",
    artifact: "Northpoint_13wk_Cash.draft",
    thesis: "The AI has built the 13-week cash flow the lender and the board will both read — inflows projected, covenant headroom shown. A rosy forecast is worse than none. Sign off only what the numbers support.",
    brief: [
      { l: "Situation", v: "Tight liquidity; a minimum-cash covenant of $500k" },
      { l: "Model", v: "13-week direct cash flow, weekly buckets" },
      { l: "Watch", v: "Receivables collection timing drives everything" },
      { l: "Reader", v: "The lender relies on this for the covenant test" },
    ],
    items: [
      { area: "Collection assumption", verdict: "flag", severity: "critical",
        output: "Assumes 95% of receivables collect within 30 days; historical collection has run at 70% with a slow-paying key account.",
        why: "Unsupported optimism on the model's most sensitive input. Jumping from a historical 70% to an assumed 95%, with a known slow payer, inflates every weekly cash position. The whole forecast rests on this number.",
        cost: "A model that shows headroom the company won't actually have. When collections come in at 70%, cash breaches the covenant weeks before the model said — and the lender was told otherwise.",
        trains: "Anchoring the key assumption to actual history, not the number that makes the model work." },
      { area: "Covenant headroom", verdict: "flag", severity: "major",
        output: "“Minimum projected cash $520k vs $500k covenant — headroom maintained, no breach.”",
        why: "True only on the inflated assumption above, and razor-thin even then. $20k of headroom on a model built with an optimistic collection rate isn't headroom — it's a breach waiting for reality. The AI reported comfort the numbers don't give.",
        cost: "A “no breach” conclusion the company acts on — no drawdown, no cost action — until the covenant trips and the facility is suddenly in default.",
        trains: "Reading headroom against the reliability of the assumptions beneath it, not the printed margin." },
      { area: "Opening balance", verdict: "ship",
        output: "Week 1 opening cash ties to the latest bank statement and reconciled ledger.",
        why: "Correct starting point. The model opens from an actual, reconciled cash figure — the right foundation.",
        cost: "Re-checking a tied-out opening balance just delays a time-critical model.",
        trains: "Confirming the model starts from reality and moving on." },
      { area: "Roll-forward formula", verdict: "flag", severity: "major",
        output: "Each week's closing cash = opening + inflows − outflows; but week 6 hard-codes a $200k figure over the formula.",
        why: "A broken link. One week's closing balance is a typed-in number, not the formula — so every week after it is disconnected from the actual flows. A hard-code buried in a live model.",
        cost: "From week 6 on, the model stops responding to the inputs. A change in collections or costs never flows through, and the forecast quietly lies for the back half of the period.",
        trains: "Auditing a model for the hard-coded cell that breaks the chain." },
      { area: "Payroll timing", verdict: "ship",
        output: "Biweekly payroll is placed in the correct weeks, with the month containing three payrolls modeled accordingly.",
        why: "Right. Payroll lands in the actual pay weeks and the three-payroll month is captured — a common trap the model avoided.",
        cost: "Second-guessing correct payroll timing wastes review time on the part that's right.",
        trains: "Recognizing correctly-timed outflows and letting them stand." },
      { area: "Sensitivity note", verdict: "ship",
        output: "Includes a downside case at 70% collections showing the covenant breaching in week 9.",
        why: "Genuinely useful — and honest. A downside at the historical rate, showing exactly when the covenant trips, is the analysis a good model includes. This is what the whole pack should have led with.",
        cost: "Cutting the downside case would strip out the one view the reader most needs.",
        trains: "Valuing the scenario that tells the reader the truth, not just the base case." },
    ],
    lesson: "The 95% collection assumption and the week-6 hard-code were the two that would have been yours to answer for. A cash model is only as honest as its worst assumption — and the lender is reading it too.",
  },

  "acc-lease": {
    slug: "acc-lease", career: "Audit & Accounting",
    short: "Sign off an AI-drafted lease accounting memo — classification, balance-sheet recognition, disclosure (ASC 842).",
    client: "Atlas Distribution — new warehouse lease",
    artifact: "Atlas_Lease_Memo.draft",
    thesis: "The AI has drafted the accounting for a new warehouse lease — classified, measured, disclosed under ASC 842. Lease accounting is where old habits produce confident, wrong answers. Sign off only what holds.",
    brief: [
      { l: "Lease", v: "10-year warehouse lease; asset's economic life ~11 years" },
      { l: "Payments", v: "$300k/year; PV close to the asset's fair value" },
      { l: "Standard", v: "ASC 842 — recognize right-of-use asset and lease liability" },
      { l: "Note", v: "A separate equipment lease is with a related party" },
    ],
    items: [
      { area: "Balance-sheet recognition", verdict: "flag", severity: "critical",
        output: "“As an operating lease, payments are expensed straight-line and the lease stays off the balance sheet.”",
        why: "Pre-ASC 842 thinking. Under the current standard, operating leases go on the balance sheet too — a right-of-use asset and a lease liability. “Operating means off-balance-sheet” is exactly the habit the standard replaced.",
        cost: "Assets and liabilities each understated by the capitalized lease — a material balance-sheet omission that distorts leverage ratios and every covenant built on them.",
        trains: "Applying the current on-balance-sheet model, not the pre-842 operating-lease reflex." },
      { area: "Lease classification", verdict: "flag", severity: "major",
        output: "Classified as an operating lease.",
        why: "Likely finance, not operating. A 10-year term against an ~11-year economic life is a major part of the life, and the PV of payments is close to fair value — either criterion pushes this to a finance lease. The AI defaulted to operating.",
        cost: "Wrong expense pattern (straight-line vs front-loaded interest plus amortization) and a misclassified lease that reshapes the income statement and the metrics off it.",
        trains: "Running the classification criteria, not defaulting to the lighter-touch answer." },
      { area: "Discount rate", verdict: "ship",
        output: "Lease liability measured using the incremental borrowing rate, as the rate implicit in the lease isn't readily determinable.",
        why: "Correct. When the implicit rate isn't determinable, the incremental borrowing rate is the right input — properly applied.",
        cost: "Second-guessing the correct rate basis just reopens settled measurement.",
        trains: "Confirming a correct measurement input and moving on." },
      { area: "Related-party lease disclosure", verdict: "flag", severity: "major",
        output: "The equipment lease with a related party is accounted for on its terms; no related-party disclosure is included.",
        why: "A missing disclosure. Even accounted for on its written terms, a lease with a related party requires related-party disclosure under ASC 850. The AI handled the accounting and skipped the note.",
        cost: "A non-compliant disclosure set and a related-party arrangement hidden from the reader — the omission a reviewer or regulator flags.",
        trains: "Remembering the related-party note even when the accounting itself looks fine." },
      { area: "Short-term lease", verdict: "ship",
        output: "A 9-month equipment rental is expensed straight-line under the short-term lease exemption, with no ROU asset.",
        why: "Correct. A lease of 12 months or less can use the short-term exemption and stay off the balance sheet — properly applied here.",
        cost: "Capitalizing a genuine short-term lease adds work and clutter for no benefit.",
        trains: "Recognizing a valid exemption and using it." },
      { area: "Lease payment schedule", verdict: "ship",
        output: "Maturity analysis of undiscounted lease payments by year is disclosed, reconciling to the lease liability.",
        why: "Right. The maturity table is a required disclosure and it reconciles to the recognized liability — clean.",
        cost: "Rebuilding a schedule that already reconciles wastes time.",
        trains: "Letting a correct, reconciling disclosure stand." },
    ],
    lesson: "The off-balance-sheet treatment and the operating classification were the two that would have been yours to answer for. ASC 842 punishes old instincts — the confident wrong answer is the one that reads like the old rule.",
  },

  "acc-consolidation": {
    slug: "acc-consolidation", career: "Audit & Accounting",
    short: "Sign off an AI-prepared group consolidation — intercompany elimination, noncontrolling interest, FX translation.",
    client: "Keystone Group — FY25 consolidation",
    artifact: "Keystone_Consol_FY25.draft",
    thesis: "The AI has consolidated the group — subsidiaries added across, intercompany stripped out, a foreign sub translated. Consolidation is where a missed elimination inflates the whole group. Sign off only what nets correctly.",
    brief: [
      { l: "Group", v: "Parent plus an 80%-owned subsidiary and a foreign sub" },
      { l: "Intercompany", v: "The sub sold goods to the parent; some remain in ending inventory" },
      { l: "NCI", v: "20% noncontrolling interest to reflect" },
      { l: "FX", v: "Foreign sub translated to the group's reporting currency" },
    ],
    items: [
      { area: "Intercompany sales elimination", verdict: "flag", severity: "critical",
        output: "Intercompany revenue and cost are eliminated, but the unrealized profit in the parent's ending inventory is left in.",
        why: "A partial elimination. The intercompany revenue nets out, but profit on goods still sitting in ending inventory hasn't been earned by the group — it must be eliminated too. The AI did the easy half and stopped.",
        cost: "Group inventory and profit overstated by the unrealized margin — a consolidated number that's inflated by a sale the group made to itself.",
        trains: "Eliminating the unrealized profit in inventory, not just the intercompany sale line." },
      { area: "Noncontrolling interest", verdict: "flag", severity: "major",
        output: "100% of the subsidiary's profit is attributed to the parent; no share is allocated to the noncontrolling interest.",
        why: "NCI ignored. With 80% ownership, 20% of the sub's profit belongs to the noncontrolling interest and must be split out — the AI swept all of it to the parent.",
        cost: "Profit attributable to the parent overstated by the 20% NCI share, and a missing NCI line on the balance sheet. A misstatement in the group's headline earnings.",
        trains: "Splitting subsidiary profit to the NCI, not defaulting everything to the parent." },
      { area: "FX translation adjustment", verdict: "flag", severity: "major",
        output: "The gain on translating the foreign subsidiary is recorded in net income for the year.",
        why: "Wrong home for it. Under the current-rate method, the translation adjustment goes to other comprehensive income (the cumulative translation adjustment in equity), not net income. The AI routed an equity movement through the P&L.",
        cost: "Net income inflated by an FX translation swing that isn't an earnings item — volatility dropped straight into profit, distorting every earnings-based metric.",
        trains: "Sending the translation adjustment to OCI, not the income statement." },
      { area: "Elimination of intercompany balances", verdict: "ship",
        output: "The intercompany receivable in the parent and payable in the sub are eliminated against each other in full.",
        why: "Correct. Reciprocal intercompany balances net to zero on consolidation — properly eliminated here.",
        cost: "Leaving them in would gross up group assets and liabilities equally for a balance the group owes itself.",
        trains: "Recognizing a correct reciprocal elimination and moving on." },
      { area: "Goodwill measurement", verdict: "ship",
        output: "Goodwill from the acquisition is carried at cost less any impairment, not amortized.",
        why: "Correct under US GAAP. Goodwill isn't amortized; it's tested for impairment and carried at cost less impairment. Right treatment.",
        cost: "Amortizing goodwill would be a straight departure from the standard.",
        trains: "Confirming the correct non-amortization treatment and leaving it." },
      { area: "Balance sheet translation rate", verdict: "ship",
        output: "The foreign sub's assets and liabilities are translated at the year-end closing rate.",
        why: "Correct. Under the current-rate method, balance-sheet items translate at the closing rate — properly applied.",
        cost: "Using an average or historical rate for the balance sheet would misstate the translated position.",
        trains: "Letting a correct translation-rate choice stand." },
    ],
    lesson: "The unrealized inventory profit and the missing NCI split were the two that would have been yours to answer for. Consolidation compounds — one missed elimination inflates the whole group, and the group number is the one that gets read.",
  },

  "acc-saas-revenue": {
    slug: "acc-saas-revenue", career: "Audit & Accounting",
    short: "Sign off an AI-drafted revenue recognition schedule for a SaaS deal — timing, setup fees, discounts (ASC 606).",
    client: "Lumen Cloud — enterprise deal recognition",
    artifact: "Lumen_Q4_RevRec.draft",
    thesis: "The AI has drafted how a big enterprise deal recognizes into revenue — a schedule that lands neatly in the quarter. Revenue timing is where pressure meets the standard. Sign off only what ASC 606 supports.",
    brief: [
      { l: "Deal", v: "$240k annual SaaS subscription, signed Oct 1" },
      { l: "Extras", v: "A $30k non-refundable setup fee; a $60k multi-year discount" },
      { l: "Pressure", v: "Q4 close — the number matters to the quarter" },
      { l: "Standard", v: "ASC 606 — recognize as obligations are satisfied" },
    ],
    items: [
      { area: "Subscription timing", verdict: "flag", severity: "critical",
        output: "“The full $240k annual subscription is recognized on Oct 1 at contract signing.”",
        why: "Wrong under ASC 606. Access to the software is a performance obligation satisfied over the year, so the $240k recognizes ratably — about $60k in Q4, not the whole amount at signing. Signing isn't delivering.",
        cost: "Revenue overstated by ~$180k in the quarter — a classic period-inflating error that becomes a restatement when the auditor unwinds it.",
        trains: "Recognizing over the service period, not at the moment of signing." },
      { area: "Setup fee", verdict: "flag", severity: "major",
        output: "The $30k non-refundable setup fee is recognized immediately as it's earned on activation.",
        why: "Non-refundable isn't the test. A setup fee that doesn't transfer a distinct good or service is part of the subscription and recognizes over the contract term — not upfront just because the cash is non-refundable.",
        cost: "Another $30k pulled into the quarter it doesn't belong in, stacking on the subscription error and enlarging the same overstatement.",
        trains: "Testing whether the fee is a distinct obligation, not whether the cash is refundable." },
      { area: "Multi-year discount", verdict: "ship",
        output: "The $60k discount is allocated across the performance obligations in proportion to their standalone selling prices.",
        why: "Correct. A discount is allocated across the obligations on a relative standalone-selling-price basis — properly applied here.",
        cost: "Re-allocating a correctly-spread discount just reopens settled measurement.",
        trains: "Recognizing a correct transaction-price allocation and moving on." },
      { area: "Contract combination", verdict: "ship",
        output: "A separate support contract signed the same day with the same customer is assessed for combination and treated as one arrangement.",
        why: "Right. Contracts with the same customer at the same time are assessed for combination — treating them as one arrangement is the correct 606 step.",
        cost: "Splitting genuinely linked contracts would misallocate the transaction price across them.",
        trains: "Confirming a correct combination assessment and leaving it." },
      { area: "Usage overage", verdict: "flag", severity: "minor",
        output: "Estimated usage-overage fees for the year are recognized upfront at the contract's start.",
        why: "Premature. Usage-based fees are variable consideration recognized as the usage occurs — not estimated and booked on day one. Small here, but it's revenue pulled forward.",
        cost: "A slice of revenue recognized before it's earned, reversing if usage comes in lower — avoidable noise in the numbers.",
        trains: "Holding variable, usage-based fees until the usage happens." },
      { area: "Implementation costs", verdict: "ship",
        output: "Incremental costs of obtaining the contract (a sales commission) are capitalized and amortized over the contract term.",
        why: "Correct under ASC 340-40. Incremental costs of obtaining a contract are capitalized and amortized over the period of benefit — properly applied.",
        cost: "Expensing them immediately would mismatch the cost against the revenue it helped earn.",
        trains: "Letting a correct cost-capitalization treatment stand." },
    ],
    lesson: "The upfront subscription and the setup fee were the two that would have been yours to answer for. Revenue timing is where the quarter's pressure meets the standard — and the standard is what you'll be held to.",
  },
};
