/* People & HR — a Judgment Gym lane. The AI drafts the job description, the
   policy, the write-up; you sign off only what's fair, compliant, and evidenced.
   HR errors reach real people and real regulators fast — a coded line in a JD, a
   misstated leave entitlement, a one-sided investigation. Same shape as every
   other lane (see lib/gym.ts). All items tagged mode + failure pattern. */

import type { Scenario } from "@/lib/gym";

export const HR_SCENARIOS: Record<string, Scenario> = {
  "hr-jd-screen": {
    slug: "hr-jd-screen", career: "People & HR", kind: "document",
    short: "Sign off an AI-drafted job posting and candidate shortlist — discriminatory language, biased screens, and the offer math.",
    client: "Brightpath Logistics — “Operations Coordinator” hire",
    artifact: "Ops_Coordinator_Posting_and_Shortlist.docx",
    thesis: "The AI wrote the job posting, built the application form, and screened the applicants down to a shortlist — polished and ready to publish. A posting is a public record and a screen is a legal one. Sign off only what's fair and lawful.",
    role: "You publish this and approve the shortlist — the posting is public and the screen is discoverable.",
    aiDid: "AI drafted the posting from the hiring manager's notes, wrote the application questions, and ranked the applicants into a shortlist. It reads clean and confident; some of it is a legal risk.",
    brief: [
      { l: "Role", v: "Operations Coordinator, on-site, salaried" },
      { l: "Comp", v: "Posted band $72,000–$84,000; annual base offered $90,000/yr" },
      { l: "Watch", v: "The posting language, the application questions, and the screen" },
      { l: "Rule", v: "Everything must be job-related and compliant with EEO law" },
    ],
    items: [
      { area: "Posting language", verdict: "flag", severity: "critical", mode: "judgment", pattern: "overreach",
        output: "“We're after a young, energetic digital native — recent grads encouraged — to join our high-energy team.”",
        why: "Age-coded language. “Young,” “digital native,” and “recent grads” signal an age preference that runs straight into the ADEA. None of it is a job-related requirement — it's a preference the law forbids you to state.",
        cost: "A public posting that's on its face evidence of age discrimination. One rejected older applicant and this line is the exhibit — a charge, a settlement, and a posting you can never un-publish.",
        trains: "Reading a posting for the coded preference the AI wrote to sound lively, not for whether it's a lawful requirement." },
      { area: "Application questions", verdict: "flag", severity: "major", mode: "fact", pattern: "stale",
        output: "The form asks each applicant for their “current and previous salary” and their “date of birth.”",
        why: "Both are the wrong questions now. Salary-history questions are banned in a growing list of states and undercut pay equity, and asking date of birth up front invites an age-discrimination claim. Standard a decade ago, non-compliant today.",
        cost: "A pay-equity and age-discrimination exposure baked into every application, plus a violation where salary-history bans apply — collected in writing, on file, and easy for a regulator to find.",
        trains: "Catching the once-standard screening question that the law has since moved past." },
      { area: "Resume screen", verdict: "flag", severity: "critical", mode: "judgment", pattern: "overreach",
        output: "“Auto-rejected every applicant with an employment gap longer than six months.”",
        why: "A neutral-looking rule with a discriminatory effect. Employment gaps track caregiving, medical leave, and disability — screening them out lands hardest on protected groups (disparate impact on sex and disability) and isn't job-related.",
        cost: "A screen that filters out protected applicants at scale, applied to the whole pool. It's the pattern class-action plaintiffs and the EEOC look for — and it rejected people you'll never know you lost.",
        trains: "Spotting the neutral-sounding filter that encodes bias, not just the openly biased one." },
      { area: "Offer letter — base pay", verdict: "flag", severity: "major", mode: "fact", pattern: "miscalc",
        output: "“Annual base $90,000, paid as $8,500 gross per month.”",
        why: "The math doesn't tie. $90,000 a year is $7,500 a month, not $8,500 — and $90,000 is also above the posted $72k–$84k band, a separate red flag. The monthly figure overstates the salary by $12,000 a year.",
        cost: "An offer that promises $12k/year more than the stated salary. Whatever the letter says is what the candidate holds you to — and correcting it after they accept is the worst possible first impression.",
        trains: "Re-performing the pay figures on an offer, and checking they sit inside the posted band." },
      { area: "EEO statement", verdict: "ship", mode: "judgment",
        output: "“We're an equal-opportunity employer and consider all applicants without regard to race, color, religion, sex, national origin, age, disability, or genetic information.”",
        why: "Correct and complete. It names the federally protected categories accurately — exactly the statement a compliant posting should carry.",
        cost: "Rewriting a correct EEO statement wastes time and risks dropping a protected class from an otherwise-complete list.",
        trains: "Recognizing a compliant EEO statement and letting it stand." },
      { area: "Stated requirement", verdict: "ship", mode: "fact",
        output: "“Requires a valid driver's license and a clean driving record” — the role includes daily site-to-site driving.",
        why: "Job-related and defensible. The role actually involves driving, so a license and driving record are a bona fide requirement — not a proxy for anything protected.",
        cost: "Striking a genuine, job-related requirement would leave you unable to screen for something the job actually needs.",
        trains: "Telling a legitimate job requirement apart from a screen that only looks like one." },
    ],
    lesson: "The age-coded posting and the employment-gap filter were the two that would have been yours to answer for. AI writes a lively posting and a tidy shortlist in seconds — but the posting is public and the screen is discoverable, and a coded line is a legal record with your name on it.",
  },

  "hr-policy-review": {
    slug: "hr-policy-review", career: "People & HR", kind: "document",
    short: "Sign off an AI-drafted handbook section before it ships to every employee — leave law, exempt status, and the NLRA.",
    client: "Meridian Retail Group — employee handbook update",
    artifact: "Meridian_Handbook_LeaveAndConduct.docx",
    thesis: "The AI drafted the new handbook section — leave entitlements, pay rules, conduct standards, all confidently stated. A handbook is what every manager will apply and what a plaintiff's lawyer will quote back to you. Sign off only what the law supports.",
    role: "You approve this — it goes to every employee and becomes the standard you're held to.",
    aiDid: "AI wrote the policy from a prompt and a pile of prior handbooks. It's clear, well-organized, and states the rules with total confidence. Some of the rules are simply wrong.",
    brief: [
      { l: "Employer", v: "Multi-state, ~600 employees (FMLA-covered)" },
      { l: "Section", v: "Family & medical leave, pay, and workplace conduct" },
      { l: "Watch", v: "Leave entitlements, exempt status, and speech rules" },
      { l: "Rule", v: "Every stated entitlement must match current employment law" },
    ],
    items: [
      { area: "Family & medical leave", verdict: "flag", severity: "critical", mode: "fact", pattern: "fabrication",
        output: "“Eligible employees are entitled to up to 8 weeks of unpaid, job-protected family and medical leave per year.”",
        why: "Wrong entitlement. The FMLA provides up to 12 weeks, not 8. A confident, specific number that simply misstates the federal floor — the kind of error that reads exactly like the correct rules around it.",
        cost: "Deny an employee weeks 9–12 based on this handbook and you've committed an FMLA interference violation, in writing, as company policy. It's a lawsuit the document itself hands the plaintiff.",
        trains: "Checking a stated entitlement against the actual statute, not trusting a confident number." },
      { area: "Overtime & exempt status", verdict: "flag", severity: "major", mode: "fact", pattern: "fabrication",
        output: "“All salaried employees are classified as exempt and are not eligible for overtime.”",
        why: "A common and costly myth. Exempt status under the FLSA turns on the salary level and the actual duties — being paid a salary alone doesn't make someone exempt. Some salaried staff are non-exempt and owed overtime.",
        cost: "Systematic misclassification across the salaried population — unpaid overtime, liquidated (double) damages, and back pay. A wage-and-hour finding that scales with headcount.",
        trains: "Testing an exemption against the duties-and-salary tests, not the “salaried means exempt” shorthand." },
      { area: "Conduct — pay discussions", verdict: "flag", severity: "major", mode: "judgment", pattern: "overreach",
        output: "“Employees may not discuss their wages, benefits, or working conditions with coworkers.”",
        why: "Unlawful restriction. Talking with coworkers about pay and working conditions is protected concerted activity under Section 7 of the NLRA — a blanket rule against it is itself a violation, even at a non-union employer.",
        cost: "An unfair-labor-practice charge and an unenforceable rule that chills protected activity. The policy meant to keep order is the one that draws the NLRB.",
        trains: "Catching the conduct rule that oversteps into legally protected employee speech." },
      { area: "PTO forfeiture", verdict: "flag", severity: "minor", mode: "fact", pattern: "stale",
        output: "“Any accrued, unused PTO is forfeited upon separation and will not be paid out.”",
        why: "Wrong in several of the states this employer operates in. Accrued PTO is treated as earned wages in states like California, and a blanket “use it or lose it / no payout” rule is unlawful there. A one-size policy can't be stated as an absolute.",
        cost: "Unpaid final-wage claims in the states that treat PTO as wages — waiting-time penalties on top, per employee, every separation handled this way.",
        trains: "Spotting the absolute rule that can't hold across every state the employer touches." },
      { area: "At-will statement", verdict: "ship", mode: "judgment",
        output: "“Employment is at-will; either you or the company may end the relationship at any time, with or without cause or notice, subject to applicable law.”",
        why: "Correctly stated. A standard at-will clause with the “subject to applicable law” qualifier — accurate and appropriately caveated.",
        cost: "Reworking a sound at-will clause risks introducing a promise of continued employment that undercuts the at-will status.",
        trains: "Recognizing a correctly-drafted standard clause and leaving it." },
      { area: "Reasonable accommodation", verdict: "ship", mode: "fact",
        output: "“The company provides reasonable accommodations for qualified individuals with disabilities and for religious beliefs, absent undue hardship.”",
        why: "Accurate. It states the ADA and Title VII accommodation duties correctly, with the undue-hardship limit — exactly right.",
        cost: "Diluting a correct accommodation statement would understate a duty the company actually owes.",
        trains: "Confirming a policy that states the law correctly and moving on." },
    ],
    lesson: "The 8-week FMLA figure and the ban on pay discussions were the two that would have been yours to answer for. AI drafts a clean, confident handbook in minutes — but every manager applies it and every plaintiff quotes it, and a wrong rule becomes company policy the moment you sign.",
  },

  "hr-investigation": {
    slug: "hr-investigation", career: "People & HR", kind: "memo",
    short: "Sign off an AI-drafted performance write-up and investigation summary before HR acts on it — documentation, both sides, and retaliation risk.",
    client: "Cedar & Vale — performance and conduct file",
    artifact: "Employee_WriteUp_and_Investigation.memo",
    thesis: "The AI drafted the write-up recommending termination and the summary of the harassment complaint — organized, decisive, ready to action. A termination file is what a jury reads. Sign off only what's documented, even-handed, and defensible.",
    role: "You approve this before HR acts — this file is what gets read in a wrongful-termination claim.",
    aiDid: "AI turned the manager's messages and notes into a formal write-up and an investigation summary. It's articulate and confident; the judgment underneath it is where the risk sits.",
    brief: [
      { l: "Situation", v: "A manager wants an employee terminated; a separate harassment complaint is open" },
      { l: "Watch", v: "Whether it's documented, both sides heard, and the timing" },
      { l: "Rule", v: "Conclusions need specific, dated evidence; both sides get heard" },
      { l: "Your seat", v: "HR acts on the file you sign — and so does a court, later" },
    ],
    items: [
      { area: "Performance write-up", verdict: "flag", severity: "critical", mode: "judgment", pattern: "fabrication",
        output: "“Employee has a bad attitude and isn't a culture fit. Recommend immediate termination.”",
        why: "A conclusion with nothing under it. No specific incidents, no dates, no policy cited, no prior warning — and “culture fit” is exactly the vague, subjective language that masks discrimination and gets torn apart in court. It's a verdict dressed as documentation.",
        cost: "A termination built on “attitude” and “fit” is a wrongful-termination and discrimination claim waiting to happen — there's no defensible record, so the company can't show why this person was let go.",
        trains: "Refusing to let a confident conclusion substitute for specific, dated, documented facts." },
      { area: "Investigation summary", verdict: "flag", severity: "critical", mode: "judgment", pattern: "unverified",
        output: "“Findings are based on the manager's account. The complaint is not substantiated. Case closed.”",
        why: "One side only. The summary reaches a finding on the accusing manager's version alone — the employee who was accused was never interviewed, and neither were the witnesses. A finding without the other side isn't an investigation, it's a rubber stamp.",
        cost: "A closed case that collapses the moment the uninterviewed employee tells their side — no impartial process, so the finding is worthless and the company's failure to investigate is now its own liability.",
        trains: "Professional skepticism — refusing to accept one side's account as the finding before the other side is heard." },
      { area: "Timing & context", verdict: "flag", severity: "major", mode: "judgment", pattern: "omission",
        output: "The write-up is dated two weeks after the employee filed an HR complaint; the summary doesn't mention the complaint at all.",
        why: "A material omission. A move to terminate right after a protected complaint is a textbook retaliation pattern — and the file stays silent on the sequence. Whether or not it's retaliation, leaving the timing off the page is the omission that looks worst later.",
        cost: "A retaliation claim with the calendar as its best evidence, and a file that hid the one fact that mattered. Silence on the timing reads as concealment.",
        trains: "Surfacing the protected-activity timing the summary left out — the omission you only catch if you know to look for it." },
      { area: "Consistency of discipline", verdict: "flag", severity: "major", mode: "judgment", pattern: "overreach",
        output: "Recommends termination for a first documented incident; the file notes two other employees kept their jobs after the same conduct.",
        why: "Disparate treatment. Jumping to termination for a first offense that others survived isn't consistent discipline — treating this employee more harshly for the same conduct is the disparate-treatment case, especially if they're in a protected class.",
        cost: "A discrimination claim the company's own file proves: same conduct, different outcome. Inconsistent discipline is one of the easiest patterns for a plaintiff to establish.",
        trains: "Checking a proposed penalty against how the same conduct was actually handled before." },
      { area: "Documented incidents", verdict: "ship", mode: "fact",
        output: "Logs three specific incidents with dates, times, the policy breached, and the employee's signed acknowledgment of each.",
        why: "Sound documentation. Specific, dated, tied to a written policy, and acknowledged by the employee — this is what a defensible record actually looks like.",
        cost: "Second-guessing well-documented incidents wastes time and signals you can't tell a real record from an empty one.",
        trains: "Recognizing a properly documented incident log and letting it stand." },
      { area: "Recommended process", verdict: "ship", mode: "judgment",
        output: "Proposes a written warning and a 30-day performance improvement plan with measurable goals before any termination decision.",
        why: "The right process. Progressive discipline with a documented PIP and objective goals gives the employee a real chance to improve and the company a defensible record either way.",
        cost: "Skipping a sound PIP step to move faster is exactly how a termination becomes indefensible.",
        trains: "Valuing the fair, documented process step and keeping it." },
    ],
    lesson: "The “culture fit” write-up and the one-sided investigation were the two that would have been yours to answer for. AI turns a manager's notes into a decisive-looking file in seconds — but the file is what a jury reads, and a conclusion with no evidence, or a finding with one side missing, is the company's liability, not the employee's.",
  },
};
