/* Marketing — the second career built 12 reps deep.
   The AI drafts the campaign, the copy, the report; you own what ships. Each rep
   is a real deliverable a marketer produces, seeded with buried, checkable errors
   — off-brief targeting, a hallucinated stat, an FTC landmine, a metric that
   flatters — and genuine good work to leave alone. US market: FTC, CAN-SPAM,
   endorsement guides, special ad categories. Same shape as every lane — see lib/gym.ts. */

import type { Scenario } from "@/lib/gym";

export const MARKETING_SCENARIOS: Record<string, Scenario> = {
  marketing: {
    slug: "marketing", career: "Marketing",
    short: "Judge an AI-built paid campaign against the brief — targeting, budget, claims, creative.",
    client: "FreshBowl — healthy meal delivery",
    artifact: "FreshBowl_Launch_Campaign.draft",
    thesis: "The AI has built a paid campaign to your brief — polished, confident, complete. Some of it is subtly wrong. Catch what doesn't hold, at speed, and ship only what's right.",
    brief: [
      { l: "Launch", v: "New high-protein range · 30g protein/bowl · from $7.99" },
      { l: "Audience", v: "Budget-conscious young professionals, ~25–35" },
      { l: "Budget", v: "$8,000 over 30 days" },
      { l: "Goal", v: "Free-trial signups" },
      { l: "Brand tone", v: "Upbeat, encouraging — no guilt" },
    ],
    items: [
      { area: "Audience targeting", verdict: "flag", severity: "major",
        output: "Adults 18–65 · Income: top 15% ($70k+) · Interests: fitness, wellness, meal kits · IG + TikTok feeds",
        why: "It contradicts the brief. You wanted budget-conscious professionals aged ~25–35 — this targets high earners ($70k+) across an 18–65 span. Finished-looking spec, pointed at the wrong people.",
        cost: "$8,000 spent reaching high earners who don't want budget meals. The campaign under-delivers and the client asks what they're paying you for.",
        trains: "Cross-checking AI output against the brief — reading for correctness, not polish." },
      { area: "Headline copy", verdict: "ship",
        output: "“30g of protein. Zero hassle. New high-protein bowls, from $7.99.”",
        why: "This one is right. 30g matches, $7.99 matches, tone is on-brief. The specific price looks like somewhere AI would hallucinate — but it checks out.",
        cost: "Flagging good work sends it back for no reason — a delay, and a hit to trust when you cry wolf.",
        trains: "Proportionate scrutiny — not flagging good work just because it could have been wrong." },
      { area: "Budget allocation", verdict: "flag", severity: "minor",
        output: "$8,000 / 30 days — Instagram 70% ($5,400) · TikTok 30% ($2,400)",
        why: "The math doesn't add up. 70% of $8,000 is $5,600, not $5,400 — and $5,400 + $2,400 = $7,800, leaving $200 unspent. Official-looking numbers you have to re-add.",
        cost: "$200 of the client's budget quietly goes unspent and your reported split is wrong. Small — but it's the sloppiness that erodes trust one detail at a time.",
        trains: "Re-doing the numbers the machine hands you — beating the lull of official-looking figures." },
      { area: "Creative concept", verdict: "ship",
        output: "Hero: 15-sec vertical — a commuter swaps a sad desk sandwich for a FreshBowl. End card: “Real food, real fast.”",
        why: "Solid. On-brief for time-poor young professionals, upbeat, no guilt. Nothing to flag.",
        cost: "Over-flagging good creative stalls the work and trains the team to route around you.",
        trains: "Recognizing genuinely good work — and having the confidence to let it through." },
      { area: "Primary ad text", verdict: "flag", severity: "critical",
        output: "Opens with: “The healthiest meal you'll eat all week — guaranteed.”",
        why: "A regulatory landmine. An unsubstantiated absolute health claim plus “guaranteed” is exactly the kind of line the FTC pulls under truth-in-advertising — you can't back it up.",
        cost: "An FTC complaint and a claim you can't substantiate. The ad is pulled, the brand takes a public hit, and it traces straight back to your sign-off — no one else's.",
        trains: "Domain scrutiny — spotting the claim that quietly becomes your legal accountability." },
      { area: "Call to action", verdict: "ship",
        output: "CTA button: “Start my free trial” → freshbowl.com/protein-trial",
        why: "On the money. Matches the goal (trial signups) and points to a sensible landing page.",
        cost: "Sending a correct CTA back for review just burns time you don't have.",
        trains: "Confirming the fundamentals are right — fast — and moving on." },
    ],
    lesson: "The wrong audience and the “guaranteed” claim were the two that would have been yours to answer for. Judging fast and right is the operator's edge — the machine drafts, you own the call.",
  },

  "marketing-email": {
    slug: "marketing-email", career: "Marketing",
    short: "Sign off an AI-drafted win-back email to lapsed customers — offer, list, and claims.",
    client: "FreshBowl — lapsed-customer win-back",
    artifact: "FreshBowl_Winback_Email.draft",
    thesis: "The AI has drafted a re-engagement email to customers who've drifted — warm, on-brand, ready to send. Some of it will cost you if it goes out. Ship only what's right.",
    brief: [
      { l: "Audience", v: "Customers with no order in 90+ days" },
      { l: "Offer", v: "20% off the next order, one use per customer" },
      { l: "Goal", v: "Win-back orders — not unsubscribes" },
      { l: "Tone", v: "Warm, we-miss-you — never guilt-trippy" },
      { l: "Rule", v: "Marketing consent required; honor suppressions" },
    ],
    items: [
      { area: "Subject line", verdict: "ship",
        output: "“We saved your spot 🥗 — 20% off your next FreshBowl”",
        why: "On-brief. Warm, names the offer, no guilt. A clean subject line.",
        cost: "Rewriting a good subject line delays the send for nothing.",
        trains: "Recognizing on-brand copy and letting it go." },
      { area: "Discount code setup", verdict: "flag", severity: "critical",
        output: "Code WELCOME20 — 20% off, stackable with active promotions, no minimum, unlimited uses.",
        why: "It contradicts the brief and the margin. “One use per customer” became unlimited and stackable — on top of live promos with no minimum. A margin bomb dressed as a win-back.",
        cost: "A discount that stacks and repeats with no floor — resold, shared, and combined with other offers. The campaign loses money on every order and finance traces it to this send.",
        trains: "Checking the offer mechanics against the brief, not just the headline number." },
      { area: "Send list", verdict: "flag", severity: "major",
        output: "Recipients: all 12,400 lapsed contacts, including 380 who previously unsubscribed.",
        why: "It includes unsubscribed contacts. Mailing people who opted out is a CAN-SPAM violation — and it tanks your deliverability with spam complaints.",
        cost: "A CAN-SPAM breach (penalties are per email) and a deliverability hit that pushes your whole domain toward the spam folder. One of the most expensive mistakes in email.",
        trains: "Catching the suppression the machine quietly ignored." },
      { area: "Preheader", verdict: "ship",
        output: "“It's been a while — here's a little something to come back to.”",
        why: "Warm, on-tone, complements the subject. Nothing to flag.",
        cost: "Over-editing good supporting copy just adds cycles.",
        trains: "Proportionate scrutiny on the small stuff." },
      { area: "Body claim", verdict: "flag", severity: "minor",
        output: "“The best deal we've ever offered — you won't see 20% off again.”",
        why: "An unsubstantiated scarcity claim. You run 20% offers regularly; “you won't see it again” isn't true and erodes trust when the next one lands.",
        cost: "A small credibility leak — customers notice when “last chance” keeps coming back, and your future urgency stops working.",
        trains: "Spotting the claim that's technically false and quietly costs trust." },
      { area: "CTA & link", verdict: "ship",
        output: "Button “Reorder my favorite” → freshbowl.com/reorder",
        why: "Matches the goal and points to a sensible page. On the money.",
        cost: "Sending a correct CTA back burns time you don't have.",
        trains: "Confirming the fundamentals fast and moving on." },
    ],
    lesson: "The stackable code and the unsubscribed contacts were the two that would have been yours to answer for. The AI writes the email in seconds — you're the one who catches what it costs.",
  },

  "mkt-seo-article": {
    slug: "mkt-seo-article", career: "Marketing",
    short: "Sign off an AI-written SEO article — sourced facts, original copy, on-page basics.",
    client: "LedgerLine — “small business bookkeeping” blog post",
    artifact: "LedgerLine_SEO_Post.draft",
    thesis: "The AI has written a ranking-ready article — confident stats, tidy structure, a meta description. Some of it is invented or lifted. Publish only what's true and yours.",
    brief: [
      { l: "Target", v: "Rank for “small business bookkeeping tips”" },
      { l: "Bar", v: "Every stat sourced; copy original; helpful, not thin" },
      { l: "Watch", v: "AI loves a confident number with no citation" },
    ],
    items: [
      { area: "Opening statistic", verdict: "flag", severity: "critical",
        output: "“82% of small businesses that fail cite poor bookkeeping as the primary cause (SBA, 2024).”",
        why: "A fabricated stat with a fake citation. That precise figure attributed to the SBA doesn't exist — it's the confident, sourced-looking number AI invents. The citation makes it more dangerous, not less.",
        cost: "A made-up fact published under the brand's name. When a reader or journalist checks the SBA and finds nothing, the brand's credibility — and its rankings under helpful-content rules — take the hit.",
        trains: "Verifying the AI's confident, cited statistic against the actual source before it goes out." },
      { area: "How-to section", verdict: "ship",
        output: "A five-step reconcile-your-accounts walkthrough, accurate and genuinely useful for the target reader.",
        why: "Good. Accurate, on-topic, and actually helpful — the kind of substantive content that earns the ranking honestly.",
        cost: "Rewriting genuinely useful, correct content just delays a good post.",
        trains: "Recognizing substantive, correct content and letting it stand." },
      { area: "Competitor passage", verdict: "flag", severity: "major",
        output: "A three-sentence definition lifted nearly verbatim from a competitor's ranking article.",
        why: "Near-duplicate content. The passage is copied close enough to be plagiarism — a legal and SEO problem. AI reproduces its training material; this reads straight off a competitor's page.",
        cost: "A duplicate-content and copyright exposure, and search engines discount lifted passages. The brand looks like it can't write its own material.",
        trains: "Catching the passage the machine copied rather than composed." },
      { area: "Meta description", verdict: "ship",
        output: "A 155-character description with the target phrase near the front and a clear benefit.",
        why: "Right. Correct length, keyword placed naturally, benefit-led — solid on-page work.",
        cost: "Nit-picking a correct meta description adds cycles for nothing.",
        trains: "Confirming the on-page basics are right and moving on." },
      { area: "Internal linking", verdict: "flag", severity: "minor",
        output: "The post links three times to the same “pricing” page using the exact phrase “best bookkeeping software.”",
        why: "Over-optimized anchor text. Three identical exact-match links to a commercial page reads as manipulation, not help — and it cannibalizes the anchor. Small, but it's the kind of thing that ages badly.",
        cost: "A pattern that looks like link manipulation to a search engine and adds no value for the reader — a slow drag on the page's standing.",
        trains: "Spotting the over-optimization that helps no one and can quietly hurt." },
      { area: "Heading structure", verdict: "ship",
        output: "A single H1, descriptive H2s per section, target phrase used naturally in one subhead.",
        why: "Clean structure — one H1, logical H2s, no keyword stuffing. Fine as is.",
        cost: "Reworking a correct heading hierarchy is busywork.",
        trains: "Letting sound on-page structure stand." },
    ],
    lesson: "The invented SBA stat and the lifted competitor passage were the two that would have been yours to answer for. AI writes fluent, confident, sourced-looking prose — verifying it is the job the fluency hides.",
  },

  "mkt-landing-page": {
    slug: "mkt-landing-page", career: "Marketing",
    short: "Sign off an AI-built landing page — message match, honest proof, accessible, converting.",
    client: "PeakFit — app free-trial landing page",
    artifact: "PeakFit_LP.draft",
    thesis: "The AI has built the landing page the paid traffic lands on — headline, proof, a signup form. Some of it breaks the promise the ad made or invents its proof. Publish only what holds.",
    brief: [
      { l: "Traffic", v: "From an ad promising “a workout plan in 60 seconds”" },
      { l: "Goal", v: "Free-trial signups" },
      { l: "Bar", v: "Message match; claims real; accessible" },
    ],
    items: [
      { area: "Message match", verdict: "flag", severity: "major",
        output: "The ad promises “a workout plan in 60 seconds”; the landing page headline leads with “The all-in-one wellness platform for your whole life.”",
        why: "A broken promise. The click came for a 60-second workout plan and lands on a generic platform pitch — the scent is lost. Message mismatch is the quiet conversion-killer AI wrote right into the fold.",
        cost: "Paid clicks bounce because the page doesn't deliver what the ad sold — you pay for the traffic and lose it at the headline.",
        trains: "Checking the page keeps the exact promise the ad made." },
      { area: "Testimonial", verdict: "flag", severity: "critical",
        output: "A quote card: “I lost 30 lbs in a month! — Sarah T., verified user,” with a stock headshot and no source.",
        why: "A fabricated, non-typical testimonial. AI-invented “verified” quotes with a stock photo are false, and “30 lbs in a month” is an atypical result presented as normal — an FTC endorsement and substantiation violation on both counts.",
        cost: "A made-up endorsement and an unsubstantiated results claim under the brand's name — squarely in FTC enforcement territory, and it collapses trust the moment anyone looks.",
        trains: "Catching the invented testimonial and the non-typical result stated as normal." },
      { area: "Hero CTA", verdict: "ship",
        output: "A single clear primary button: “Start my free trial” above the fold, repeated once lower down.",
        why: "Right. One clear primary action, placed where it should be and repeated sensibly — good conversion hygiene.",
        cost: "Reworking a clean CTA layout just delays a good page.",
        trains: "Recognizing sound conversion structure and keeping it." },
      { area: "Superlative claim", verdict: "flag", severity: "minor",
        output: "A subhead reads “The #1 fitness app in the world.”",
        why: "An unsupported superlative. “#1 in the world” with no ranking or source behind it is an unsubstantiated claim — easy to challenge, and it cheapens the page. Minor, but it needs proof or needs cutting.",
        cost: "A claim you'd have to back if challenged, and a line savvy visitors discount on sight.",
        trains: "Spotting the superlative that needs a citation or a cut." },
      { area: "Accessibility", verdict: "flag", severity: "minor",
        output: "The hero sets light-gray body text on a white background and images ship with empty alt attributes.",
        why: "An accessibility gap. Low-contrast text fails WCAG contrast and empty alt text shuts out screen readers — the page excludes real users and invites an accessibility complaint. Small fixes, real exclusion.",
        cost: "Visitors who can't read the page (and don't convert), plus ADA/accessibility exposure that's entirely avoidable.",
        trains: "Catching the contrast and alt-text gaps that quietly exclude users." },
      { area: "Signup form", verdict: "ship",
        output: "The form asks only for email to start the trial, with a clear privacy link beside it.",
        why: "Right. Minimal friction — email only — with a visible privacy link. Exactly what a trial signup form should be.",
        cost: "Adding fields to a lean, converting form would only cost signups.",
        trains: "Letting a low-friction, transparent form stand." },
    ],
    lesson: "The broken message match and the fabricated testimonial were the two that would have been yours to answer for. The machine builds a page that looks ready — keeping the ad's promise and the proof honest is the human call.",
  },

  "mkt-search-ads": {
    slug: "mkt-search-ads", career: "Marketing",
    short: "Sign off an AI-built search campaign — trademark risk, match types, policy, budget control.",
    client: "Nomad Luggage — Google Search launch",
    artifact: "Nomad_Search_Campaign.draft",
    thesis: "The AI has built the search campaign — keywords chosen, ad copy written, budget set. Some of it breaks platform policy or burns money. Launch only what's safe and controlled.",
    brief: [
      { l: "Goal", v: "Drive purchases of a new carry-on line" },
      { l: "Budget", v: "$100/day, tightly controlled" },
      { l: "Bar", v: "No policy violations; spend goes to intent, not waste" },
    ],
    items: [
      { area: "Ad copy — competitor name", verdict: "flag", severity: "critical",
        output: "Headline: “Better than Away® — Nomad Carry-On, $195.”",
        why: "Trademark infringement in ad text. Using a competitor's trademarked brand name in your ad copy is a policy violation and a legal exposure — bidding on the term is one thing, naming them in the creative is another.",
        cost: "Ad disapproval, a possible trademark complaint, and the competitor's legal team with a clean case. The brand's account standing is on the line.",
        trains: "Catching the competitor trademark the machine dropped into the creative." },
      { area: "Match type", verdict: "flag", severity: "major",
        output: "All keywords set to broad match, including single generic terms like “bags” and “travel.”",
        why: "A budget leak. Broad match on generic single words will show the ad against wildly irrelevant searches — “bags under eyes,” “travel jobs.” On $100/day it drains fast on non-buyers.",
        cost: "Most of the daily budget spent on searches with no purchase intent — the campaign looks active but buys nothing.",
        trains: "Reading match types for the spend they'll waste, not just the reach they promise." },
      { area: "Negative keywords", verdict: "ship",
        output: "Adds negatives: “free,” “repair,” “used,” “jobs,” “cheap knockoff.”",
        why: "Good hygiene. A sensible negative list that keeps the budget off low-intent and off-brand searches. Exactly right for a controlled launch.",
        cost: "Stripping a sound negative list would reopen the budget leak you're trying to close.",
        trains: "Recognizing sound spend control and keeping it." },
      { area: "Ad copy — superlative", verdict: "flag", severity: "minor",
        output: "Description: “The #1 carry-on in the world.”",
        why: "An unsupported superlative. “#1 in the world” with nothing behind it can be disapproved under ad policy and challenged as an unsubstantiated claim. Small, but it's an easy disapproval.",
        cost: "Ad disapproval that stalls the launch, and a claim you'd have to substantiate if pushed. Avoidable friction.",
        trains: "Spotting the superlative that needs proof or needs cutting." },
      { area: "Landing page match", verdict: "ship",
        output: "Carry-on ads point to the carry-on product page, not the homepage.",
        why: "Right. Sending intent-rich clicks to the specific product page, not a generic homepage — good message match and better conversion.",
        cost: "Redirecting correct, specific landing pages to the homepage would cut conversion for no reason.",
        trains: "Confirming the click lands where the intent points." },
      { area: "Conversion tracking", verdict: "ship",
        output: "Purchase conversion action is set up and the campaign optimizes to it, not to clicks.",
        why: "Correct. Optimizing to purchases rather than clicks aligns the spend with the actual goal. Sound setup.",
        cost: "Switching to click-optimization would chase traffic instead of sales.",
        trains: "Letting a correctly-configured goal stand." },
    ],
    lesson: "The competitor name in the copy and the all-broad-match keywords were the two that would have been yours to answer for. The machine builds a campaign in minutes — the policy and the spend discipline are still yours.",
  },

  "mkt-social-calendar": {
    slug: "mkt-social-calendar", career: "Marketing",
    short: "Sign off an AI-built organic social calendar — brand safety, rights, platform fit, cultural read.",
    client: "Ember Coffee Co. — monthly social calendar",
    artifact: "Ember_Social_Calendar.draft",
    thesis: "The AI has drafted a month of posts — captions, hashtags, a posting schedule. Some of it will embarrass the brand or infringe a right. Schedule only what's safe.",
    brief: [
      { l: "Brand", v: "Warm, community-first neighborhood roaster" },
      { l: "Channels", v: "Instagram and LinkedIn" },
      { l: "Bar", v: "On-brand, rights-cleared, culturally aware" },
    ],
    items: [
      { area: "Sensitive-date post", verdict: "flag", severity: "critical",
        output: "A cheerful “Grab 20% off and celebrate!” sale post scheduled for a national day of mourning / remembrance.",
        why: "A tone-deaf collision. A jokey discount push on a solemn remembrance date reads as the brand cashing in on a day of grief — the kind of post that gets screenshotted and spread. AI has no read on the calendar's meaning.",
        cost: "A public backlash and an apology cycle, for a brand whose whole equity is warmth and community. The reputational hit dwarfs any sale.",
        trains: "Reading the cultural calendar the machine is blind to before anything schedules." },
      { area: "Stock imagery", verdict: "flag", severity: "major",
        output: "A hero post uses an image pulled from a web search, credited “via Google.”",
        why: "No usage rights. An image grabbed from search results isn't licensed — “via Google” isn't a license. Using it is copyright infringement waiting for a demand letter.",
        cost: "A copyright claim and a takedown, potentially a settlement — for an image the brand never had the right to use.",
        trains: "Catching the unlicensed asset before it publishes." },
      { area: "Evergreen post", verdict: "ship",
        output: "A behind-the-counter reel of the team roasting, caption about the week's single-origin, on-brand and warm.",
        why: "On-brand and safe. Owned footage, community feel, genuinely the brand's voice. Nothing to flag.",
        cost: "Second-guessing a clearly on-brand, owned-content post just slows the calendar.",
        trains: "Recognizing safe, on-voice content and scheduling it." },
      { area: "Trend/newsjack", verdict: "flag", severity: "minor",
        output: "A post hitching the brand to a currently-viral audio clip whose origin and meaning aren't verified.",
        why: "An unvetted trend. Jumping on a viral sound without knowing what it references is how brands accidentally endorse something ugly. Minor if it's fine — but the point is no one checked.",
        cost: "A best-case shrug and a worst-case association with whatever the trend actually meant. Reward small, downside real.",
        trains: "Pausing on the trend no one has actually vetted." },
      { area: "Platform fit", verdict: "ship",
        output: "The LinkedIn version reworks the caption to a professional tone; the Instagram version stays casual.",
        why: "Right. Tailoring voice and format per platform rather than cross-posting identically — a sign of real craft.",
        cost: "Flattening the two back to one caption would weaken both.",
        trains: "Letting a sound per-platform adaptation stand." },
      { area: "Hashtag set", verdict: "ship",
        output: "A tight set of five relevant, brand- and location-appropriate hashtags per post.",
        why: "Sensible. Relevant, not spammy, locally tuned — appropriate hashtag hygiene.",
        cost: "Reworking a clean hashtag set is busywork.",
        trains: "Confirming the small stuff is fine and moving on." },
    ],
    lesson: "The remembrance-day sale post and the unlicensed image were the two that would have been yours to answer for. The machine fills a calendar in seconds — the brand's judgment about the world is still human.",
  },

  "mkt-influencer": {
    slug: "mkt-influencer", career: "Marketing",
    short: "Sign off an AI-drafted influencer program — FTC disclosure, vetting, projections, terms.",
    client: "GlowWell — skincare creator program",
    artifact: "GlowWell_Influencer_Brief.draft",
    thesis: "The AI has drafted the influencer program — creators picked, briefs written, ROI projected. Some of it breaks FTC rules or skips the vetting. Approve only what's compliant and real.",
    brief: [
      { l: "Program", v: "Paid creators posting about a new serum" },
      { l: "Rule", v: "FTC endorsement guides — disclose the material connection" },
      { l: "Bar", v: "Creators vetted; claims allowed are limited (cosmetic, not drug)" },
    ],
    items: [
      { area: "Disclosure instructions", verdict: "flag", severity: "critical",
        output: "Creator brief says: “Keep it authentic — no need to label it as an ad, just share your honest experience.”",
        why: "A direct FTC violation. Paid endorsements must clearly disclose the material connection (#ad / #sponsored) — telling creators to skip the label is exactly what the endorsement guides prohibit, and the brand is liable for it.",
        cost: "FTC exposure for the advertiser, not just the creator. Undisclosed paid posts are a documented enforcement target — and the instruction is in writing, from you.",
        trains: "Catching the missing #ad disclosure the machine wrote out of the brief." },
      { area: "Claim guardrails", verdict: "flag", severity: "major",
        output: "Talking points invite creators to say the serum “heals damaged skin and repairs it at the cellular level.”",
        why: "A cosmetic making a drug claim. “Heals” and “repairs at the cellular level” are treatment claims that reclassify a cosmetic as an unapproved drug — a regulatory line the brief hands creators to cross.",
        cost: "FDA/FTC exposure and warning-letter territory, multiplied across every creator who repeats it. The claim scales the risk with the reach.",
        trains: "Spotting the drug claim dressed up as a skincare talking point." },
      { area: "Creator vetting", verdict: "flag", severity: "major",
        output: "A shortlisted creator is included on follower count alone; no review of their recent content or past controversies.",
        why: "Unvetted brand risk. Picking on reach without checking recent posts or history is how a brand ends up associated with whatever that creator said last month. AI ranked by numbers, not judgment.",
        cost: "A partnership that blows up when the creator's past resurfaces — the brand's name next to content it never vetted.",
        trains: "Requiring the human vet the algorithm skips." },
      { area: "Contract clause", verdict: "ship",
        output: "The agreement requires disclosure per FTC guidelines, brand approval of posts, and a usage license for repurposing.",
        why: "Solid terms. Disclosure mandated, approval gate, and rights to reuse the content — the clauses a real program needs.",
        cost: "Reworking sound contract terms just delays signing.",
        trains: "Recognizing well-drafted terms and keeping them." },
      { area: "ROI projection", verdict: "flag", severity: "minor",
        output: "Projects a 12× return assuming every follower sees the post and 5% buy.",
        why: "Fantasy math. Organic reach is a fraction of follower count, and 5% conversion from a single post is wildly optimistic — the projection assumes best-case on every variable at once.",
        cost: "A number that sets expectations no program can hit, so a decent result reads as a failure against your own forecast.",
        trains: "Sanity-checking the projection built on stacked best-case assumptions." },
      { area: "Content cadence", verdict: "ship",
        output: "Three posts per creator over six weeks, spaced to avoid audience fatigue.",
        why: "Reasonable. Spaced cadence that sustains presence without burning out the audience — a sound rhythm.",
        cost: "Compressing a sensible cadence would just fatigue the audience.",
        trains: "Letting a sound schedule stand." },
    ],
    lesson: "The “don't label it as an ad” instruction and the cosmetic-as-drug claims were the two that would have been yours to answer for. The machine drafts the program — FTC compliance and creator judgment are the parts it can't hold.",
  },

  "mkt-analytics": {
    slug: "mkt-analytics", career: "Marketing",
    short: "Sign off an AI-built performance report — attribution, real ROI, honest charts.",
    client: "Beacon Software — Q3 marketing report",
    artifact: "Beacon_Q3_Report.draft",
    thesis: "The AI has assembled the quarterly performance report — channels ranked, ROI declared, charts drawn. Leadership will reallocate budget off this. Sign off only what the data actually says.",
    brief: [
      { l: "Audience", v: "Leadership — budget decisions get made from this" },
      { l: "Watch", v: "Attribution, cost metrics, and how the charts are drawn" },
      { l: "Bar", v: "Metrics tie to outcomes, not vanity" },
    ],
    items: [
      { area: "Headline metric", verdict: "flag", severity: "major",
        output: "“Social drove 2.4M impressions this quarter — our best-performing channel.”",
        why: "A vanity metric masquerading as performance. Impressions aren't outcomes — “best-performing” should map to signups or revenue, not eyeballs. The channel with the most impressions may drive the fewest customers.",
        cost: "Budget shifted toward the channel that looks biggest on a metric that doesn't pay — leadership optimizing for impressions instead of customers.",
        trains: "Refusing to let a big vanity number stand in for actual performance." },
      { area: "Attribution", verdict: "flag", severity: "critical",
        output: "Last-click attribution credits paid search with 80% of conversions; brand and content get ~0.",
        why: "A model artifact read as truth. Last-click hands all credit to the final touch — paid search catches people already sold by brand and content, which show ~0 only because they never get the last click. The conclusion is an artifact of the model.",
        cost: "The channels that actually create demand get defunded because a last-click model can't see them — the brand starves its own top of funnel.",
        trains: "Reading what the attribution model can't see before reallocating on it." },
      { area: "Cohort chart", verdict: "ship",
        output: "A retention-by-signup-month cohort chart showing month-3 retention improving across the quarter.",
        why: "Genuinely useful. Cohorts isolate whether newer customers retain better — a real, honest read on product-marketing fit. Good analysis.",
        cost: "Cutting a sound cohort view removes one of the report's few honest signals.",
        trains: "Recognizing analysis that actually informs and keeping it." },
      { area: "CAC calculation", verdict: "flag", severity: "major",
        output: "CAC = ad spend ÷ new customers, excluding the agency retainer and creative costs.",
        why: "Understated by omission. Customer acquisition cost has to include the fully-loaded spend — leaving out the retainer and creative makes CAC look better than it is. A flattering denominator.",
        cost: "A CAC that reads healthy, an LTV:CAC ratio that justifies scaling — until the real, loaded cost shows the unit economics don't work.",
        trains: "Loading the cost metric fully, not just the media line." },
      { area: "Chart axis", verdict: "flag", severity: "minor",
        output: "A revenue bar chart whose y-axis starts at $80k, making a 4% rise look like a doubling.",
        why: "A truncated axis exaggerates the move. Starting the axis at $80k instead of zero turns a modest 4% gain into a visual doubling — technically the data, misleadingly drawn.",
        cost: "Leadership reads a dramatic jump that isn't there and expects a trend the numbers don't support. Small chart choice, distorted decision.",
        trains: "Catching the axis trick that oversells a modest number." },
      { area: "Conversion definition", verdict: "ship",
        output: "“Conversion” is defined once, up front, as a paid subscription — and used consistently throughout.",
        why: "Right. A single, stated definition applied consistently is what makes a report trustworthy. Good discipline.",
        cost: "Second-guessing a clear, consistent definition adds nothing.",
        trains: "Letting sound reporting discipline stand." },
    ],
    lesson: "The last-click attribution and the stripped-down CAC were the two that would have been yours to answer for. The machine assembles the report — not being fooled by the metric is the human edge.",
  },

  "mkt-positioning": {
    slug: "mkt-positioning", career: "Marketing",
    short: "Sign off an AI-drafted positioning & claims doc — comparative claims, brand fit, promises you can keep.",
    client: "Vertex CRM — repositioning brief",
    artifact: "Vertex_Positioning.draft",
    thesis: "The AI has drafted the new positioning — a sharp message, bold claims, a competitor comparison. Some of it you can't stand behind. Sign off only what's true and on-brand.",
    brief: [
      { l: "Product", v: "A mid-market CRM, repositioning up-market" },
      { l: "Brand", v: "Trusted, plain-speaking, no hype" },
      { l: "Bar", v: "Claims substantiated; comparisons defensible" },
    ],
    items: [
      { area: "Comparative claim", verdict: "flag", severity: "critical",
        output: "“3× faster than Salesforce — switch and see.”",
        why: "An unsubstantiated comparative claim naming a competitor. “3× faster than [named competitor]” invites a Lanham Act false-advertising challenge unless you have rigorous, apples-to-apples proof — and the brief has none.",
        cost: "A cease-and-desist or a false-advertising suit from a competitor with deep legal pockets, plus the claim pulled from every asset it touched.",
        trains: "Catching the named-competitor comparison that needs airtight proof or needs cutting." },
      { area: "Capability promise", verdict: "flag", severity: "major",
        output: "“Fully autonomous CRM — it runs your pipeline with zero manual work.”",
        why: "A promise the product can't keep. “Zero manual work / fully autonomous” overstates what the tool does — the gap between the claim and the demo is where trust dies and churn starts.",
        cost: "Prospects sold on autonomy, disappointed on day one — inflated acquisition, brutal churn, and a reputation for overpromising.",
        trains: "Spotting the capability claim the product can't actually deliver." },
      { area: "Core differentiator", verdict: "ship",
        output: "“The CRM your reps actually update — built for the way sales teams really work.”",
        why: "Strong and defensible. It's a genuine, ownable angle that fits the plain-speaking brand and can be demonstrated. Good positioning.",
        cost: "Weakening a sharp, true differentiator would blunt the whole reposition.",
        trains: "Recognizing a genuinely strong, true message and keeping it." },
      { area: "Tone", verdict: "flag", severity: "minor",
        output: "Copy leans on “game-changing, revolutionary, next-gen, disruptive” across the headline set.",
        why: "Off-brand hype. The brand is trusted and plain-speaking; stacked buzzwords are exactly the hype it's meant to avoid. Not illegal — just not this brand.",
        cost: "Positioning that sounds like every other vendor, undercutting the one thing that set the brand apart: that it doesn't talk like that.",
        trains: "Catching the tone drift away from the brand's actual voice." },
      { area: "Proof point", verdict: "ship",
        output: "“98% of customers renew” — backed by an internal retention figure cited in the appendix.",
        why: "A substantiated claim. A specific number with a documented internal source behind it — the kind of proof point positioning should lean on.",
        cost: "Cutting a substantiated proof point removes real credibility.",
        trains: "Letting a claim that's actually backed stand." },
      { area: "Market-size stat", verdict: "flag", severity: "minor",
        output: "“The $50B CRM market is ours to take” — no source for the figure.",
        why: "An unsourced market number. The $50B is stated as fact with nothing behind it — plausible, but uncited, and easy to get wrong. Internal-facing here, but it'll get repeated as gospel.",
        cost: "A figure that propagates into decks and pitches uncited, then turns out wrong — a small credibility crack that spreads.",
        trains: "Sourcing the market stat before it becomes company gospel." },
    ],
    lesson: "The “3× faster than Salesforce” claim and the “zero manual work” promise were the two that would have been yours to answer for. The machine writes bold — standing behind the claim is the part that's yours.",
  },

  "mkt-press-release": {
    slug: "mkt-press-release", career: "Marketing",
    short: "Sign off an AI-drafted press release — verifiable claims, real quotes, timing, the parts a journalist checks.",
    client: "Cirrus Robotics — Series B announcement",
    artifact: "Cirrus_SeriesB_PR.draft",
    thesis: "The AI has drafted the funding announcement — a punchy headline, quotes, a boilerplate. A journalist will fact-check this. Send only what stands up.",
    brief: [
      { l: "News", v: "$40M Series B to expand the robotics platform" },
      { l: "Bar", v: "Every claim verifiable; quotes approved; timing right" },
      { l: "Reader", v: "Tech press — they check first-of claims and numbers" },
    ],
    items: [
      { area: "Superlative claim", verdict: "flag", severity: "critical",
        output: "Headline: “Cirrus builds the world's first fully autonomous warehouse robot.”",
        why: "An unverifiable “world's first.” Several companies ship autonomous warehouse robots — “world's first / fully autonomous” is exactly the claim a tech journalist disproves in one search, and it taints the whole announcement.",
        cost: "A skeptical or debunking story instead of a funding story, plus a competitor's rebuttal. The one line the AI reached for undermines the news it was announcing.",
        trains: "Catching the “first / only” claim a reporter will fact-check in seconds." },
      { area: "Misattributed quote", verdict: "flag", severity: "major",
        output: "A glowing quote is attributed to the lead investor, drafted by the AI and not yet approved by them.",
        why: "A quote the named person never said or approved. Putting words in an investor's mouth in a public release, unapproved, is a trust and legal problem — quotes must be real and signed off.",
        cost: "An investor blindsided by their own “quote,” a correction, and a damaged relationship on the day you most needed them aligned.",
        trains: "Confirming every attributed quote is real and approved before it's public." },
      { area: "Boilerplate", verdict: "ship",
        output: "The company boilerplate states founding year, HQ, and what the platform does, all accurate.",
        why: "Correct and standard. The facts check out and it reads as boilerplate should. Nothing to flag.",
        cost: "Rewriting accurate boilerplate is pure busywork.",
        trains: "Confirming the standard facts are right and moving on." },
      { area: "Forward-looking figure", verdict: "flag", severity: "minor",
        output: "“We'll be profitable within 12 months and triple headcount.”",
        why: "A hard forward-looking promise. Stated as fact rather than aspiration, a specific profitability-and-headcount pledge sets a bar the company may miss publicly — and reporters keep receipts.",
        cost: "A quotable promise that becomes a “they said they'd be profitable” story in 12 months if it slips. Avoidable hostage to fortune.",
        trains: "Softening the hard future promise stated as present fact." },
      { area: "Funding figure", verdict: "ship",
        output: "“$40M Series B led by [named fund]” — matches the signed term sheet and the cap table.",
        why: "Verifiable and correct. The number and lead investor match the documents. Exactly what the release should assert.",
        cost: "Second-guessing a figure that ties to the paperwork wastes time.",
        trains: "Letting an accurate, documented figure stand." },
      { area: "Embargo/timing", verdict: "ship",
        output: "The release is set under embargo until the announced date, with the embargo clearly stated to press.",
        why: "Right. A stated embargo coordinates coverage and protects the timing — standard, correct PR practice.",
        cost: "Dropping the embargo would scatter the coverage.",
        trains: "Recognizing correct release mechanics and keeping them." },
    ],
    lesson: "The “world's first” headline and the unapproved investor quote were the two that would have been yours to answer for. The machine writes a confident release — what a journalist can verify is what you're accountable for.",
  },

  "mkt-display-creative": {
    slug: "mkt-display-creative", career: "Marketing",
    short: "Sign off an AI-built display ad set — targeting law, disclaimers, licensing, honest pricing.",
    client: "HomeFund — mortgage refinance display ads",
    artifact: "HomeFund_Display_Set.draft",
    thesis: "The AI has built the display ad set — audiences, banners, offers. This is a regulated category, and some of the targeting and claims cross a legal line. Ship only what's compliant.",
    brief: [
      { l: "Product", v: "Mortgage refinance — a credit/housing offer" },
      { l: "Rule", v: "Special ad category — restricted targeting applies" },
      { l: "Bar", v: "Rate claims disclosed; assets licensed" },
    ],
    items: [
      { area: "Audience targeting", verdict: "flag", severity: "critical",
        output: "Targets homeowners aged 30–45, excludes certain ZIP codes, narrows by gender.",
        why: "Illegal targeting for a housing/credit ad. Refinance falls under special ad category rules that prohibit targeting or excluding by age, gender, and ZIP-code proxy — the AI applied ordinary targeting to a regulated category.",
        cost: "A fair-lending / discrimination violation — ECOA and Fair Housing exposure, platform account action, and a genuinely harmful ad. One of the most serious lines in advertising.",
        trains: "Recognizing the regulated category the machine targeted like any other." },
      { area: "Rate claim", verdict: "flag", severity: "major",
        output: "Banner reads “Refi at 4.9%” with no APR, terms, or “rates subject to change” disclosure.",
        why: "A lending claim without required disclosure. Advertising a rate without APR and the triggering-terms disclosures breaches truth-in-lending advertising rules — the number alone isn't allowed.",
        cost: "A TILA/Reg Z advertising violation and a rate that misleads on the true cost of the loan. Regulated claims carry regulated disclosures.",
        trains: "Catching the regulated financial claim shipped without its disclosure." },
      { area: "Ad sizing", verdict: "ship",
        output: "The set includes the standard IAB sizes (300×250, 728×90, 160×600) with correct safe zones.",
        why: "Correct. Standard sizes, proper safe zones — clean production work with nothing to flag.",
        cost: "Reworking correctly-sized creative is busywork.",
        trains: "Confirming the production basics and moving on." },
      { area: "Stock asset license", verdict: "flag", severity: "minor",
        output: "A “happy family” hero image is marked “source: stock site — license TBD.”",
        why: "License unconfirmed. “TBD” means the usage rights aren't secured — running it before the license is confirmed risks an infringement claim. Minor to fix now, expensive to ignore.",
        cost: "A licensing demand for an image used without a confirmed right — avoidable entirely by clearing it first.",
        trains: "Clearing the asset license before the ad runs, not after." },
      { area: "Disclaimer", verdict: "ship",
        output: "Includes “Subject to credit approval. Equal Housing Lender.” with the required legal footer.",
        why: "Right. The category's standard legal footer and equal-housing statement are present and correct. Compliant.",
        cost: "Cutting a required disclaimer would create the violation you're checking for.",
        trains: "Recognizing a correct, required disclosure and keeping it." },
      { area: "Price/offer copy", verdict: "ship",
        output: "“No application fee” — matches the current published product terms.",
        why: "Accurate. The offer copy matches the real product terms — a true, checkable claim.",
        cost: "Second-guessing a claim that matches the terms wastes time.",
        trains: "Letting an accurate offer claim stand." },
    ],
    lesson: "The special-category targeting and the undisclosed rate were the two that would have been yours to answer for. In a regulated category the machine's ordinary defaults are the violation — knowing the category is the job.",
  },

  "mkt-lifecycle": {
    slug: "mkt-lifecycle", career: "Marketing",
    short: "Sign off an AI-built lifecycle automation — consent, segment logic, margin, data governance.",
    client: "Trailhead Apparel — lifecycle automation",
    artifact: "Trailhead_Lifecycle_Flows.draft",
    thesis: "The AI has built the lifecycle automation — segments defined, triggers set, offers attached. Some of it breaks consent or double-sends or bleeds margin. Turn on only what's safe.",
    brief: [
      { l: "Goal", v: "Onboarding, replenishment, and win-back flows" },
      { l: "Rule", v: "Marketing consent honored; suppressions respected" },
      { l: "Bar", v: "Segments mutually clean; offers protect margin" },
    ],
    items: [
      { area: "Consent scope", verdict: "flag", severity: "critical",
        output: "The onboarding flow emails everyone who created an account, including those who never opted into marketing.",
        why: "A consent breach. An account signup isn't marketing consent — emailing people who never opted in mails a non-consented list. The AI treated “has an email” as “can be marketed to.”",
        cost: "A CAN-SPAM/consent violation across the whole onboarding flow, spam complaints, and a deliverability hit — the automation breaks the rule on every new signup, silently and at scale.",
        trains: "Separating account creation from marketing consent before a flow turns on." },
      { area: "Segment overlap", verdict: "flag", severity: "major",
        output: "The replenishment and win-back flows both include customers at 60–90 days, with no exclusion between them.",
        why: "Overlapping segments double-send. A customer in both flows gets two competing emails in the same window — the segments aren't mutually exclusive, and the AI didn't set the exclusion.",
        cost: "Customers hit with conflicting messages and doubled frequency — annoyance, unsubscribes, and a muddled experience that no single flow's metrics will explain.",
        trains: "Checking that segments are mutually exclusive, not just individually sensible." },
      { area: "Trigger logic", verdict: "ship",
        output: "The replenishment email fires at 75% of the average consumption cycle for the purchased product.",
        why: "Smart. Timing the reminder to just before the customer runs out, per product cycle — exactly the right trigger for replenishment.",
        cost: "Re-timing a well-designed trigger would only make it worse.",
        trains: "Recognizing sound trigger logic and keeping it." },
      { area: "Win-back offer", verdict: "flag", severity: "minor",
        output: "The win-back flow leads with 40% off for anyone inactive 90+ days, applied automatically.",
        why: "A margin overreach. A blanket 40% to all lapsed customers trains people to lapse on purpose and hands the discount to those who'd have returned anyway. Deep, unconditional, automatic.",
        cost: "Margin given away to customers who didn't need the incentive, and a discount-conditioning habit that erodes full-price behavior over time.",
        trains: "Questioning the deep automatic discount before it becomes the default path back." },
      { area: "Frequency cap", verdict: "ship",
        output: "A global cap limits any contact to three automated emails per week across all flows.",
        why: "Right. A cross-flow frequency cap is exactly the guardrail that stops automations from ganging up on a contact. Good governance.",
        cost: "Removing the cap would reopen the over-mailing risk.",
        trains: "Letting a sound frequency guardrail stand." },
      { area: "Data field use", verdict: "ship",
        output: "Personalization uses first name and last purchased category — no sensitive or inferred-health data.",
        why: "Appropriate. Sticking to volunteered, non-sensitive fields for personalization is the right data-governance line.",
        cost: "Second-guessing appropriate field use adds nothing.",
        trains: "Confirming personalization stays inside safe data and moving on." },
    ],
    lesson: "The non-consented onboarding list and the overlapping double-send were the two that would have been yours to answer for. The machine wires the automation — consent and segment logic are the parts that break quietly and at scale.",
  },
};
