/* Operations & Admin — Judgment Gym lane. The AI drafts the deliverable at speed;
   you sign off only what holds. Purchase orders that don't foot, rosters that
   break a coverage rule, vendor SOWs that over-commit or leave out a key term —
   the errors an ops/admin pro is paid to catch. Same shape as every other lane
   (see lib/gym.ts). US conventions throughout; all items tagged mode + pattern. */

import type { Scenario } from "@/lib/gym";

export const OPS_SCENARIOS: Record<string, Scenario> = {
  "ops-purchase-order": {
    slug: "ops-purchase-order", career: "Operations & Admin", kind: "order",
    short: "Approve an AI-built purchase order before it's sent to the vendor — line math, unit prices, duplicates, and the total.",
    client: "Meridian Office Supply — new-hire equipment PO",
    artifact: "PO-4520.pdf",
    role: "You approve this — the vendor bills against the numbers you send, and the PO is the commitment.",
    aiDid: "AI built the purchase order from the requisition and the vendor's current quote (Q-7788). It's itemized, priced, and totaled — ready to send. Some lines don't foot or don't match the quote.",
    thesis: "The AI built the purchase order — items extended, a discount line, a total at the bottom. A PO is a number the vendor holds you to. Approve only the lines that add up.",
    brief: [
      { l: "Requisition", v: "Desks, monitors and sit-stand converters for a new-hire cohort" },
      { l: "Quote Q-7788", v: "Task chairs $189.00 · 27\" monitors $229.00 · sit-stand converters $145.00" },
      { l: "Watch", v: "The line extensions, the unit prices, duplicates, and the total" },
      { l: "Rule", v: "Every line must foot and match the current quote" },
    ],
    items: [
      { area: "Task chairs — line 1", verdict: "flag", severity: "critical", mode: "fact", pattern: "miscalc",
        output: "24 × $189.00 = $4,356.00",
        why: "The extension is wrong. 24 × $189.00 is $4,536.00, not $4,356.00 — a digit transposition on the anchor line, understating it by $180.",
        cost: "The PO won't match the vendor's invoice, the three-way match breaks, and either the PO gets reworked mid-order or the wrong commitment is recorded.",
        trains: "Re-performing the extension that anchors the PO, not trusting the printed line total." },
      { area: "27\" monitors — line 2", verdict: "ship", mode: "fact",
        output: "18 × $229.00 = $4,122.00",
        why: "Correct. 18 × $229.00 is $4,122.00, and the unit price matches the quote — the line foots and ties to Q-7788.",
        cost: "Re-deriving a line that foots and matches the quote just delays the order.",
        trains: "Confirming a line ties to its source and moving on." },
      { area: "Sit-stand converters — line 3", verdict: "flag", severity: "minor", mode: "fact", pattern: "stale",
        output: "20 × $165.00 = $3,300.00",
        why: "The math foots, but the unit price is stale. The current quote Q-7788 lists converters at $145.00 — the $165.00 is last quarter's price, so every unit is overpriced by $20.",
        cost: "An overpay of $400 on this line, and a rate that won't reconcile to the quote the vendor honors — a small, certain leak that repeats on the next order built the same way.",
        trains: "Checking the unit price against the current quote, not a superseded one — even when the arithmetic is right." },
      { area: "Monitors — line 4", verdict: "flag", severity: "major", mode: "fact", pattern: "unverified",
        output: "27\" monitors: 18 × $229.00 = $4,122.00 — a second, identical line further down the PO.",
        why: "A duplicate. The monitors already appear on line 2; this is the same item, quantity and amount raised straight from the requisition without checking it against what's already on the PO. It would order 36 monitors for an 18-person cohort.",
        cost: "Twice the monitors ordered and paid for — recoverable only if someone notices, and duplicates are built not to be noticed.",
        trains: "Catching the duplicate line the PO presents as just another item." },
      { area: "Order consolidation", verdict: "ship", mode: "judgment",
        output: "Three departmental requisitions are combined into one PO to clear the vendor's volume-discount tier.",
        why: "Sound. Consolidating open requisitions to a single PO hits the vendor's volume tier and cuts the admin overhead — a sensible procurement call.",
        cost: "Splitting a well-consolidated order back out loses the volume pricing and creates more POs to manage.",
        trains: "Recognizing a sound consolidation and letting it stand." },
      { area: "PO total", verdict: "flag", severity: "critical", mode: "fact", pattern: "miscalc",
        output: "Total: $15,480.00",
        why: "The total doesn't foot. The four printed line extensions ($4,356 + $4,122 + $3,300 + $4,122) sum to $15,900.00 — the total is a plug that ties to nothing, even before the line errors above.",
        cost: "You commit to a number that reconciles to none of the lines. Whatever the vendor accepts, you're bound to — and untangling it later is the awkward call that stalls the order.",
        trains: "Re-adding the total against the lines, never trusting the figure at the bottom." },
    ],
    lesson: "The transposed chairs line and the total that didn't foot were the two that would have been yours to answer for. AI builds a clean, itemized PO in seconds — but the vendor holds you to the number you send, and a slip on the anchor line flows all the way to the bottom.",
  },

  "ops-staff-roster": {
    slug: "ops-staff-roster", career: "Operations & Admin", kind: "spreadsheet",
    short: "Sign off an AI-built weekly store roster before it's published — hours, coverage, keyholders, and availability.",
    client: "Lakeside Retail — weekly store schedule",
    artifact: "Lakeside_Roster_Wk32.xlsx",
    role: "You publish this — the store runs on the shifts you sign, and a gap is a shift nobody shows up for.",
    aiDid: "AI built the weekly roster from demand, availability and the time-off requests. Hours are totaled, shifts are assigned, coverage looks filled. Some of it breaks a scheduling rule.",
    thesis: "The AI built the weekly roster — shifts assigned, hours totaled, coverage that looks complete. A roster that reads full can still break a rule. Publish only the shifts that hold.",
    brief: [
      { l: "Store", v: "Open 8am–10pm, seven days; a mix of full- and part-time associates" },
      { l: "Rules", v: "≥2 associates on the floor while open; a keyholder on every opening and closing shift" },
      { l: "Rules", v: "Over 40 hours needs OT pre-approval; honor approved time off and current availability" },
      { l: "Watch", v: "The weekly-hours totals, coverage, keyholders, and stale availability" },
    ],
    items: [
      { area: "Dana — weekly hours", verdict: "flag", severity: "major", mode: "fact", pattern: "miscalc",
        output: "Weekly total: 38.0 hrs  (shifts: Mon–Fri 8.0 + Sat 6.0)",
        why: "The total cell under-counts. The listed shifts sum to 46.0 hours (5 × 8.0 + 6.0), not 38.0 — and 46 hours is a 6-hour overtime week that never got the required pre-approval. The total hides the breach.",
        cost: "Unapproved overtime you're now committed to pay, and a labor-cost overrun that isn't in the number the roster reports.",
        trains: "Re-adding the shift hours against the total cell, not trusting the printed weekly figure." },
      { area: "Saturday 12–4 coverage", verdict: "flag", severity: "critical", mode: "fact", pattern: "omission",
        output: "Saturday midday shows one associate on the floor during open hours.",
        why: "Under the coverage rule. The store must have at least two associates on the floor while open — a single-cover midday block leaves the floor short at a busy time, and it's the gap the roster doesn't surface because the shift cell isn't empty, just thin.",
        cost: "An understaffed floor during peak Saturday traffic — lost sales, a security and safety exposure, and a rule breach on the schedule you signed.",
        trains: "Reading the roster for the coverage minimum on every open hour, not just that each shift has a name in it." },
      { area: "Sunday opening — keyholder", verdict: "flag", severity: "major", mode: "judgment", pattern: "unverified",
        output: "Sunday's 8am open is assigned to Priya, who isn't on the keyholder list.",
        why: "Assumed, not checked. The roster puts an associate on an opening shift without confirming she can actually open — Priya isn't a keyholder, so no one on that shift can unlock, disarm, or handle the drawer.",
        cost: "The store can't open on time Sunday — a scramble to reach a keyholder while customers wait, all because the roster assumed anyone could take the shift.",
        trains: "Confirming the person on an opening or closing shift is actually a keyholder, not trusting the name in the cell." },
      { area: "Weekday morning coverage", verdict: "ship", mode: "fact",
        output: "Weekday mornings staff two associates plus a keyholder, matching the coverage and opening rules.",
        why: "Correct. Two on the floor plus a keyholder on the open — the coverage minimum and the keyholder rule are both met. A clean block.",
        cost: "Re-working coverage that already meets the rules just delays publishing the roster.",
        trains: "Recognizing a shift that satisfies the rules and leaving it." },
      { area: "Ana — Thursday & Friday", verdict: "flag", severity: "major", mode: "fact", pattern: "stale",
        output: "Ana is scheduled Thursday and Friday 2–10.",
        why: "Built off stale availability. Ana's approved time off for Thursday and Friday was submitted last week, but the roster used last month's availability and never reflected it — so she's scheduled on days she's off.",
        cost: "Two shifts that will simply not be worked — a no-show the roster created, and a same-day scramble to cover the floor.",
        trains: "Checking the schedule against the current availability and approved time off, not the version the draft was built on." },
      { area: "Friday close staffing", verdict: "ship", mode: "judgment",
        output: "The two strongest closers are put on Friday night, the week's busiest shift.",
        why: "A sound call. Weighting the most capable closers to the busiest, highest-stakes shift is exactly the judgment a good roster makes — nothing to change.",
        cost: "Reshuffling a deliberate, well-judged staffing choice trades a stronger shift for a weaker one for no reason.",
        trains: "Recognizing a smart staffing judgment and letting it stand." },
    ],
    lesson: "The under-counted overtime week and the single-cover Saturday floor were the two that would have been yours to answer for. AI fills a roster that reads complete in seconds — but the store runs on the shifts you publish, and a hidden gap is a shift nobody shows up for.",
  },

  "ops-vendor-sow": {
    slug: "ops-vendor-sow", career: "Operations & Admin", kind: "document",
    short: "Sign off an AI-drafted vendor SOW before you countersign — the term, the service levels, the fee math, and an unchecked claim.",
    client: "Northgate Managed IT — helpdesk services SOW",
    artifact: "Northgate_Helpdesk_SOW.docx",
    role: "You countersign this — every term binds the company, and the vendor delivers to what's on the page.",
    aiDid: "AI drafted the statement of work for a managed-helpdesk engagement — scope, term, service levels, and a fee schedule — ready to countersign. The clauses read like standard boilerplate; some of them aren't in your favor, and one key term isn't there at all.",
    thesis: "The AI drafted the vendor SOW — scoped, termed, priced, ready to countersign. A SOW is where a helpful draft quietly gives away the store or leaves out the term you'll need. Sign off only what you'd stand behind.",
    brief: [
      { l: "Engagement", v: "Outsourced IT helpdesk, per-seat monthly fee" },
      { l: "Your playbook", v: "Terms no longer than 12 months; response-time SLAs with service credits" },
      { l: "Watch", v: "The renewal term, the service levels, the fee math, and any vendor claim" },
      { l: "Rule", v: "Every term must match the playbook, and the numbers must foot, before it's signable" },
    ],
    items: [
      { area: "Term & renewal", verdict: "flag", severity: "critical", mode: "judgment", pattern: "overreach",
        output: "\"This SOW auto-renews for successive 24-month terms; termination requires 120 days' written notice. No termination for convenience.\"",
        why: "Straight past the playbook. Your limit is a 12-month term — this locks in rolling two-year commitments with a long notice window and no way out for convenience. Miss the 120-day date and you're bound for another two years.",
        cost: "A multi-year lock-in nobody signed up for, on a service you can't easily exit — the term a procurement lead escalates the moment they see it.",
        trains: "Catching the term and renewal lock-in dressed up as ordinary boilerplate." },
      { area: "Service levels", verdict: "flag", severity: "major", mode: "judgment", pattern: "omission",
        output: "The SOW specifies scope and hours of coverage, but names no response-time targets and no service credits.",
        why: "A missing term, not a written-wrong one. Your playbook requires response-time SLAs with credits — \"coverage hours\" without targets or remedies leaves you no recourse when tickets sit for days. The gap is the problem.",
        cost: "A helpdesk with no measurable obligation and no penalty for missing it — you inherit the downtime with nothing to enforce against.",
        trains: "Catching the clause that should be there and isn't — the omission you only see if you know the deal needs it." },
      { area: "Fee schedule", verdict: "flag", severity: "minor", mode: "fact", pattern: "miscalc",
        output: "\"Monthly fee $6,500; annual total $84,000.\"",
        why: "The annual figure doesn't foot. $6,500 × 12 is $78,000, not $84,000 — a $6,000 slip between the monthly rate and the stated annual total in the same clause.",
        cost: "A signed contract that states two different prices — an ambiguity the vendor can read the higher way, and a dispute the first time an annual invoice lands.",
        trains: "Re-performing the fee math inside the contract, not trusting a stated total." },
      { area: "Security claim", verdict: "flag", severity: "major", mode: "judgment", pattern: "unverified",
        output: "\"Vendor is SOC 2 Type II compliant.\" No report or attestation is attached or required.",
        why: "Accepted at face value. A helpdesk vendor will hold access to your systems and data — a bare compliance claim with no report referenced, no attestation attached, and no obligation to provide one isn't verification, it's a sentence.",
        cost: "You certify a control posture you never saw evidence of — and own the gap if the vendor's access is breached and the claim turns out to be aspirational.",
        trains: "Requiring the evidence behind a security claim before it anchors the agreement, not accepting the assertion." },
      { area: "Payment terms", verdict: "ship", mode: "fact",
        output: "\"Fees are invoiced monthly in arrears, due Net 30 from the invoice date.\"",
        why: "Standard and reasonable. Monthly in arrears at Net 30 is a conventional, fair payment term — nothing to redline.",
        cost: "Reopening a market-standard payment term burns cycles and signals you can't tell a clean clause from a risky one.",
        trains: "Recognizing a market-standard term and letting it stand." },
      { area: "Acceptance & governing law", verdict: "ship", mode: "judgment",
        output: "\"Deliverables are deemed accepted after a 10-business-day review window; the SOW is governed by the laws of the State of Delaware, standard venue.\"",
        why: "Reasonable and standard. A defined acceptance window gives you time to reject bad work, and Delaware governing law is a conventional, defensible choice — no issue.",
        cost: "Fighting a fair acceptance window and a standard governing-law clause spends negotiation capital you'll want for the terms that matter.",
        trains: "Letting conventional, low-risk clauses through." },
    ],
    lesson: "The two-year auto-renew lock-in and the missing service levels were the two that would have been yours to answer for. AI drafts a SOW that reads like clean boilerplate in seconds — but every term ships under your signature, and the give-aways and the gaps read exactly like the clauses around them.",
  },
};
