/* Legal & Compliance — Judgment Gym lane. The AI drafts the redline, the memo,
   the review; you sign off only what holds. Same shape as every other lane
   (see lib/gym.ts). Real, checkable errors a lawyer or compliance pro would
   catch — an uncapped liability clause, a missing disclosure, a fabricated
   right, a superseded rule — seeded alongside genuinely sound work to leave
   alone. US law and conventions throughout. All items tagged mode + pattern. */

import type { Scenario } from "@/lib/gym";

export const LEGAL_SCENARIOS: Record<string, Scenario> = {
  "legal-contract-redline": {
    slug: "legal-contract-redline", career: "Legal & Compliance", kind: "contract",
    short: "Sign off an AI-marked-up vendor MSA before you approve it — liability, indemnity, data terms, and what's missing.",
    client: "Vendor Master Services Agreement — your company is the customer",
    artifact: "Vendor_MSA_Redline.docx",
    role: "You approve this redline — the terms you accept bind the company under its signature.",
    aiDid: "AI reviewed the vendor's paper, summarized each clause, and proposed the accepted terms end-to-end. It reads like clean boilerplate; some of it isn't in your favor, and one thing that should be there isn't.",
    thesis: "The AI marked up the vendor's contract — clauses summarized, redlines proposed, ready to approve. A contract is where a helpful AI quietly accepts the terms you'd never sign. Approve only what you'd actually stand behind.",
    brief: [
      { l: "Deal", v: "SaaS platform that will process your customers' personal data" },
      { l: "Your playbook", v: "Liability capped at 12 months' fees; you don't indemnify the vendor for its own fault" },
      { l: "Watch", v: "Liability, indemnity, the data terms, and any required clause left out" },
      { l: "Rule", v: "Terms must match the playbook and the law before they're approvable" },
    ],
    items: [
      { area: "Limitation of liability", verdict: "flag", severity: "critical", mode: "judgment", pattern: "overreach",
        output: "“Customer's liability under this Agreement shall be unlimited for any breach; Vendor's liability is capped at the fees paid in the prior three (3) months.”",
        why: "Backwards and off the playbook. Your liability is left uncapped while the vendor's is capped at three months' fees — the exact term you never accept. Liability should be mutual and capped, normally at twelve months' fees.",
        cost: "Uncapped exposure on your side against a vendor who has capped its own at almost nothing. One incident and your downside has no ceiling while theirs is trivial — the clause a GC escalates the moment they see it.",
        trains: "Reading a liability clause for who is actually capped and who isn't, not just that a cap exists somewhere." },
      { area: "Indemnification", verdict: "flag", severity: "major", mode: "fact", pattern: "overreach",
        output: "“Customer shall indemnify and hold Vendor harmless from all claims arising from the Services, including claims arising from Vendor's own negligence.”",
        why: "It sweeps in the vendor's own negligence. You indemnify for your misuse — not for the vendor's fault. Agreeing to cover their negligence flips the risk of their own bad work onto you.",
        cost: "You've agreed to pay for harm the vendor itself caused. When their negligence produces a third-party claim, the bill routes to you under a clause that read like standard indemnity language.",
        trains: "Catching the indemnity that reaches past your own conduct to cover the other side's fault." },
      { area: "Payment terms", verdict: "ship", mode: "fact",
        output: "“Fees are due Net 30 from the invoice date; 1.5% per month accrues on undisputed late amounts.”",
        why: "Standard and reasonable. Net 30 with a conventional late-payment rate on undisputed amounts — nothing to redline here.",
        cost: "Reopening a market-standard payment term wastes cycles and signals you can't tell a clean clause from a risky one.",
        trains: "Recognizing a conventional commercial term and letting it stand." },
      { area: "Cross-border data transfer", verdict: "flag", severity: "major", mode: "fact", pattern: "stale",
        output: "“Any transfer of personal data outside the EU is legitimized under the EU-US Privacy Shield Framework.”",
        why: "A superseded mechanism. The Privacy Shield was invalidated by the Court of Justice in Schrems II (2020); transfers now rest on Standard Contractual Clauses or the 2023 EU-US Data Privacy Framework. The clause relies on a framework that no longer exists.",
        cost: "The transfer has no valid legal basis, so every cross-border flow under this contract is unlawful from day one — a regulatory exposure that sits quietly until an authority or a data subject raises it.",
        trains: "Checking that a named legal mechanism is still current, not that a mechanism is merely cited." },
      { area: "Data breach notification", verdict: "flag", severity: "major", mode: "fact", pattern: "omission",
        output: "The data-protection section covers security controls and audit rights, but says nothing about notifying you if the vendor suffers a breach.",
        why: "A required term is missing. A processor handling your customers' data must be contractually bound to notify you of a breach without undue delay — that's how you meet your own notification deadlines. The clause is silent, and the AI didn't flag the gap.",
        cost: "A breach at the vendor with no duty to tell you promptly. You miss your own statutory notification windows because you found out late — and the liability for that lands on you, not them.",
        trains: "Catching the clause that should be there and isn't — the omission you only see if you know the deal requires it." },
      { area: "Confidentiality", verdict: "ship", mode: "judgment",
        output: "“Each party shall protect the other's Confidential Information with the same care it uses for its own, and no less than a reasonable standard, for three (3) years after disclosure.”",
        why: "Mutual, reasonable, and time-bound. A conventional confidentiality clause with a standard survival period — balanced for both sides.",
        cost: "Fighting a fair, mutual confidentiality term burns negotiation capital you'll want for the clauses that actually matter.",
        trains: "Letting a balanced, conventional clause through." },
    ],
    lesson: "The uncapped liability and the indemnity for the vendor's own negligence were the two that would have been yours to answer for. AI redlines a contract in seconds — but the terms bind the company under your approval, and the give-aways read exactly like the boilerplate around them.",
  },

  "legal-compliance-memo": {
    slug: "legal-compliance-memo", career: "Legal & Compliance", kind: "memo",
    short: "Sign off an AI-drafted CCPA/CPRA compliance memo before the business relies on it — the citation, the applicability call, and the rule it skipped.",
    client: "Brightloom Retail — CCPA/CPRA readiness memo before a data-sharing launch",
    artifact: "Brightloom_Privacy_Memo.docx",
    role: "You sign this memo — the business builds its launch on the conclusions you approve.",
    aiDid: "AI drafted the privacy compliance memo from the business's plan and its own reading of the statute — confident, referenced, and ready to circulate. Some of the law it states is wrong, and one conclusion rests on a rule it never fully checked.",
    thesis: "The AI drafted the compliance memo the business will rely on — the law summarized, the risks assessed, a green light at the bottom. A wrong rule stated with confidence is worse than no memo. Sign off only what the statute actually supports.",
    brief: [
      { l: "Business", v: "DTC retailer preparing to share customer data with ad partners" },
      { l: "Framework", v: "California CCPA, as amended by the CPRA (in effect since 2023)" },
      { l: "Watch", v: "Any statute the memo cites, the applicability call, and required consumer disclosures" },
      { l: "Rule", v: "Every legal statement must tie to the current text; conclusions must be tested, not asserted" },
    ],
    items: [
      { area: "Private right of action", verdict: "flag", severity: "critical", mode: "fact", pattern: "fabrication",
        output: "“Consumers may sue the company for statutory damages for any violation of the CCPA.”",
        why: "Wrong, and stated with total confidence. The CCPA's private right of action is narrow — it's limited to certain data breaches under §1798.150. Consumers can't sue for any violation; enforcement of the rest sits with the Attorney General and the CPPA. The memo invents a liability that doesn't exist.",
        cost: "The business makes launch decisions to avoid a lawsuit exposure that isn't real, or — worse — trusts this memo's grasp of the statute on the points that are real. A confident, wrong statement of the law is the most dangerous line in the file.",
        trains: "Testing a stated legal rule against the actual statute, not trusting fluent legal phrasing." },
      { area: "Applicability threshold", verdict: "flag", severity: "major", mode: "judgment", pattern: "unverified",
        output: "“The company's annual revenue is below $25 million, so the CCPA does not apply and no further analysis is needed.”",
        why: "It closes the point on one prong of a three-prong test. The CCPA also applies to a business that buys, sells, or shares the personal data of 100,000+ consumers, or derives 50%+ of revenue from selling data — either can trigger it regardless of revenue. The AI accepted the tidy revenue answer and stopped.",
        cost: "A retailer about to share data at scale is told the law doesn't apply — when the very launch it's assessing likely crosses the 100,000-consumer trigger. The whole compliance program gets skipped on a half-checked conclusion.",
        trains: "Refusing to let a memo close applicability on one prong of a multi-part test — check every trigger before concluding the rule is off." },
      { area: "Right-to-opt-out scope", verdict: "flag", severity: "major", mode: "fact", pattern: "stale",
        output: "“Consumers have the right to opt out of the sale of their personal information; the plan addresses this.”",
        why: "Pre-CPRA framing. Since the CPRA amendments took effect in 2023, the opt-out right covers both the sale and the sharing of personal information (sharing for cross-context behavioral advertising), plus new rights to limit use of sensitive personal information. A memo about an ad-partner launch that addresses only “sale” misses the concept that actually governs it.",
        cost: "The exact activity being launched — sharing data for targeted ads — falls under the “sharing” right the memo doesn't cover. The company builds an opt-out that doesn't reach the practice that needs it.",
        trains: "Checking the memo against the current, amended text, not the version of the statute that was true a few years ago." },
      { area: "Required consumer notice", verdict: "flag", severity: "major", mode: "fact", pattern: "omission",
        output: "The memo covers the privacy-policy update but doesn't mention a “Notice at Collection” or a “Do Not Sell or Share My Personal Information” link.",
        why: "A required disclosure is missing. The CCPA/CPRA require a notice at or before the point of collection and, for a business that sells or shares data, a clear opt-out link. The memo addresses the policy but leaves out the front-end disclosures the law mandates.",
        cost: "The site launches without the notices the statute requires — a straightforward, on-the-face violation that a regulator or a consumer advocate spots on the homepage.",
        trains: "Catching the mandated disclosure the memo never surfaced — the omission that's invisible unless you know the rule requires it." },
      { area: "Service-provider contracts", verdict: "ship", mode: "judgment",
        output: "Recommends putting CCPA-compliant service-provider terms in place with each ad partner before any data flows, and distinguishes a service provider from a third party.",
        why: "Sound and correct. The service-provider/third-party distinction drives whether a data flow is a “sale/share,” and getting the contracts right up front is exactly the correct step. Good analysis.",
        cost: "Second-guessing a well-reasoned, correct recommendation delays a launch the business is right to plan carefully.",
        trains: "Recognizing legal analysis that's actually right and letting it stand." },
      { area: "Data-retention position", verdict: "ship", mode: "judgment",
        output: "Advises disclosing retention periods by category and not keeping personal information longer than reasonably necessary for the disclosed purpose.",
        why: "Correct under the CPRA's data-minimization and retention-disclosure requirements. A defensible, on-point position.",
        cost: "Reworking a correct retention position just slows the memo.",
        trains: "Confirming a conclusion that matches the current rule and moving on." },
    ],
    lesson: "The invented private right of action and the applicability call closed on one prong were the two that would have been yours to answer for. The AI drafts a confident memo in seconds — but the business relies on the law you sign, and a rule stated wrong reads exactly like the parts that are right.",
  },

  "legal-nda-review": {
    slug: "legal-nda-review", career: "Legal & Compliance", kind: "document",
    short: "Sign off an AI-reviewed mutual NDA before you counter-sign — term, definitions, and the covenants smuggled in.",
    client: "Mutual NDA — sent by a counterparty before partnership talks",
    artifact: "Counterparty_Mutual_NDA.docx",
    role: "You counter-sign this — every term binds your company, including the ones an NDA has no business containing.",
    aiDid: "AI reviewed the counterparty's NDA, summarized it as “standard mutual, low risk,” and recommended signing. It mostly is standard — but a few terms reach well past confidentiality, and one protection you'd expect is missing.",
    thesis: "The AI reviewed the NDA and called it standard, ready to sign. An NDA is short and looks harmless — which is exactly where over-reaching terms hide. Counter-sign only what an NDA should actually contain.",
    brief: [
      { l: "Context", v: "A mutual NDA to explore a partnership; you're the receiving party as much as the disclosing one" },
      { l: "Watch", v: "The confidentiality term, the definition and its carve-outs, and anything that isn't about confidentiality" },
      { l: "Rule", v: "An NDA protects information — it shouldn't assign rights or restrict conduct beyond that" },
    ],
    items: [
      { area: "Term of confidentiality", verdict: "flag", severity: "major", mode: "judgment", pattern: "overreach",
        output: "“The obligations of confidentiality shall survive in perpetuity as to all Confidential Information disclosed under this Agreement.”",
        why: "Overbroad. A perpetual obligation over all information is impractical and one-sided — a definite term (commonly 2-5 years) is standard, with perpetual survival reserved for trade secrets specifically. As drafted you're bound forever on ordinary business information.",
        cost: "An indefinite obligation you can never close out — a compliance burden that outlives the deal, the relationship, and any memory of what was even shared.",
        trains: "Catching the perpetual term dressed up as ordinary confidentiality — durations are the trap in a short NDA." },
      { area: "Definition of Confidential Information", verdict: "flag", severity: "major", mode: "fact", pattern: "omission",
        output: "Defines Confidential Information broadly, with no exclusions for information that is public, already known, independently developed, or lawfully received from a third party.",
        why: "The standard carve-outs are missing. Every workable NDA excludes information that's public, that you already had, that you develop independently, or that a third party gives you freely. Without them you're on the hook for information you were always free to use.",
        cost: "You can be accused of breach for using knowledge you had before the deal or developed on your own — an unwinnable position that a functioning NDA is specifically drafted to prevent.",
        trains: "Reading a confidentiality definition for the exclusions that should bound it, not just what it sweeps in." },
      { area: "Non-solicitation", verdict: "flag", severity: "major", mode: "judgment", pattern: "overreach",
        output: "“During the term and for two (2) years after, neither party shall solicit or hire the other's employees.”",
        why: "This doesn't belong in an NDA. A two-year no-hire is a restrictive covenant on your conduct, unrelated to protecting information — smuggled into a document you'd sign quickly because it's “just an NDA.” It needs its own negotiation, if it's agreed at all.",
        cost: "You've quietly agreed to a two-year hiring restriction across the other party's workforce, buried in a confidentiality agreement — a real constraint on the business that no one weighed as one.",
        trains: "Spotting the covenant that has nothing to do with confidentiality riding inside the NDA." },
      { area: "Ownership of disclosed ideas", verdict: "flag", severity: "critical", mode: "fact", pattern: "overreach",
        output: "“All ideas, concepts, and materials disclosed hereunder, and any derivatives thereof, shall be the exclusive property of the Disclosing Party.”",
        why: "An IP grab an NDA should never contain. An NDA governs the use and protection of information — it doesn't assign ownership. This clause hands the disclosing party rights in anything derived from what's shared, in both directions, dressed as a confidentiality term.",
        cost: "Anything your team builds that touches what was disclosed could be claimed by the other side — a live IP dispute created by a document everyone treated as a formality.",
        trains: "Catching the ownership-assignment clause hiding in an agreement that's only supposed to protect information." },
      { area: "Injunctive relief", verdict: "ship", mode: "judgment",
        output: "“The parties agree that a breach may cause irreparable harm for which monetary damages are inadequate, and that the non-breaching party may seek injunctive relief.”",
        why: "Standard and mutual. The acknowledgment that a confidentiality breach may warrant an injunction is conventional in NDAs and applies evenly to both sides. Nothing to flag.",
        cost: "Reopening a conventional, mutual remedies clause wastes time on the part that's fine.",
        trains: "Recognizing a standard clause that runs both ways and letting it stand." },
      { area: "Return or destruction of materials", verdict: "ship", mode: "fact",
        output: "“Upon request or termination, each party shall return or destroy the other's Confidential Information and confirm destruction in writing.”",
        why: "Correct and mutual. A clean return-or-destroy obligation with written confirmation — exactly what an NDA should provide, applied to both parties.",
        cost: "Querying a standard, mutual return-or-destroy clause just delays the signature.",
        trains: "Confirming a conventional, balanced NDA term and moving on." },
    ],
    lesson: "The smuggled non-solicit and the ownership grab were the two that would have been yours to answer for. The AI called a short document “standard” — but an NDA is exactly where a covenant or an IP assignment hides, because no one reads a formality closely before they sign it.",
  },
};
