import { NextResponse } from "next/server";
import { getOrCreateMapNarrative, type ReadStanding } from "@/lib/map-narrative";
import { getStanding } from "@/lib/standing";
import { getOrCreateProfile } from "@/lib/member";
import { requireMember } from "@/lib/gate";
import { aiConfigured } from "@/lib/ai";

/** The member's current standing (map reading + work banked) so the read reflects
 *  the improvement, not just the raw map reading. */
async function currentStanding(userId: string): Promise<ReadStanding | undefined> {
  const profile = await getOrCreateProfile();
  const s = await getStanding(userId, profile?.careerSlug, profile?.currentLane);
  return s.hasMap && s.current != null ? { current: s.current, dividend: s.dividend } : undefined;
}

// The member's personal Map reading — generated by Claude, grounded in their
// saved (deterministically-computed) Map, cached on the snapshot. Fetched
// client-side from the dashboard so generation never blocks the page render.
export const maxDuration = 60;

export async function GET() {
  const userId = await requireMember();
  if (!userId) return NextResponse.json({ narrative: null });
  if (!aiConfigured()) return NextResponse.json({ narrative: null });

  const read = await getOrCreateMapNarrative(userId, await currentStanding(userId));
  return NextResponse.json({ narrative: read?.narrative ?? null });
}

// Force a fresh read (ignores the cached one) — the member's "regenerate".
export async function POST() {
  const userId = await requireMember();
  if (!userId) return new NextResponse("Forbidden", { status: 403 });
  if (!aiConfigured()) return NextResponse.json({ narrative: null });

  const read = await getOrCreateMapNarrative(userId, await currentStanding(userId), true);
  return NextResponse.json({ narrative: read?.narrative ?? null });
}
