import { NextResponse } from "next/server";
import { auth } from "@clerk/nextjs/server";
import { getOrCreateMapNarrative } from "@/lib/map-narrative";
import { aiConfigured } from "@/lib/ai";

// The member's personal Map reading — generated by Claude, grounded in their
// saved (deterministically-computed) Map, cached on the snapshot. Fetched
// client-side from the dashboard so generation never blocks the page render.
export const maxDuration = 60;

export async function GET() {
  const { userId } = await auth();
  if (!userId) return new NextResponse("Unauthorized", { status: 401 });
  if (!aiConfigured()) return NextResponse.json({ narrative: null });

  const read = await getOrCreateMapNarrative(userId);
  return NextResponse.json({ narrative: read?.narrative ?? null });
}
